### ISSUE TITLE
Use xrandr instead of xinerama to detect screens

### ISSUE THREAD

**Issue by The-Compiler** [herbstluftwm/herbstluftwm#10]
xrandr is probably more standard, but it seems rather hard to use it...

Some pointers:
- https://github.com/LemonBoy/bar/blob/master/lemonbar.c#L834-L926
- https://github.com/Guff/guffml/blob/3272817b4e659710f3eaa7f3363284b0df105347/guffml/linux/guffml-videomodex11.c
- https://git.gnome.org/browse/gnome-panel/tree/gnome-panel/panel-multiscreen.c

Also it'd be nice if the monitors get auto-named based on their connecors (`vga1`, `lvds1`, etc.)

**Comment by t-wissmann** [comment]
It has been implemented (except for the last comment about names). Feel free to open another issue if you also need the output names as monitor names. :-)
