### ISSUE TITLE
Version copyright notice is out of date.

### ISSUE THREAD

**Issue by PorkrollPosadist** [herbstluftwm/herbstluftwm#1000]
Super minor issue, but I might as well record it.  It looks like the copyright message hasn't been updated in 6 years.

```
$ herbstluftwm --version
herbstluftwm 0.8.3
Copyright (c) 2011-2014 Thorsten Wißmann
Released under the Simplified BSD License
xrandr support: on
xinerama support: on
```

That is all.  Thanks for working on this project. :+1:

**Comment by t-wissmann** [comment]
Indeed, one should update this from time to time to avoid the impression of the project being abandoned. Thanks for the reminder/motivation to do so!
