### ISSUE TITLE
spawn does not refresh the comand

### ISSUE THREAD

**Issue by Vintodrimmer** [herbstluftwm/herbstluftwm#101]
Good day,

Sorry for strange title, but I don't know how to phrase it better.

I use keybindings for such things as screenshots and watching online videos through `mpv`. The problem is that once the appropriate line is executed, it does not change on the next keypress.

Let's say I want to make a screenshot, using `hc keybind Control-Print spawn maim -s /tmp/$(date +%Y-%m-%d-%T)-screenshot.png`. This would create a screenshot with the current time and date. Now 10 minutes have passed and I want to take another one. Instead of getting a new file, the _previous one_ will be overwritten.

Same with `hc keybind Shift-Control-v spawn mpv $(xsel -o)`. Let's say i copied a link and pressed the according combination on the keyboard. At first the result would be expected, But if I copy the next link and try that again, the first video would play again, instead of the new one.

It's very likely that I'm doing something wrong there. I simply added the lines to the autostart. Maybe that was inappropriate?

**Comment by The-Compiler** [comment]
Yeah, this won't work - bash replaces the things inside `$(...)` with their value when your autostart is run.

If you want to do this kind of thing, either put the commands in their own bash script and execute that, or do something like `hc keybind Shift-Control-v spawn bash -c "mpv $(xsel -o)"` so you actually spawn another bash shell when the key is pressed.

**Comment by Vintodrimmer** [comment]
Thanks!

**Comment by t-wissmann** [comment]
I guess there's a typo in @The-Compiler's keybind-line, because the `$(...)` within the double quotes are still evaluated when the binding is done, and not when the key is hit. So the correct line is:
```
hc keybind Shift-Control-v spawn bash -c 'mpv "$(xsel -o)"'
```

**Comment by The-Compiler** [comment]
Yup, my bad - thanks for the follow-up!
