### ISSUE TITLE
Share screen in teams broken

### ISSUE THREAD

**Issue by AckslD** [herbstluftwm/herbstluftwm#1011]
When I try sharing my screen in [teams](https://aur.archlinux.org/packages/teams/) the screen gets black with a small red edge around it and I am not able to for example change tags or anything else. If I try to close the window I disconnect from the meeting.

Not sure if this is a bug with teams or not but thought I would ask here if anyone has some ideas why this might happen.

**Comment by blarz** [comment]
This is a problem discussed on several MS issue reports. This fixed it for me:
``` sudo mv /usr/share/teams/resources/app.asar.unpacked/node_modules/slimcore/bin/rect-overlay /usr/share/teams/resources/app.asar.unpacked/node_modules/slimcore/bin/bad-rect-overlay```

**Comment by AckslD** [comment]
Great seems to work!

**Comment by The-Compiler** [comment]
FWIW I had this issue on my old laptop, but everything works fine with the overlay on my own laptop with hlwm on 7c0283b4 and teams 1.3.00.16851-1 on Archlinux - so I wonder if this got fixed somehow?

**Comment by blarz** [comment]
The funny thing is, that is really just a node app drawing a red rectangle. Fascinating :D

**Comment by blarz** [comment]
> FWIW I had this issue on my old laptop, but everything works fine with the overlay on my own laptop with hlwm on [7c0283b](https://github.com/herbstluftwm/herbstluftwm/commit/7c0283b4dd087e8280c48fa2cac8a7105ffe1ae9) and teams 1.3.00.16851-1 on Archlinux - so I wonder if this got fixed somehow?

I haven't checked with newer teams version, I can try tomorrow.

Most annoying is that #543 still persists.
