### ISSUE TITLE
[Mac Port] Update request for macOS version of this WM

### ISSUE THREAD

**Issue by branwright1** [herbstluftwm/herbstluftwm#1012]
Hello, Is it possible to update 6yo version of https://trac.macports.org/browser/trunk/dports/x11/herbstluftwm?order=name to latest version from Linux and BSD?

**Comment by t-wissmann** [comment]
Hi, I'm not using macOS, so I think it's more promising if you open a bug report at the macports project. Also note that the on mac, hlwm is only able to manage X windows but not the other native mac applications.
