### ISSUE TITLE
Forum for a better communication

### ISSUE THREAD

**Issue by diegobernardes** [herbstluftwm/herbstluftwm#102]
Found Herbstluftwm a week ago, it's a really amazing project, it just solved everything i thought was wrong with I3. But took a time to get everything running, don't know if this is the right place to question this. What you guys think of running something like [Discourse](https://www.discourse.org/), i think it lower the entry point to new users.

Herbstluftwm , need more visibility for new users like me.

**Comment by vyp** [comment]
I know it isn't the same as a discourse for new users but fwiw in case you missed it in the readme there is an irc channel at #herbstluftwm on freenode. 🙂
