### ISSUE TITLE
adjust for xrandr scale function

### ISSUE THREAD

**Issue by Xenate** [herbstluftwm/herbstluftwm#1050]
On my HiDPI display, I need to use the bash command "xrandr --output <OUTPUT_DISPLAY> --scale 0.75x0.75". To decrease the resolution uniformly but when I do this it zooms into the top left corner instead of adjusting to display the desktop with a lower resolution. Any tips on how to fix this?

**Comment by daddeffe** [comment]
#194 
Like this one try to launch
```
herbstclient detect_monitors
```
I tried and worked for me

**Comment by daddeffe** [comment]
@Xenate can you check and close the issue if it works?

**Comment by t-wissmann** [comment]
I guess it did :-) If there further issues. feel free to re-open.
