### ISSUE TITLE
Fedora package is only version 0.7.2

### ISSUE THREAD

**Issue by Simerax** [herbstluftwm/herbstluftwm#1054]
Maybe it's not the right place to ask, if so just tell me to get lost :joy: 

The official [rpm package](https://src.fedoraproject.org/rpms/herbstluftwm) on Fedora for herbstluft is only version 0.7.2. Is someone in contact with the maintainer of that rpm? Is it possible to get the latest version on there?

**Comment by The-Compiler** [comment]
According to that page, @sham1 (same nick on GitHub) is the maintainer.

**Comment by Simerax** [comment]
I sent him an e-mail and notified him about this issue here. I would suggest we leave this issue open for now just in case someone else is in the same situation as me.

In case he/she is not reachable within the next weeks we could think about either adding a fedora disclaimer or make use of the fedora [Non-responsive maintainer policy](https://docs.fedoraproject.org/en-US/fesco/Policy_for_nonresponsive_package_maintainers/)

**Comment by sham1** [comment]
Yeah, hi. So I was contacted about this, and I will go ahead and update the package for Fedora 33 and Rawhide ASAP.

I suppose 0.9.0 is good?

**Comment by blarz** [comment]
> I suppose 0.9.0 is good to go?

Most certainly!

Be aware that there was a switch to CMake for the build system.

**Comment by sham1** [comment]
Alright, the build itself is now done, now we have to wait for it to get to the distribution itself, which takes a bit.

Now, it'd be wonderful if there was some input as to whether the update is actually working. The instructions for getting the testing version before the package stabilises and hits the repos can be found [here.](https://bodhi.fedoraproject.org/updates/FEDORA-2020-8dd7afb411)

**Comment by Simerax** [comment]
Works like a charm on my laptop :+1: 
I will close the issue as soon as the update is in stable

**Comment by Simerax** [comment]
Let's not put this in stable yet. it looks like the wm crashes on that build #1056

**Comment by sham1** [comment]
Right. It's now unpushed. I've now also commented on the linked issue, and try to help with fixing it.

**Comment by sham1** [comment]
Alright. [I have now taken the latest commit and packaged that up.](https://bodhi.fedoraproject.org/updates/FEDORA-2020-1a4776d06d)

Make sure to look for any other bugs that may happen with this version.

**Comment by t-wissmann** [comment]
Thanks!

**Comment by Simerax** [comment]
I have not encountered any problems so far.
I'm also unable to reproduce #1056 anymore - looks like the fix works :+1:

**Comment by Simerax** [comment]
update is in stable

**Comment by t-wissmann** [comment]
Great! thanks for letting us know!
