### ISSUE TITLE
Watching attributes (comments requested)

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#1098]
Right now, it is not possible to get notified when an attribute value changes. For example, when showing the current layout algorithm in the panel (pursued in issue #71), one does not know yet when an update of the panel is necessary.

Right now, I'm planning to add a command `watch` such that one can run:
```
hc watch tags.focus.tiling.focused_frame.algorithm
```
This will emit one hook whenever the attribute has a different value, and the format is probably:
```python
attribute_changed ATTRIBUTE_PATH NEW_VALUE
```
For example:
```
attribute_changed tags.focus.tiling.focused_frame.algorithm grid
```

There are two kinds of changes:
  * The value of the attribute changes (e.g. another layout is selected)
  * The links between objects change (e.g. another frame is selected)

Because of the second item, the existence of dynamic links (such as `focused_frame`), and dynamic attributes, the best implementation I can think of is plain polling. That is, we have to read all the watched attributes in every iteration of the main algorithm. This would imply that if a attribute changes forth and back within one command / event, it will not be noticed. (Maybe this is desirable, maybe not).

If you have comments/ideas, let me know.

**Comment by bklaase** [comment]
wouldn't it be nicer to be able to overload attribute setters a conditional (ea it is being watched in a rule) event emmision?

Or is that precisely not possible due to the dynamic links/attributes?

**Comment by tiosgz** [comment]
This is probably a stupid comment — but can you watch when the links change; or define another thing that causes the change? & how hard would it be to keep the old state (of the whole object tree?) so that you can notify only about what’s actually changed?

Also, shouldn’t the hook include the old value? (This again requires knowing the old state?)

**Comment by t-wissmann** [comment]
> wouldn't it be nicer to be able to overload attribute setters a conditional (ea it is being watched in a rule) event emmision?
> 
> Or is that precisely not possible due to the dynamic links/attributes?

I'm not sure what you mean by overloading the setters. Overloading sounds as if the overloaded setter could deny a value that's about to be written to the attribute. But you're right, that the dynamic links and attributes don't hav setters. E.g. `tags.focus.frame_count` has no setter, but when someone reads the attribute, a function is called that actively counts the number of frames.


> This is probably a stupid comment — but can you watch when the links change; or define another thing that causes the change? & how hard would it be to keep the old state (of the whole object tree?) so that you can notify only about what’s actually changed?

In hlwm's implementation, I can watch links change rather easily, but only with a few exceptions like `focused_frame`. Maybe I don't get the "what's actually changed" question: Do you want to by informed *why* the value of e.g. `tags.focus.tiling.focused_frame.algorithm` has changed? (such that you can distinguish the two cases I wrote above?)

> Also, shouldn’t the hook include the old value? (This again requires knowing the old state?)

Good point! With my implementation in mind, it would be easy include the old value!

**Comment by tiosgz** [comment]
> In hlwm's implementation, I can watch links change rather easily, but only with a few exceptions like `focused_frame`.

But there’s an exact set of things that can change it & you can watch them, right?
> Maybe I don't get the "what's actually changed" question

E.g. when the `focused_frame` changes, the old & the new frame can have some properties the same — so you probably don’t want to notify about them, but only about those that differ.

OTOH someone could have a use case where they are useful as well. In that case, maybe it’d be good if these dynamic links (i.e. the objects, not only their properties) could also be watched. But let’s keep that for later.

**Comment by t-wissmann** [comment]
> > In hlwm's implementation, I can watch links change rather easily, but only with a few exceptions like `focused_frame`.
> 
> But there’s an exact set of things that can change it & you can watch them, right?

For `focused_frame` there are quite a lot of things that change it. (all `focus` and `shift` commands, `load`, `split`, `remove`)

> > Maybe I don't get the "what's actually changed" question
> 
> E.g. when the `focused_frame` changes, the old & the new frame can have some properties the same — so you probably don’t want to notify about them, but only about those that differ.

For most of the objects, there is always a property that identifies the object (more or less) uniquely, so one can watch this object (it's `index` for frames, `winid` for clients, `index` for monitors) 

> OTOH someone could have a use case where they are useful as well. In that case, maybe it’d be good if these dynamic links (i.e. the objects, not only their properties) could also be watched. But let’s keep that for later.

If people are interested in it, then it can be easily implemented.

I think I should go for the implementation and see how useful it is. Thanks for your comments!
