### ISSUE TITLE
Negative offsets for rectangles

### ISSUE THREAD

**Issue by The-Compiler** [herbstluftwm/herbstluftwm#11]
According to some standard (I don't remember which one it was...) `HxW+X+Y` also should accept negative offsets.

Probably minor, feel free to close if you disagree ;)

**Comment by johnLate** [comment]
`herbstclient add_monitor 600x600+-200+-200` works for me. Are there other commands where this doesn't work? Or do you think the syntax should be different (e.g. `600x600-200-200`)?

**Comment by t-wissmann** [comment]
The syntax should be `600x600-200-200`. But as far as I can see herbstluftwm supports this syntax (e.g. for `move_monitor`); and this is already used in [q3terminal.sh](https://github.com/herbstluftwm/herbstluftwm/blob/master/scripts/q3terminal.sh)

So I assume this issue can be closed.
