### ISSUE TITLE
display bug when merging minimized windows

### ISSUE THREAD

**Issue by apm256** [herbstluftwm/herbstluftwm#1123]
Found a minor bug: when I merge a tag containing a minimized window, it appears to be floating, until I focus it with the mouse.

Steps to reproduce:

1. `herbstclient add test`
2. `herbstclient add merged`
3. `herbstclient use test`
4. open a terminal
5. `herbstclient set_attr  clients.focus.minimized true`
6. `herbstclient use merged`
7. `herbstclient merge_tag test`
8. the terminal first appears to be floating, but becomes tiled again as soon as it is focused with the mouse.

**Comment by t-wissmann** [comment]
Thanks for the excellent bug report! I've fixed it in PR #1125.
