### ISSUE TITLE
X11/extensions/shape.h issues

### ISSUE THREAD

**Issue by smason1995** [herbstluftwm/herbstluftwm#113]
Hello,

I am trying to install herbstluftwm on the latest Solus and have run into an issue with shape.h

**X11/extensions/shape.h** does not exist in my directories, but **xcb/shape.h** does.

However, when I redirect **x11-utils.cpp** to **xcb/shape.h** it throws a bunch of errors like so

src/x11-utils.cpp: In function ‘void window_cut_rect_hole(Window, int, int, int)’:

src/x11-utils.cpp:41:31: error: ‘ShapeBounding’ was not declared in this scope
     XShapeCombineMask(d, win, ShapeBounding, -bw, -bw, p, ShapeSet);
                               ^~~~~~~~~~~~~

src/x11-utils.cpp:41:59: error: ‘ShapeSet’ was not declared in this scope
     XShapeCombineMask(d, win, ShapeBounding, -bw, -bw, p, ShapeSet);
                                                           ^~~~~~~~

src/x11-utils.cpp:41:5: error: ‘XShapeCombineMask’ was not declared in this scope
     XShapeCombineMask(d, win, ShapeBounding, -bw, -bw, p, ShapeSet);
     ^~~~~~~~~~~~~~~~~

src/x11-utils.cpp:41:5: note: suggested alternative: ‘XSetPlaneMask’
     XShapeCombineMask(d, win, ShapeBounding, -bw, -bw, p, ShapeSet);
     ^~~~~~~~~~~~~~~~~
     XSetPlaneMask

src/x11-utils.cpp: In function ‘void window_make_intransparent(Window, int, int)’:
src/x11-utils.cpp:63:31: error: ‘ShapeBounding’ was not declared in this scope
     XShapeCombineMask(d, win, ShapeBounding, -bw, -bw, p, ShapeSet);
                               ^~~~~~~~~~~~~

src/x11-utils.cpp:63:59: error: ‘ShapeSet’ was not declared in this scope
     XShapeCombineMask(d, win, ShapeBounding, -bw, -bw, p, ShapeSet);
                                                           ^~~~~~~~

src/x11-utils.cpp:63:5: error: ‘XShapeCombineMask’ was not declared in this scope
     XShapeCombineMask(d, win, ShapeBounding, -bw, -bw, p, ShapeSet);
     ^~~~~~~~~~~~~~~~~

src/x11-utils.cpp:63:5: note: suggested alternative: ‘XSetPlaneMask’
     XShapeCombineMask(d, win, ShapeBounding, -bw, -bw, p, ShapeSet);
     ^~~~~~~~~~~~~~~~~
     XSetPlaneMask

At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’

make: *** [Makefile:43: src/x11-utils.o] Error 1

Searching around google has been fruitless (and I can easily understand why), so I am wondering if I might be able to get some help solving this.

**Comment by t-wissmann** [comment]
I guess you need to install the headers for libxext on solus. I don't know how this package is called in solus. Maybe someone else how knows solus can help.

In general: xcb is something different to Xlib (and the directory for Xlib is called X11). This is why your change does not help.

**Comment by t-wissmann** [comment]
As the solus people on the irc told me, the headers should be in `libxext-devel`, so please install this package, undo your changes in the hlwm source and then try again.

And libxext is indeed the package for the libxext library containing the XShape extension: https://dev.solus-project.com/source/libxext/

**Comment by smason1995** [comment]
Thank you! That fixed my issue :)
