### ISSUE TITLE
specifying applications to specific tags

### ISSUE THREAD

**Issue by zenny** [herbstluftwm/herbstluftwm#1135]
Hi,

Great project @t-wissmann ! :+1: 

This server-client arch is what I liked because I had two incidents with dwm crash in the middle of very important errands.

However, I could not figure out exactly how to assign specific applications to specific tags, say firefox always opens in tag2.

In addition, is there a possibility of assiging keychords to accomplish specific tasks similar to discussion here (https://www.reddit.com/r/i3wm/comments/kvqcf4/is_it_possible_to_bind_mod_two_letters/) or nifty implementation in i3 (https://github.com/EllaTheCat/dopamine-2020)?

Cheers and stay safe,
/z

**Comment by The-Compiler** [comment]
> However, I could not figure out exactly how to assign specific applications to specific tags, say firefox always opens in tag2.

Via rules (see the `RULES` section in the manpage). Something like `hc rule class=firefox tag=2` (untested).

> In addition, is there a possibility of assiging keychords to accomplish specific tasks

There's some discussion about this in #751 as well as a [keychain.sh](https://github.com/herbstluftwm/herbstluftwm/blob/master/scripts/keychain.sh) script.

**Comment by zenny** [comment]
Thanks @The-Compiler, I do remember you from the qutebrowser repo. Yay!

I am looking forward to create a modular like https://github.com/EllaTheCat/dopamine-2020 within herbstluftwm.

`sxhkd` has that possibility. Is there an ideal herbstluftwm way to include the sxhkdrc without breaking?

Cheers,/

**Comment by zenny** [comment]
> > However, I could not figure out exactly how to assign specific applications to specific tags, say firefox always opens in tag2.
> 
> Via rules (see the `RULES` section in the manpage). Something like `hc rule class=firefox tag=2` (untested).

Didn't work! :(
> 
> > In addition, is there a possibility of assigning keychords to accomplish specific tasks
> 
> There's some discussion about this in #751 as well as a [keychain.sh](https://github.com/herbstluftwm/herbstluftwm/blob/master/scripts/keychain.sh) script.

**Comment by blarz** [comment]
```hc rule class=Firefox tag=2``` (mind the capital F) works for my autostart.sh.
You need to figure out the class via xprop or xwininfo.

**Comment by zenny** [comment]
@The-Compiler and @bla

> `hc rule class=Firefox tag=2` (mind the capital F) works for my autostart.sh.
> You need to figure out the class via xprop or xwininfo.



> Thanks @The-Compiler, I do remember you from the qutebrowser repo. Yay!
> 
> I am looking forward to create a modular like https://github.com/EllaTheCat/dopamine-2020 within herbstluftwm.
> 
> `sxhkd` has that possibility. Is there an ideal herbstluftwm way to include the sxhkdrc without breaking?
> 
> Cheers,/


Thanks to @The-Compiler and @blarz .

**Comment by bew** [comment]
> `sxhkd` has that possibility. Is there an ideal herbstluftwm way to include the sxhkdrc without breaking?

Technically you can use sxhkd to define all your keys, and not define any in your hlwm' config
