### ISSUE TITLE
Option to change cursor when mouse focuses window-border

### ISSUE THREAD

**Issue by astier** [herbstluftwm/herbstluftwm#1138]
Changing the cursor when the mouse focuses a window-border as an visual indicator could be helpful in the following scenarios:

1. Grabbing thin-borders
2. Preventing accidentally grabbing borders. For example I sometimes try to grab the scrollbar of a window but accidentally grab the window border and resize it instead of scrolling.

The only issue I see is that if you would drag the mouse over the screen each time the mouse crosses a border it would change the cursor. Some people could find it annoying. It probably should be optional. A timer could be a solution such that the cursor doesnt change immediately.

An alternative solution would be instead of changing the cursor an option could be introduced to disable resizing a window by dragging the window-border.

**Comment by astier** [comment]
I figured that disabling the dragging-feature would be the best for my case because I never use it anyway. I opened another issue #1141 which would be my preference. My request in this issue would be just a workaround if you dont want to implement #1141 If you are willing to implement #1141 you can close this issue here.

**Comment by t-wissmann** [comment]
I see. I can consider implementing the option to disable it altogether, but I will definitely implement the cursor change at some point.
