### ISSUE TITLE
pass-through mode

### ISSUE THREAD

**Issue by zenny** [herbstluftwm/herbstluftwm#1149]
Hi,

In `i3`, there is a `pass-through` mode that allows to execute similar commands inside the open windows:

```
mode "pass-through" {
    bindsym $mod+p mode "default"
}

bindsym $mod+p mode "pass-through"
```

Is there an equivalent to the above in `herbstluftwm`? 

Cheers,
/z

**Comment by t-wissmann** [comment]
After the additional infos in the IRC, I now get what this is about: in pass-through mode, the keybindings of the WM are inactive. Though there is no pass-through mode in hlwm, there is maybe something better: there are the client-specific attributes `keymask` and `keys_inactive`, with which you can filter out hlwm keybindings for a client. E.g. you can do:
```
hc rule class=VirtualMachine keymask=$mod-b
```
and then only `$mod-b` binding is active for the virtual machine window and all other key presses are passed directly to the window.

**Comment by t-wissmann** [comment]
(I claim this is "maybe better" because you don't need to enter/leave the pass-through mode but instead hlwm does it automatically depending on which window is focused)

**Comment by zenny** [comment]
> After the additional infos in the IRC, I now get what this is about: in pass-through mode, the keybindings of the WM are inactive. Though there is no pass-through mode in hlwm, there is maybe something better: there are the client-specific attributes `keymask` and `keys_inactive`, with which you can filter out hlwm keybindings for a client. E.g. you can do:
> 
> ```
> hc rule class=VirtualMachine keymask=$mod-b
> ```
> 
> and then only `$mod-b` binding is active for the virtual machine window and all other key presses are passed directly to the window.

@t-wissmann, thanks. However, I needed that not for the virtual machine, but for a specific window that connects to a remote server where I have to run tmux session which is configured to use the duplicate commands similar to host machine (because I use `jabirali/tmux-tilish` plugin)

With the solution above, if I

`hc rule class=St keymask=$mod-b`

All open st instances gets replaced. I want that to happen only on a single instance of the terminal which is connected to the remote machine with running tmux session.

**Comment by t-wissmann** [comment]
> All open Sakura instances and tabs gets affected, don't they? I want that to happen only on a single instance of the terminal which is connected to the remote machine with running tmux session.

There are two options to solve this:

1. Instead of `class=Sakura` you can put `instance=tmuxtilish` and start sakura with the option `--name=tmuxtilish` (see `sakura --help-gtk`). Then only this particular window is affected

2. You can have
  ```
hc keybind ${mod}+p or : and , compare clients.focus.keymask = '' , try attr clients.focus.keymask ${mod}+p : set_attr clients.focus.keymask ''
```
it will toggle the keymask of your focused window between `${mod}+p` (only `${mod}+p` is active, all other keys are passed through) and `''` (no keys are filtered out)

**Comment by zenny** [comment]
> > All open Sakura instances and tabs gets affected, don't they? I want that to happen only on a single instance of the terminal which is connected to the remote machine with running tmux session.
> 
> There are two options to solve this:
> 
>     1. Instead of `class=Sakura` you can put `instance=tmuxtilish` and start sakura with the option `--name=tmuxtilish` (see `sakura --help-gtk`). Then only this particular window is affected
> 
>     2. You can have
> 
> 
> ```
> hc keybind ${mod}+p or : and , compare clients.focus.keymask = '' , try attr clients.focus.keymask ${mod}+p : set_attr clients.focus.keymask ''
> ```
> 
> it will toggle the keymask of your focused window between `${mod}+p` (only `${mod}+p` is active, all other keys are passed through) and `''` (no keys are filtered out, all hlwm keybindings are active)

Thanks @t-wissmann for swift reply. Cheers.
