### ISSUE TITLE
_NET_DESKTOP_VIEWPORT returns wrong value

### ISSUE THREAD

**Issue by lyze237** [herbstluftwm/herbstluftwm#115]
Hello!

Running herbstluftwm 0.7.0 on Xubuntu 17.10.

[Polybar's xworkspaces module](https://github.com/jaagr/polybar/wiki/Module:-xworkspaces) can't detect viewport regions from herbstluftwm since it returns a really big number. https://github.com/jaagr/polybar/issues/1097

Therefore it displays no workspaces when you enable "workspace pinning" which should only show workspaces defined on the same output as the bar.

```
$ xprop -root _NET_DESKTOP_VIEWPORT
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 2415376896
```

**Comment by t-wissmann** [comment]
Thanks for reporting this issue! I have fixed this in commit 95aac7ce4eda8691d2c985374fee40fee336530d. Can you check this on your system?

Thanks!
