### ISSUE TITLE
License for default config file?

### ISSUE THREAD

**Issue by Valleriite** [herbstluftwm/herbstluftwm#1154]
OK this may feel weird but what is the license for the default auto start file,I have a modified version of it that I may publish and I want to be infringing anyone's copyright
have a nice day

**Comment by t-wissmann** [comment]
The entire project is in 'simplified MIT', see the LICENSE file. You're absolutely allowed to modify and publish it as you wish. So you don't need worry about copyright.

**Comment by Valleriite** [comment]
> The entire project is in 'simplified MIT', see the LICENSE file. You're absolutely allowed to modify and publish it as you wish. So you don't need worry about copyright.

Simplified BSD License you mean?
If yes,is the copyright notice I should include the one inside this repository?

**Comment by t-wissmann** [comment]
Oh sorry, yes, I mean simplified BSD License. If you leave a note that it's derived from the default autostart it is completely sufficient. But you can also just publish it. It is just the autostart and it is completely clear that is somehow related to the herbstluftwm project :-)

**Comment by Valleriite** [comment]
> Oh sorry, yes, I mean simplified BSD License. If you leave a note that it's derived from the default autostart it is completely sufficient. But you can also just publish it. It is just the autostart and it is completely clear that is somehow related to the herbstluftwm project :-)

I think I should include that license file,
not sure if I should modify said file.
