### ISSUE TITLE
Rule to focus client in its frame (but not the frame in its tag)

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#1156]
Recently it happens quite often that I want to open school materials for a lesson all at once, but I’m facing one of the following problems:

- I `hc rule class=Zathura index=1 focus=true`, but then I have to switch back to the file manager to open the next document
- I `hc rule class=Zathura index=1 focus=false`, but then the windows are in reverse order (except the first one)

The possible solutions that I’ve thought of:

- use the `hook` consequence to focus the original frame — but it changes the focus & so I could press `jl` too early → but this is not an option
- request a new consequence to focus the client only in its frame :)
- request a new consequence to specify the client’s index in the frame, with possibilities such as `-1` — seems too complicated though
- use the `hook` consequence to `lock`, switch focus to the new window, switch focus back, `unlock`

Now my question: is the request (& which one) too specific to not make sense to be implemented & should I use the hook approach instead, or does it make sense for more than this special use case? (Anyway I’ll have to use the hook&lock approach at least til the new consequence is implemented)

**Comment by tiosgz** [comment]
FWIW, this is what I’ve come up with for the 4th possible solution

```bash
hc rule class~'Zathura|imv' index=1 focus=off hook=new_material
hc -i rule new_material | while IFS=$'\t' read _ __ winid; do
  hc substitute FM clients.focus.winid chain . lock . jumpto "$winid" . jumpto FM . unlock
done
```

**Comment by tiosgz** [comment]
IDK why I didn’t close this, coz it’s resolved to a sufficient extent.

**Comment by t-wissmann** [comment]
Sorry that I didn't react (Maybe I only left a comment in the irc and then forgot it?). But it's great that the issue is solved for you!
