### ISSUE TITLE
can't use titles with spaces or parenthesis in rules

### ISSUE THREAD

**Issue by cccplex** [herbstluftwm/herbstluftwm#116]
I open mocp via a launcher and I want it to show up on tag 'listen'. 

```
j4-dmenu-desktop --term='st -f Inconsolata-g:size=15 -g 80x24' --display-binary --dmenu='dmenu -i -l 20 -fn -sony-*-*-*-*-*-24-*-*-*-*-*-*-*'"
```
```
$ herbstclient sprintf STR title=%s clients.0xa00005.title   echo STR
title=Music on Console (mocp)
```

Because i open more terminal programs I can't just use the class in rule and also add the title

I tried the following in autostart:

```
hc rule class=st-256color title='Music on Console (mocp)' tag='listen' index=0 switchtag=on focus=on
hc rule class=st-256color title~'Music\son\sConsole\s\(mocp\)' tag='listen' index=0 switchtag=on focus=on
```
If I open mocp with `st -f Inconsolata-g:size=15 -g 80x24 -e mocp` and use the following rule it will work.
`hc rule class=st-256color title='mocp' tag='listen' index=0 switchtag=on focus=on`
```
$ herbstclient sprintf STR title=%s clients.0x2200005.title  echo STR
title=mocp
```

So does it have to do with the spaces or parenthesis?

**Comment by t-wissmann** [comment]
The hlwm rules are applied when a window shows up for the first time. However, the title `Music on Console (mocp)` is set by the application running within the terminal, and that is after the terminal window is created. This is why your rule is not applied. You can check this by starting st with the flag `-e Music on Console (mocp)` and your original rule. This is also a proper solution, in my opinion.
