### ISSUE TITLE
Wrong stacking order between fullscreen and tiled clients

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#1165]
@The-Compiler reported a bug via IRC, but I'm not sure whether it is still an issue:

> something I've been wondering for a while if it's a bug: If there's a fullscreened and a tiled client on monitor 1 and e.g. nothing on monitor 2, switching monitors will always raise the tiled window. i.e. I think switching back to monitor one focuses the tiled window (rather than the fullscreened one) and so it gets raised above the fullscreened. definitly bit me with presentations and such (where I usually have a second window behind the presentation for demos)

I can't reproduce it at the moment (neither in the git version, nor in v0.9.1 which didn't include #1144 )

**Comment by blarz** [comment]
So this might be fixed with #1167, right?

**Comment by t-wissmann** [comment]
I first thought this is an enitrely different issue, but maybe it is really the same: if the tiled window was accidentally focused before leaving the monitor, then the tiled window was hidden (though focused) and (surprisingly) raised&focused again when switching back to the monitor.

**Comment by The-Compiler** [comment]
I haven't seen this happening anymore after upgrading. Will reopen in case I see it again, but I think this is indeed fixed.
