### ISSUE TITLE
[REQUEST] Create a new atom to detect whether window is floating

### ISSUE THREAD

**Issue by Barbarossa93** [herbstluftwm/herbstluftwm#1172]
I'd like to request an atom for herbstluftwm to report whether a window is floating or not, similar to i3's `I3_FLOATING_WINDOW`. This would allow specifying a picom rule to exclude shadows, fade, blur, etc for either floating or non-floating windows

**Comment by t-wissmann** [comment]
I've implemented it in PR #1325.

**Comment by Barbarossa93** [comment]
You're awesome! Thank you for doing that!
