### ISSUE TITLE
allow to increase (or decrease) int attributes

### ISSUE THREAD

**Issue by apm256** [herbstluftwm/herbstluftwm#1174]
It may be useful to allow increasing/decreasing int attributes.

# Pros:

* I've found two use cases:
    1. [increment a counter](https://github.com/herbstluftwm/herbstluftwm/pull/1140#issuecomment-779226542)
    2. [increment a setting](https://github.com/herbstluftwm/herbstluftwm/issues/42#issue-69303315)
* such a "read then write" feature already exists for booleans (i.e. `toggle`), so it seems natural to allow similar feature for `int`
* as we can use calls like `use_index +1` it would make sense to allow calls like `set_attr tags.focus.index +1`

# Cons:

* perhaps two use cases are not enough?
* perhaps the goal is not to make `herbstclient` turing-complete :-)

**Comment by t-wissmann** [comment]
I think it's reasonable to implement it because it is a very local change to the sourcecode ('local' in contrast to complex change).
Since `+1` should be the same as `1` (and `-1` already means "minus one" and not "decrease by 1"), the syntax should be `+=1` and `-=1` (or in general `+=N`/`-=N` for (possibly signed) integers `N`)

**Comment by apm256** [comment]
> the syntax should be `+=1` and `-=1` (or in general `+=N`/`-=N` for (possibly signed) integers `N`)

or maybe `inc N` and `dec N`, to be more similar to the `toggle` command, or the future `cycle_layout` command mentioned in #1203?

**Comment by t-wissmann** [comment]
> > the syntax should be `+=1` and `-=1` (or in general `+=N`/`-=N` for (possibly signed) integers `N`)
> 
> or maybe `inc N` and `dec N`, to be more similar to the `toggle` command, or the future `cycle_layout` command mentioned in #1203?

Ah, I wasn't talking about new commands but I meant "relative values", i.e.:
```
hc attr settings.border_width +=2
```

> as we can use calls like `use_index +1` it would make sense to allow calls like `set_attr tags.focus.index +1`

By the way, these two commands should not be equivalent in my understanding. `use_index +1` focuses the next tag, but `set_attr tags.focus.index +1` should increase the index of the focused tag, that means, swap it with the tag right to it.

**Comment by apm256** [comment]
> > > the syntax should be `+=1` and `-=1` (or in general `+=N`/`-=N` for (possibly signed) integers `N`)
> > 
> > 
> > or maybe `inc N` and `dec N`, to be more similar to the `toggle` command, or the future `cycle_layout` command mentioned in #1203?
> 
> Ah, I wasn't talking about new commands but I meant "relative values", i.e.:
> 
> ```
> hc attr settings.border_width +=2
> ```

I was thinking of something like:

```
hc attr settings.border_width inc 2
```

by analogy with:

```
hc attr clients.focus.minimized toggle
```

...but it is only a detail!

> 
> > as we can use calls like `use_index +1` it would make sense to allow calls like `set_attr tags.focus.index +1`
> 
> By the way, these two commands should not be equivalent in my understanding. `use_index +1` focuses the next tag, but `set_attr tags.focus.index +1` should increase the index of the focused tag, that means, swap it with the tag right to it.

Yes, you're perfectly right!

**Comment by t-wissmann** [comment]
> I was thinking of something like:
> 
> ```
> hc attr settings.border_width inc 2
> ```
> 
> by analogy with:
> 
> ```
> hc attr clients.focus.minimized toggle
> ```
> 
> ...but it is only a detail!

This would mean that `inc` and `2` are separate tokens. (`toggle` and `+=2` are
only one token!), so this syntax would either require to change the interface
of the `attr` command (and any other command dealing with attributes) or it would
require quotes
```
hc attr settings.border_width "inc 2"
```

**Comment by apm256** [comment]
Ok. Thanks for the explanations.

**Comment by apm256** [comment]
Thank you for this feature! :tada:
