### ISSUE TITLE
herbstclient reload does not fully execute autostart

### ISSUE THREAD

**Issue by Naught0** [herbstluftwm/herbstluftwm#119]
### Behavior
I have `hc keybind $Mod-Shift-r reload` defined in my autostart file. 

When I press that keybind, window gaps/borders are refreshed as expected, however the end of my autostart which restarts the panel does not seem to be executed. Normally I'd think I messed something up along the way, however when running `./autostart`, everything works as expected. Here is that panel start for reference:
```sh
if ! pgrep -P $(<panel/panel.pid) > /dev/null; then
    bash panel/panel.sh & 
else
    pkill -P $(<panel/panel.pid)
    bash panel/panel.sh & 
fi
```

### What I think is the issue
Running `zsh autostart` (my default shell) yields `autostart:84: bad substitution`, which leads me to believe that herbstluftwm is perhaps using the user's default shell to execute the autostart file and exits early somehow despite the proper shebang `#!/bin/env bash`. 
For reference here's the code that doesn't seem to work in zsh (it's default):
```sh
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do    # LINE 84
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
```
Is this a bug or am I missing something obvious here?

**Comment by ypnos** [comment]
Well I am not so sure about your assumption, as my autostart is a perl script and it is executed properly.

**Comment by Naught0** [comment]
That's probably fair, and I'm obviously a novice when it comes to all this stuff! I'm not sure why else it would work when run from terminal yet not via `hc reload`

**Comment by ypnos** [comment]
You are calling another shell script with relative path, maybe the working directory is not what you assume?

**Comment by t-wissmann** [comment]
I think it will work properly if you make your shell explicit in the shebang. (You should always provide a meaningful shebang in shell scripts). Another issue here, are the lines
```
bash panel/panel.sh & 
```
The path `panel/panel.sh` is relative, so it is treated relative to the current working directory, which is usually home, and not ~/.conf/herbstluftwm/autostart, so please provide an absolute path there `~/.config/herbstluftwm/panel/panel.sh`.

**Comment by Naught0** [comment]
Oh my god that's got to be it. I normally would put `cd "${0%/*}"` at the start of my scripts to get the cwd right. Testing again with proper paths
