### ISSUE TITLE
HLWM conflicts with REAPER's floating dialogue windows

### ISSUE THREAD

**Issue by theotrst** [herbstluftwm/herbstluftwm#1235]
Hey, 
I got some problems (i.e. system crashes and I have to restart manually) when I start REAPER (Audio Editor, www.reaper.fm/) when I open any REAPER's dialog floating windows. I don't know why only with this program I have this issue (maybe someone has found a solution for this). But I can solve this by setting a rule. I know it is possible to create a rule to selectively disable floating dialogs windows by default. 

Should I add somthing like

> hc disable attr clients.focus.floating toggle

but how to make this rule only for a single program?

many thanks,
R

**Comment by t-wissmann** [comment]
> I got some problems (i.e. system crashes and I have to restart manually) when I start REAPER (Audio Editor, [www.reaper.fm/](http://www.reaper.fm/)) when I open any REAPER's dialog floating windows. I don't know why only with this program I have this issue (maybe someone has found a solution for this).

Does herbstluftwm crash? What version are you using? (Output of `herbstclient version` or `herbstluftwm --version`). Can you run the following and reproduce the crash in Xephyr? (Ctrl+Shift grabs mouse & keyboard)
```
Xephyr -resizeable :13 & sleep 2; DISPLAY=:13 herbstluftwm --verbose
```

> But I can solve this by setting a rule. I know it is possible to create a rule to selectively disable floating dialogs windows by default.
> 
> Should I add somthing like
> 
> > hc disable attr clients.focus.floating toggle
> 
> but how to make this rule only for a single program?

First you need to find out the window class of reaper. you can do this by running
```
xprop | grep 'WM_CLASS'
```
and then click on the reaper window. The window class is the *second* entry of WM_CLASS. If it is for example `Reaper` you can add the rule:
```
hc rule class=Reaper floating=false
```
This disables the floating-setting for the reaper window. However, I doubt that this will solve any crashes.

**Comment by theotrst** [comment]
Thank you for your answer.
I run the 0.8.3 version

I tried to run REAPER within Xephyr: I opened Reaper, and try to open a dialog windows (usually I try ABOUT). I try to make a photo of Xephyr's report:

> 
> ~\ >>> hc version
> herbstluftwm 0.8.3
> Copyright (c) 2011-2014 Thorsten Wißmann
> Released under the Simplified BSD License
> xrandr support: on
> xinerama support: on
> ~\ >>> Xephyr -resizeable :13 & sleep 2; DISPLAY=:13 herbstluftwm --verbose
> [1] 11192
> EWMH: 0 desktops:
> 0 managed clients: 
> pad: Monitor "1" not found!
> notice: Parsing config file: /home/rdw/.config/polybar/config.ini
> warn: No monitor specified, using "default"
> warn: The config parameter 'settings.throttle-input-for' is deprecated, it will be removed in the future. Please remove it from your config
> error: Disabling module "network" (reason: basic_string::_M_construct null not valid)
> notice: Loaded font "Ubuntu Condensed:size=11" (name=Ubuntu Condensed, offset=3, file=/usr/share/fonts/truetype/ubuntu/Ubuntu-C.ttf)
> notice: Loaded font "FontAwesome:size=11" (name=FontAwesome, offset=4, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0x400001
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 459: name is: MapRequest for 0x400001
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0x400001
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0x400001 to apply rules
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 364: name is: EnterNotify, focus = 0, window = 0x51f
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 459: name is: MapRequest for 0xa00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 459: name is: MapRequest for 0xa00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00119
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00119
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for 200057
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 204: name is: ButtonPress on sub 0x0, win 0xa00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa003e5 to apply rules
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a003e5
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a003e5
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00119
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a003e5
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa00428 to apply rules
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00428
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00119
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a00428
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa0045c to apply rules
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a0045c
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00119
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a0045c
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa00476 to apply rules
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00476
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa004aa to apply rules
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a004aa
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00476
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a004aa
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00119
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00119
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a00476
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00544
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 459: name is: MapRequest for 0xa00544
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00544
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00544
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00544
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00544
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 204: name is: ButtonPress on sub 0x0, win 0xa00544
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00544
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 204: name is: ButtonPress on sub 0x0, win 0xa00544
> 

![IMG_20210312_222039](https://user-images.githubusercontent.com/77860783/111005063-0652aa00-8382-11eb-906e-7c7f38130311.jpg)

I would like to understand why this is happening and try to solve this issue. Otherwise, I will try to set a rule to use not-floating windows...

thank you for any help you may provide...
cheers

**Comment by t-wissmann** [comment]
Thanks for the additional information! So you started Reaper in the Xephyr session, and it didn't crash there -- am I right? So far I can't see anything bad happening. Can you take a screenshot of the Xephyr window (e.g. using the `scrot` command) and post it here?

**Comment by theotrst** [comment]
Also through Xephyr, when I start opening any dialog window Reaper doesn't respond (or sometimes is very slow). Not sure to have understood how to take a screenshot with "scrot"... I tried a second time and I open "Preferences"-windows... Reaper turns very slow, every command takes 40 seconds to act...and it seems now I have a more interesting report:

> 
> ~\ >>> Xephyr -resizeable :13 & sleep 2; DISPLAY=:13 herbstluftwm --verbose
> [1] 2032
> EWMH: 0 desktops:
> 0 managed clients: 
> pad: Monitor "1" not found!
> notice: Parsing config file: /home/rdw/.config/polybar/config.ini
> warn: No monitor specified, using "default"
> warn: The config parameter 'settings.throttle-input-for' is deprecated, it will be removed in the future. Please remove it from your config
> error: Disabling module "network" (reason: basic_string::_M_construct null not valid)
> notice: Loaded font "Ubuntu Condensed:size=11" (name=Ubuntu Condensed, offset=3, file=/usr/share/fonts/truetype/ubuntu/Ubuntu-C.ttf)
> notice: Loaded font "FontAwesome:size=11" (name=FontAwesome, offset=4, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0x400001
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 459: name is: MapRequest for 0x400001
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0x400001
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0x400001 to apply rules
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 204: name is: ButtonPress on sub 0x0, win 0x51f
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 459: name is: MapRequest for 0xa00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00116
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 459: name is: MapRequest for 0xa00116
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00116
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00116
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00116
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00003
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00116
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00116
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a00003
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for 200057
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 204: name is: ButtonPress on sub 0x0, win 0xa00116
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa00439 to apply rules
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00439
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00439
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00116
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00116
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a00439
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa004a3 to apply rules
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a004a3
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa00528 to apply rules
> herbstluftwm: fatal error
>    resource id: 0xa00528
>    request code: 14 "X_GetGeometry" (minor code: 0)
>    error code: 9 "BadDrawable (invalid Pixmap or Window parameter)"
>    serial number: 305920
> /home/rdw/herbstluftwm/src/xconnection.cpp: 99: Warning: ignoring X_BadDrawable
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00528
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a004a3
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a00528
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa0053e to apply rules
> herbstluftwm: fatal error
>    resource id: 0xa0053e
>    request code: 14 "X_GetGeometry" (minor code: 0)
>    error code: 9 "BadDrawable (invalid Pixmap or Window parameter)"
>    serial number: 307830
> /home/rdw/herbstluftwm/src/xconnection.cpp: 99: Warning: ignoring X_BadDrawable
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a0053e
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a004a3
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a0053e
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa0054e to apply rules
> herbstluftwm: fatal error
>    resource id: 0xa0054e
>    request code: 14 "X_GetGeometry" (minor code: 0)
>    error code: 9 "BadDrawable (invalid Pixmap or Window parameter)"
>    serial number: 308942
> /home/rdw/herbstluftwm/src/xconnection.cpp: 99: Warning: ignoring X_BadDrawable
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a0054e
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a004a3
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a0054e
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa00576 to apply rules
> herbstluftwm: fatal error
>    resource id: 0xa00576
>    request code: 14 "X_GetGeometry" (minor code: 0)
>    error code: 9 "BadDrawable (invalid Pixmap or Window parameter)"
>    serial number: 317803
> /home/rdw/herbstluftwm/src/xconnection.cpp: 99: Warning: ignoring X_BadDrawable
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00576
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a004a3
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a00576
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 453: MapNotify: briefly managing 0xa00586 to apply rules
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00586
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a004a3
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a00586
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00116
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00116
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 541: name is: UnmapNotify for a004a3
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00734
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 459: name is: MapRequest for 0xa00734
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00734
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 248: name is: ConfigureRequest for 0xa00734
> /home/rdw/herbstluftwm/src/ewmh.cpp: 272: Received event: ClientMessage: "_NET_ACTIVE_WINDOW" for a00734
> /home/rdw/herbstluftwm/src/xmainloop.cpp: 204: name is: ButtonPress on sub 0x0, win 0xa00734
> 
>

**Comment by theotrst** [comment]
the reason why I assume is a HLWM's issue is that when I start a session without HLWM (only Kdeplasma), REAPER works perfectly.

**Comment by t-wissmann** [comment]
It's HLWM's issue for sure and I can reproduce it here. I don't know when I have time to look at it, but as a workaround, you can start another window manager (e.g. fluxbox or openbox) in the Xephyr session and use reaper there, until the issue in hlwm is fixed:
```bash
Xephyr -resizeable :13 & sleep 2; DISPLAY=:13 openbox & DISPLAY=:13 reaper
```

**Comment by t-wissmann** [comment]
I've come up with a fix, it is the patch in the pull request #1236. Do know how to build hlwm from source? It is described in the `HACKING` file. Essentially, you need to install the dependencies (if not already existing on your machine), edit the source (or checkout the branch `dont-fear-the-reaper`) and then you can run:
```
mkdir build ; cd build ; cmake .. ; make
```
from the git repository.

**Comment by theotrst** [comment]
hey,
thank you Thorsten. Cool! So let me understand. Not really sure to which patch you refer. Do you mean, I just have to uninstall HLWM and build it again (with the new patch included) from the git repository?

thnx
Riccardo

**Comment by t-wissmann** [comment]
There's no need to uninstall anything. you can build *either* with the patch https://github.com/herbstluftwm/herbstluftwm/pull/1236/files *or* take the branch `dont-fear-the-reaper`. Then, you can replace the herbstluftwm binary in your $PATH with the freshly built one.

**Comment by tiosgz** [comment]
```sh
git clone https://github.com/herbstluftwm/herbstluftwm.git -b dont-fear-the-reaper --depth 1 && cd herbstluftwm
mkdir build && cd build && cmake .. && make
hc wmexec "$PWD/herbstluftwm"
```

If it’s working, you can then move this binary to `/usr/bin/herbstluftwm` (or where the original binary is)

**Comment by theotrst** [comment]
wow. wonderful! yes, Reaper is working fine! thank you @t-wissmann and @tiosgz 
just two questions

what do you really mean with:

> you can then move this binary to /usr/bin/herbstluftwm (or where the original binary is)

should I close the issue, now?

:)
thanx
R

**Comment by tiosgz** [comment]
> what do you really mean with:
> 
> > you can then move this binary to /usr/bin/herbstluftwm (or where the original binary is)

Assuming that you are still in the `build/` directory, `sudo mv ./herbstluftwm "$(which herbstluftwm)"`

**Comment by theotrst** [comment]
hey,
I am sorry, but I had the feeling there is still something wrong on going. First try, Reaper was fast (as without HLWM), then I try to work on it and I realized some processes got slower, until it started to act similarly as before. I try to run it again in Xephyr and WITHIN Xephyr seems fine! (it is still open in Xephyr session and continues great). 

Actually, I dont know what is going on here.

**Comment by t-wissmann** [comment]
Does it help if you delete the call to `m->applyLayout()` in line 311 in xmainloop.cpp?
```c++
            client->float_size_ = newRect;
            Monitor* m = find_monitor_with_tag(client->tag());
            if (m) {
                m->applyLayout(); // line 311.
            }
```

**Comment by theotrst** [comment]
I tried it. It seems the same. (in Xephyr, Reaper is actually perfect).

**Comment by tiosgz** [comment]
Given https://github.com/herbstluftwm/herbstluftwm/pull/1240#issuecomment-804960340
> I tested Reaper now (building the git-version)... it seems this fixes the problem!!!

can this be closed?

**Comment by theotrst** [comment]
yes, I guess so. I had time to test Reaper in different projects, with four external windows... Everything seems fine!

**Comment by theotrst** [comment]
unfortunately, I have to say that the problem reappears. I tested Reaper 1-2 days then again the program started to be slower. I solved re-building the git-version but afterwhile the problem occurred. Is there a way to restore the initial configuration  without re-building a brand new version? thanks.

**Comment by t-wissmann** [comment]
I don't know what you mean by "restore the initial configuration". Do you just mean restarting hlwm? You could do something like:
```
herbstclient keybind Mod4-Control-q wmexec
```
which restarts hlwm. Is this what you are asking for?

**Comment by theotrst** [comment]
thanks for the answer. Actually, I tried to reload/quit hlwm but the situation does not change. It is a bit weird that the only way to solve the problem (temporarily because it comes back afterwhile) is to build the git-version.

moreover, if I run Reaper within Xephyr is (always) fine.

I am sorry that I opened again the issue. It is just because, I do not understand the behaviour of this bug: it seems solved, then appears again... and apparently I can only solve it by building the wm from git.

**Comment by tiosgz** [comment]
Can you check that you *really* use the git version? After the issue reappears (*reaper – reappear*, haha), run `herbstclient version` in the terminal.

**Comment by t-wissmann** [comment]
Sorry for the trouble! Recompiling the WM has definitely no effect. But maybe hard-resetting helps ('reload' only loads the autostart)

**Comment by theotrst** [comment]
It is me that I say sorry for this... (I am not really keen on these issues and no time to follow all your advices... ) Thank you...

~\ >>> hc version
herbstluftwm 0.8.3

**Comment by t-wissmann** [comment]
> It is me that I say sorry for this... (I am not really keen on these issues and no time to follow all your advices... ) Thank you...
> 
> ~\ >>> hc version
> herbstluftwm 0.8.3

Oh, this is indeed an old version! Did you really replace the old hlwm binary as @tiosgz suggested?
```
sudo install ./herbstluftwm "$(which herbstluftwm)"
```
What distro are you on?

**Comment by theotrst** [comment]
oh, this is strange. ok. Let's make this clear. I am with an Ubuntu(Studio) 20.10 with KDE plama and in order to update HLWM I have done the following

> git clone https://github.com/herbstluftwm/herbstluftwm.git --depth 1 && cd herbstluftwm
> mkdir build && cd build && cmake .. && make
> herbstclient wmexec "$PWD/herbstluftwm"

then in the build/ directory, 

> sudo install ./herbstluftwm "$(which herbstluftwm)"

**Comment by theotrst** [comment]
ok, now I have 0.9.1, I will test Reaper for a couple of days and let you know. Thanks.

**Comment by t-wissmann** [comment]
0.9.1 is not enough (not even 0.9.2), you need the git version.

**Comment by theotrst** [comment]
is there something wrong in my installation procedure? (I actually build from the git version, but it seems there is still something from the previous version there...)

**Comment by theotrst** [comment]
I remove previous ~/herbstluftwm folder then

> git clone https://github.com/herbstluftwm/herbstluftwm
> cd herbstluftwm
> mkdir build && cd build && cmake .. && make
> herbstclient wmexec "$PWD/herbstluftwm"
> sudo install ./herbstluftwm "$(which herbstluftwm)"

**Comment by t-wissmann** [comment]
the wmexec before the `install` is odd, but it does not harm. So what's the output of `herbstclient version` after doing this and what's the output of `herbstclient version` after rebooting?

**Comment by theotrst** [comment]
oh, this is really weird

I rebuild the git I got:

> herbstclient version
> herbstluftwm 0.9.2 (73f50c26 built on 2021-03-26)
> Copyright (c) 2011-2021 Thorsten Wißmann
> Released under the Simplified BSD License
> xrandr support: on
> xinerama support: on

then I reboot, and I got:

> herbstclient version
> herbstluftwm 0.8.3
> Copyright (c) 2011-2014 Thorsten Wißmann
> Released under the Simplified BSD License
> xrandr support: on
> xinerama support: on
>

**Comment by theotrst** [comment]
and then if I type

> hc --version

I get

> herbstclient 0.9.1 (da16e111 built on 2021-01-17)

**Comment by t-wissmann** [comment]
`herbstclient --version` does not matter. Are you sure your correctly running this?
```
sudo install ./herbstluftwm "$(which herbstluftwm)"
```
It must be *herbstluftwm* (and not herbst*client*). Also, if you re-login anyways, you don't need the wmexec. (the `wmexec` replaces the running process). What's the output of
```
which herbstluftwm
herbstluftwm --version
```

**Comment by t-wissmann** [comment]
Also, whenever you re-install hlwm via the package manager, it will replace the herbstluftwm binary, so you should not do this until 0.9.3 is in ubuntu

**Comment by theotrst** [comment]
Actually

> sudo install ./herbstluftwm "$(which herbstluftwm)"

gives

> install: directory './herbstluftwm' omessa

that means "omitted"

> ~\ >>> which herbstluftwm
> /usr/local/bin/herbstluftwm
> ~\ >>> herbstluftwm --version
> herbstluftwm 0.9.2 (73f50c26 built on 2021-03-26)

**Comment by t-wissmann** [comment]
Oh. How, I'm confused. "omitted" isn't good and actually `./herbstluftwm` shouldn't be a directory, but the output of `herbstluftwm --version` seems ok. Anyway, just ensure that you properly install the freshly built herbstluftwm binary to all the places where herbstluftwm binaries were..

(Maybe there is another one in /usr/bin/herbstluftwm)

**Comment by tiosgz** [comment]
(Just thinking aloud) It’d be good to know also what the desktop file launches (or maybe plasma? I’m not sure how to understand ‘Ubuntu(Studio) 20.10 with KDE plama’)

**Comment by theotrst** [comment]
Ok, I will try to solve this out. 

FYI:This is the Xsession configuration for my Plasma+hlwm

> 
> [Desktop Entry]
> Type=XSession
> Exec=env KDEWM=/usr/bin/herbstluftwm /usr/bin/startplasma-x11
> DesktopNames=KDE
> Name=Plasma + Herbstluftwm
> Comment=Plasma w/HLWM by RP

**Comment by t-wissmann** [comment]
Ah, this explains it! Yes, you also have to overwrite `/usr/bin/herbstluftwm`

**Comment by theotrst** [comment]
ok. Done.

> ~/herbstluftwm/build\ >>> herbstclient version
> herbstluftwm 0.9.2 (73f50c26 built on 2021-03-26)
> ~/herbstluftwm/build\ >>> herbstclient --version
> herbstclient 0.9.1 (da16e111 built on 2021-01-17)
> ~/herbstluftwm/build\ >>> herbstluftwm --version
> herbstluftwm 0.9.2 (73f50c26 built on 2021-03-26)

I guess Reaper's problem is now solved, but I will test it for a couple of days and close the issue.

thanks

**Comment by t-wissmann** [comment]
Great!

**Comment by theotrst** [comment]
Reaper tested for 3 days in different configurations. No problem. Issue solved! thnx
