### ISSUE TITLE
Bugged position of menus in Qt apps

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#1239]
This seems to be new with #1236.

Qt apps use an outdated menu position if the window is floating. Example:

- set tag to floating
- open VLC
- open a menu to check that it’s placed correctly; close the menu
- move the window
- check the menu again – it’s misplaced
- set tag to tiling
- check the menu again – it’s okay
- split the tag & move the window to the other frame
- the menu is still okay

**Comment by blarz** [comment]
I can confirm. The menu is still at the old position after moving the floating VLC window.

**Comment by blarz** [comment]
Resizing the window however fixes the menu position again.

**Comment by blarz** [comment]
And it really was introduced with #1236 as @tiosgz said. I reverted to HEAD~2 and this doesn't happen.
(not sure how to fix it though)

**Comment by t-wissmann** [comment]
I have it on my radar and will look at it on the weekend.
