### ISSUE TITLE
[Question] Styling panes with more than 1 client

### ISSUE THREAD

**Issue by gomezhyuuga** [herbstluftwm/herbstluftwm#1280]
Is there any recommended way to style the window title or the panel border color if the current pane contains more than 1 client/windows? e.g using the `max` layout with multiple windows on a single pane.

My question originates from a feature I used a lot in i3, the stacked windows:
![image](https://user-images.githubusercontent.com/1633839/114322422-7474c300-9b20-11eb-992e-f78e6ecc1bf0.png)

In i3 I have clearly a visual indicator that the panel contains multiple windows, but with the `max` layout I don't know and I have to cycle through layouts constantly to check if there is more than one window maximized.

Possible workarounds I was trying:

- Styling the frame border to a different color as an indicator
- Using a script that "watches" over the current focused pane, and if it has a `max` layout then showing in Polybar all the windows inside it

But haven't got any success with any of those.

Any support would be really appreciated, thanks in advance!

**Comment by t-wissmann** [comment]
Having tab-styled decorations in the max layout is a definitely planned feature. But so far, I did not have time to implement it. (It is also one of the main feature requests in the window decoration thread #1097)

**Comment by gomezhyuuga** [comment]
Cool, thanks a lot for the reference @t-wissmann I'll keep watching that thread then :)
