### ISSUE TITLE
Transparent border/title when using picom

### ISSUE THREAD

**Issue by mserajnik** [herbstluftwm/herbstluftwm#1281]
I'm using herbstluftwm in combination with [picom](https://wiki.archlinux.org/index.php/Picom) on Arch. Both installed from the official Arch repos.

When setting transparency for a window it also makes the borders and the title transparent. Here's an example:

__Focused:__
![image](https://user-images.githubusercontent.com/80664890/114607881-597b8d80-9c9d-11eb-9042-0bf2098fc0c8.png)

__Unfocused:__
![image](https://user-images.githubusercontent.com/80664890/114606910-2c7aab00-9c9c-11eb-8dd1-a3814b39d4b2.png)

Here's what the title/border should look like fully opaque:
![image](https://user-images.githubusercontent.com/80664890/114607787-3a7cfb80-9c9d-11eb-84a0-af34b9c1bb8a.png)

In this case, it's [kitty](https://github.com/kovidgoyal/kitty) and the transparency is set via its `background_opacity` setting (which picom respects). But I can reproduce this with other programs too (e.g., Konsole).

Interestingly, the opacity of the border/title seems to stay the same, regardless what value I set for `background_opacity` (unless I set it to `1`, of course, which makes it opaque; in the example it's `0.75`). But `background_opacity` still does correctly modify the window opacity itself.

I've tried setting `frame-opacity = 1.0` in picom, but that didn't fix the issue.

What is more, I've set `inactive-opacity = 1` in picom, so it's also a bit weird that the border/title looks different when focused/unfocused.

From what I can see, people had a similar issue with dwm (see [here](https://www.reddit.com/r/suckless/comments/gg60lo/transparent_borders_on_dwm_when_using_picom/)) and they are talking about using an "alpha patch".

And there's at least one other user who's apparently experiencing the same issue as me, see [here](https://www.reddit.com/r/herbstluftwm/comments/mii55a/problem_with_transparent_window_bars/).

**Comment by Barbarossa93** [comment]
Try the latest herbstluftwm-git on the AUR. This should be fixed with https://github.com/herbstluftwm/herbstluftwm/commit/696afd4f1e4bc7860e4478820f6c69bb06220c76, although it seems there are possibly some other related problems (see https://github.com/herbstluftwm/herbstluftwm/issues/1267).

**Comment by mserajnik** [comment]
Thanks, I'll give that a try.

Sorry, I missed https://github.com/herbstluftwm/herbstluftwm/issues/1173, I wouldn't have opened a new issue otherwise. I did use the search function but somehow forgot to check closed issues.

**Comment by Barbarossa93** [comment]
No worries! Hope that fixes it for you :)

**Comment by mserajnik** [comment]
I can confirm using herbstluftwm-git from the AUR fixes the issue:

__Focused:__
![image](https://user-images.githubusercontent.com/80664890/114611577-7c0fa580-9ca1-11eb-86a2-4be2260ec646.png)

__Unfocused:__
![image](https://user-images.githubusercontent.com/80664890/114611603-816cf000-9ca1-11eb-83e4-11629d960da4.png)

I'll let you know in case I experience any issues as described in https://github.com/herbstluftwm/herbstluftwm/issues/1267.

Thanks for the quick response! :)
