### ISSUE TITLE
dzen: error, cannot allocate color '#101010cc'

### ISSUE THREAD

**Issue by sje30** [herbstluftwm/herbstluftwm#1282]
Hi,
just getting started with hlwm (thank you for it).
I've installed the -git version from arch, and have the autostart copied and working okay.  I cannot get the panel to work though.  on my laptop with no external monitor:

```
% sh .config/herbstluftwm/panel.sh 0
dzen: error, cannot allocate color '#101010cc'
% 
```

any ideas how to start?  I've not changed any color configs so I think that color is 

```
% hc get frame_border_normal_color 
#101010cc
```

**Comment by t-wissmann** [comment]
Hi, thanks for givin hlwm a try!

this is indeed a mistake in the panel.sh. I've implemented transparency support in the colors recently (and `cc` is the alpha/transparency-value here). I've opend a pull-request to fix this. If you want to fix it locally, you can replace the definitions of `bgcolor` and `selbg` in your panel.sh with
```bash
bgcolor=$(hc get frame_border_normal_color|sed 's,^\(\#[0-9a-f]\{6\}\)[0-9a-f]\{2\}$,\1,')
selbg=$(hc get window_border_active_color|sed 's,^\(\#[0-9a-f]\{6\}\)[0-9a-f]\{2\}$,\1,')
```

**Comment by sje30** [comment]
wow. and with that simple edit, and a simple refresh, the dzen2 panel appears. thank you.
