### ISSUE TITLE
[bug] Mixed Title Drawings

### ISSUE THREAD

**Issue by duclos-cavalcanti** [herbstluftwm/herbstluftwm#1297]
From the video shown below, it can be seen that my document viewer (Zathura) apparently is drawing a grey border on top of the window's title. I tried to illustrate in the video other windows that are also not being focused to show that the theme.normal.color is not grey (actually a dark blue) and that was being "overdrawn" by the application apparently. When I then focus on Zathura one can see the overlapping of that grey color with my theme.active.color (blue), producing a aqua like mixed color. Also it is somewhat able to be seen that the title font seems blurred as if both the title from Zathura and herbstluft's title are being drawn together.

Ive been looking around for a way to maybe suppress the title drawing for specific applications, instead of just either having titles or not. Something I could place as a rule in autostart, but had no luck finding such a solution or a similar one. Meaning, have titles drawn 'on', but for specific applications maybe matched through a rule ask that no title is drawn.

Is there such a workaround that I may be overlooking?

[Here](https://github.com/duclos-cavalcanti/dotfiles/blob/main/wms/herbstluftwm/autostart) is my autostart if that is in fact needed.

https://user-images.githubusercontent.com/62443350/116317248-62974f00-a7b3-11eb-9af5-bb61307afbd3.mp4

There is also a zoomed in image of the unfocused border title, where one can notice that the unknown grey border seems to be partially drawn/integrated into herbstluft's title border.

![2021-04-27-235813_134x39_scrot](https://user-images.githubusercontent.com/62443350/116318139-93c44f00-a7b4-11eb-804b-636a53d36f81.png)

**Comment by t-wissmann** [comment]
This is the bug https://github.com/herbstluftwm/herbstluftwm/issues/1173 which has been fixed in the current git version of hlwm. Do you have a chance to install it on your system?
Anyway, thanks for the clear bug report. The effort you put in it is still much appreciated :)

**Comment by duclos-cavalcanti** [comment]
Ahh, I haven't seen the bug report. I could install the git version from the AUR but I think I'll stay on the current stable release on Arch's community repo. It's not that much of an issue for me, my intent was to hopefully show a bug that would be of interest to the devs/community and maybe see if there would be a possible workaround. Thank you anyways for the helpful reply and referral to the current solution. :)
