### ISSUE TITLE
Show stacked window titles

### ISSUE THREAD

**Issue by Nairou** [herbstluftwm/herbstluftwm#1299]
This idea comes from older tiled WMs like Ion and PWM. In those, when you had multiple windows stacked in the same frame, the space for the window title was segmented to display the title of each stacked window.

[Ion example](https://tuomov.iki.fi/software/ion/ion3-1.png)
[PWM example](https://tuomov.iki.fi/software/ion/pwm-3.jpg)
[Haiku OS example](https://www.haiku-os.org/docs/userguide/en/images/gui-images/gui-s+t.gif)

With herbstluftwm, you only see the top window's title, so there is no indication that there are other windows behind it. I often end up hitting the keybinding to cycle windows in a frame just to see if I left one back there.

**Comment by blarz** [comment]
I'd also like to see this. It is also part of a more general discussion in #1097, you might want to take a look into that issue, too.

**Comment by t-wissmann** [comment]
This is implemented in PR #1381, and will soon be merged to the master branch.

![hlwm-tabs](https://user-images.githubusercontent.com/9048813/142879398-82e3b117-9a61-406d-8f05-ab129b76eaa8.gif)
