### ISSUE TITLE
Setting min width and height for frames

### ISSUE THREAD

**Issue by cakir-enes** [herbstluftwm/herbstluftwm#1301]
`hc resize <dir> <delta>` stops resizing frame at some min value that user doesn't control. 
Is there any way to either changing min values, or setting frame sizes manually?

**Comment by t-wissmann** [comment]
Sorry for not reacting earlier: no it is not possible to change the minimum frame size. The minimum size is currently set to 10% of the parent frame. If you needs something smaller, then this indicates that you need something different like a panel that should not be handled by the tiling at all.
