### ISSUE TITLE
Window border thicker on sides for floating window with floating_geometry rule or other specific pixel size method

### ISSUE THREAD

**Issue by Barbarossa93** [herbstluftwm/herbstluftwm#1322]
I've noticed that if I spawn a floating window with a specific pixel size either with the floating_geometry rule or through xdotool, the window will have one side of it's border be incorrect i.e. thicker than what it is suppose to be. I tried `hc attr clients.focus.sizehints_floating false` and that made no difference. Here's a screenshot to illustrate:
![1621199339](https://user-images.githubusercontent.com/57952969/118412711-84c11600-b669-11eb-83d8-c35cbc575ceb.png)
This is with urxvt windows, so my guess is that urxvt expects to be a specific incremental size rather than pixel size. If there is a way already, I'm not sure how to make herbstluftwm go ahead and respect that size despite some other method requesting an exact pixel size

**Comment by Barbarossa93** [comment]
So in that screenshot, I spawned that window through a keybinding and it came up like that. If I spawn the window from a command in the terminal, the window borders are correct, until I focus it. Then, one of the sides becomes larger than it should be. The window itself doesn't change size. It seems like herbstluftwm respects the initial size hints, but forgets them as soon as the focus changes? Is there a way to always respect size hints?

**Comment by Barbarossa93** [comment]
Ah, sorry for the spamming, but now I think I've found something interesting! When I run `hc attr clients.focus.sizehints_floating false` the border is fixed. If I unfocus and then refocus, I run `hc attr clients.focus.sizehints` to get a value of true when it was set to false and the border is also wonky again! Unless I have some other setting that's renabling size hints for floating windows, could this be a bug?

**Comment by t-wissmann** [comment]
In your scenario, you should keep `clients.focus.sizehints_floating` enabled (which is the default). Does the bug really exist when setting the client size via `floating_geometry`?

In your description of unfocusing and refocusing, you mention `sizehints_floating` and `sizehints` (which does not exist). Did you maybe accidentally check `sizehints_tiling`?

Nice screenshot, by the way!

**Comment by Barbarossa93** [comment]
Woops, I must've typed too quickly, I meant `sizehints_floating`! It's not necessarily just with `floating_geometry`, it's any tool such as `xdotool` that sets the window to a specific pixelsize (but yes, it definitely happens with the rule). My guess is that it's related to how `urxvt` can technically only be in sizes based on number of columns and lines and while herbstluftwm respects it initially, changing focus causes the border to snap to the pixel size that was either specified by the rule or xdotool.

Applying the `noinc.diff` patch from [here](https://aur.archlinux.org/packages/rxvt-unicode-fontspacing-noinc-vteclear-secondarywheel/) makes the problem go away, but causes other problems that prevent me from using it.

Also, thanks! :D

**Comment by Barbarossa93** [comment]
Well... I think I solved it with the patch from [here](https://unix.stackexchange.com/questions/473183/how-to-configure-openbox-to-ignore-the-size-hint-of-a-specific-applications-win). I suspect that this is still unintended behavior, so I'll let you decide how to proceed  from here

**Comment by t-wissmann** [comment]
I've reproduced it an have a patch for it:
```diff
diff --git src/xmainloop.cpp src/xmainloop.cpp
index b2f4d19a..d07801d3 100644
--- src/xmainloop.cpp
+++ src/xmainloop.cpp
@@ -537,6 +537,9 @@ void XMainLoop::propertynotify(XPropertyEvent* ev) {
                 client->update_wm_hints();
             } else if (ev->atom == XA_WM_NORMAL_HINTS) {
                 client->updatesizehints();
+                Rectangle geom = client->float_size_;
+                client->applysizehints(&geom.width, &geom.height);
+                client->float_size_ = geom;
                 Monitor* m = find_monitor_with_tag(client->tag());
                 if (m) {
                     m->applyLayout();
```
However, it will take a bit more time until I have a test case for it such that I can fix it in the git version. Are you using the git version or releases?

**Comment by Barbarossa93** [comment]
I'm using the git version! I have a fix for now so no rush
