### ISSUE TITLE
Black screen when someone annotates shared screen

### ISSUE THREAD

**Issue by AckslD** [herbstluftwm/herbstluftwm#1323]
I don't know if this an issue with herbstluftwm but whenever someone draws on my shared screen in zoom everything goes black. Even if I switch tag or anything else. Only my cursor is there and whatever was drawn. Anyone else having the same issue?

**Comment by t-wissmann** [comment]
Is this issue solved if you use a compositor, e.g. picom?

**Comment by AckslD** [comment]
Sorry for my lack of knowledge but to try it would I simply install it and run `picom`?

**Comment by t-wissmann** [comment]
Exactly! Just install and run it. (Beware: do not pause the process (Ctrl+Z) or your session will hang)

**Comment by AckslD** [comment]
That did indeed work @t-wissmann! Thanks!
