### ISSUE TITLE
herbstclient dump/load using window class:instance? (Save/load states across reboots)

### ISSUE THREAD

**Issue by Barbarossa93** [herbstluftwm/herbstluftwm#1335]
I'm trying to figure out a way to save/load sessions across reboots. While the scripts provided in the repo are very nice, they unfortunately rely on window id's rather than class or instance information from the window. This means that the identifying info for each window becomes useless across reboots as the window id's change constantly. Using something like class/instance, I can at least create an external script to process the current state file and then generate a launch script to use for the next boot.

There is probably a better way to go about saving/loading states across reboot than with this request, but I couldn't figure it out. The main reason why I'd like to have this ability is because unfortunately I have an optimus laptop. Normally, I have the discrete card powered off to save precious battery. When I need to power it on to use the hdmi port for an external monitor, I have to restart my x session, losing my entire setup. The same is true for when I want to power down the card.

**Comment by t-wissmann** [comment]
Maybe you can solve this with an explicit python script that not only saves the output of `dump` but also saves a mapping from window ids to class and instance.

On restore, one needs to create a new mapping such that one can translate the window id's from before into current window ids.

In principle, the perfect solution was if hlwm supported X11 session saving which is needed anyway in the long run for #838.

**Comment by Barbarossa93** [comment]
Yeah, I've been trying to figure out how to script this in the mean time. The hard part will be restoring the session; I don't think I can use the `load` command unless windows exist. So essentially, I'd have to translate from win id to window class/instance/title, figure out what to launch, launch the programs, find the window ids of all the newly launched programs, then finally insert into a `hc load` command. 

Alternatively, I like the way bspwm does [it](https://github.com/baskerville/bspwm/tree/master/examples/receptacles). They create oneshot rules so that the next window that launches and matches the rule, the window is placed where it was prior to session restore. It looks like that might be possible in HLWM using the `index` consequence, but I am unsure if the information provided by `dump` is giving the needed frame index information.

Are you planning on implementing X11 session saving anyway? I may just tough it out with bumblebee until then.

**Comment by t-wissmann** [comment]
> Yeah, I've been trying to figure out how to script this in the mean time. The hard part will be restoring the session; I don't think I can use the `load` command unless windows exist.
Yes, `load` requires the windows to exist already, otherwise the window IDs are just ignored (but the frame layout is nevertheless created)

> Alternatively, I like the way bspwm does [it](https://github.com/baskerville/bspwm/tree/master/examples/receptacles). They create oneshot rules so that the next window that launches and matches the rule, the window is placed where it was prior to session restore. It looks like that might be possible in HLWM using the `index` consequence, but I am unsure if the information provided by `dump` is giving the needed frame index information.

Oh right, this can be done in hlwm easily. The following bash script creates another bash script that can be called during restore and that then will create the one-short rules:
```bash
#!/usr/bin/env bash

for id in $(herbstclient foreach C clients. echo C|grep -oE '0x[0-9a-fA-F]*') ; do
    client="clients.${id}"
    rule=(
        class="$(herbstclient get_attr ${client}.class)"
        instance="$(herbstclient get_attr ${client}.instance)"
        tag="$(herbstclient get_attr ${client}.tag)"
    )
    if herbstclient compare "${client}.floating" = on ; then
        rule+=( "floating=on" )
        consequence=
    else
        rule+=(
            "index=$(herbstclient get_attr ${client}.parent_frame.index)"
        )
    fi
    echo herbstclient rule once "${rule[@]}" "# $id"
done
```
E.g. here, the output is:
```
herbstclient rule once class=cantata instance=cantata tag=irc index=11 # 0x160000f
herbstclient rule once class=URxvt instance=urxvt tag=irc index=10 # 0x1c0000a
herbstclient rule once class=URxvt instance=urxvt tag=irc index=01 # 0x2a0000a
herbstclient rule once class=TelegramDesktop instance=telegram-desktop tag=irc index=00 # 0x3400006
herbstclient rule once class=Emacs instance=emacs tag=vim index=0 # 0x36000ca
herbstclient rule once class=URxvt instance=urxvt tag=scratchpad index= # 0x380000a
herbstclient rule once class=qutebrowser instance=qutebrowser tag=web index=0 # 0x3a000f1
herbstclient rule once class=Evince instance=evince tag=vim index=1 # 0x5600007
herbstclient rule once class=URxvt instance=urxvt tag=web index=10 # 0x580000a
herbstclient rule once class=URxvt instance=urxvt tag=web index=10 # 0x600000a
```
Unfortunately, this does not work well with if you have multiple terminals with the same class and instance.

> Are you planning on implementing X11 session saving anyway? I may just tough it out with bumblebee until then.

Yes I will implement this, but I don't know when.

**Comment by Barbarossa93** [comment]
Absolutely brilliant, thank you! A quick question though, will I still need `hc dump/load` to create the frame layouts before I can use the oneshot rules? Regarding terminal programs, my shell changes the window title to the running process so for things like `neomutt` or `weechat`, the title info will be the information to use when trying to figure out what to launch. I can definitely include that in the nifty bash script you've provided.

**Comment by t-wissmann** [comment]
Yes, the frame layouts need to exist. The window title is probably changed too late (you have to try it). Sometimes the title is only changed after the window is already managed by the window manager (but e.g. urxvt supports `-t`. If you run `urxvt -e neomutt`, then the title is also changed to `neomutt` during startup according to the urxvt man page)

**Comment by Barbarossa93** [comment]
Yup, I start each program with `urxvt -e <command>` and it works great! The one thing I am noticing so far unfortunately is that it doesn't seem to affect zathura; it must be changing it's title too late. Not sure how to fix/ work around it.

In either case, I think my issue is effectively solved. Since the ideal implementation of X sessions is already mentioned in another issue, this issue is technically a duplicate. I'll close this issue then. Thanks so much @t-wissmann ! I greatly appreciate the help :)

**Comment by t-wissmann** [comment]
Great to hear that! For zathura, the instance/class rule should work (instead of title).

**Comment by Barbarossa93** [comment]
Yes, that does work, but if I have multiple instances on different tags, then the wrong document could get loaded on the wrong tag :( For now, I just set a permanent rule to have all zathura instances on one tag, so hopefully that will be fine for the most part
