### ISSUE TITLE
[feature request] fullscreen a frame while a windows in it is fullscreen

### ISSUE THREAD

**Issue by tekkenly** [herbstluftwm/herbstluftwm#1339]
I love the fact that when a window is in fullscreen mode, I can still cycle through other windows for quick access. In my workflow, I have a bunch of terminals open in a frame, in most time, I can just use max mode and cycle through them. But, sometimes I need them to a bit bigger, I switch a terminal to fullscreen mode, then, when I cycle through the terminals, it doesn't feel the same as in max mode.

I think when fullscreen a windows, fullscreen the frame containing it should be a good way to make this workflow better, also, more logically consistent.

**Comment by t-wissmann** [comment]
Maybe you're issue can be solved with a bit of scripting:

*1.* do you really need fullscreen mode or do you actually need window maximization? there is a `maximize.sh` script (in the examples folder) that 'maximizes' a tiled window simply by reducing the layout to one frame in max layout. and there, you can cycle through all windows as usual (and unmaximizing then restores the previous layout).

*2.* If you replace the keybind for $Mod-c / `cycle` with the following, you should obtain the desired effect:
```
hc keybind Mod4-c substitute FS clients.focus.fullscreen \
        chain , set_attr clients.focus.fullscreen off \
              , cycle \
              , set_attr clients.focus.fullscreen FS
```
This command 'remembers' the current windows fullscreen state and passes it to the next window in the `cycle` order. With this, only one window in the frame is in fullscreen mode, so when pressing Mod-f one returns to the normal setup where no window is in fullscreen mode.

**Comment by t-wissmann** [comment]
By the way: this also works for `cycle_all`. (and I think it's both useful, so I've added it to my configuration.)

**Comment by tekkenly** [comment]
@t-wissmann Thanks a lot for your help, although it's not what I was thinking, these scripts really opened my mind about how to use herbstluftwm. I bet I can come up with some script to do what I want in an even better way.
