### ISSUE TITLE
MouseManager overrides existing cursor

### ISSUE THREAD

**Issue by pjones** [herbstluftwm/herbstluftwm#1345]
I *think* that the `MouseManager` constructor is overriding whatever cursor is set before herbstluftwm starts:

```c++
cursor = XCreateFontCursor(g_display, XC_left_ptr);
XDefineCursor(g_display, g_root, cursor);
```

I use [home-manager](https://github.com/nix-community/home-manager) to manage all of my configuration files.  It generates my `~/.xsession` file which contains a call to `xsetroot` to set the cursor just before it starts herbstluftwm.  From what I can tell, `MouseManager` then clobbers the cursor I have set.

Is there a reason that `MouseManager` sets the cursor vs. having users call `xsetroot` in `autostart` similar to how the example file sets the root background color?

I'm happy to submit a PR if this is an acceptable solution.

**Comment by t-wissmann** [comment]
You're correct that the `MouseManager` constructor set the cursor on herbstluftwm start up. It is set to a sane default. In contrast to the default background color / wallpaper, this does not seem to be too much a matter of preference (e.g. I don't know a single application where one can configure a different default cursor). This is why I think it is annoying for most users having to define this explicitly in the default autostart.

On the other hand: why don't you set your preferred cursor on the root window in the `autostart`? If you set it in `.xsession`, it gets overwritten by hlwm on startup (which is before `autostart` runs). But if you put it in the `autostart` you should achieve the desired effect without the necessity to adjust hlwm's source code and more importantly, without all other hlwm users having to put it in their autostart explicitly.

**Comment by pjones** [comment]
I can understand your reasoning and it's a nice convenience for users.  I don't think many other window managers do this for you.

As I mentioned earlier, my `.xsession` is generated by home-manager.  I tell it was cursor I want to use and it generates all the GTK, QT, and Xresources code that is needed.  It also puts an invocation of `xsetroot` in the `.xsession` file.
 
I certainly *could* call `xsetroot` from my `autostart` file but then that information is duplicated and I have to keep it in sync.  I think I'd rather just patch herbstluftwm on my system so it doesn't set the cursor for me.

It sounds like the option of moving the cursor setting code out of `MouseManager` and into the `autostart` file isn't something you like very much.  Is there another solution you can agree to, such as a command line option or environment variable?  Is there a way to ask the X server what the current cursor is, and only set it if it's the default cursor?

Thank you.

**Comment by t-wissmann** [comment]
So what cursor are you actually using if it is not `XC_left_ptr`. Or is your actual issue that the cursor *font* (i.e. cursor theme) isn't correct?
If you don't want to duplicate information, you can set an environment variable in `.xsession` and in your `autostart`, you can pass the content of the environment variable to `xsetroot -cursor_name`.

If you want to make it configurable, the only way to accomplish this is by a command line flag, because modifications to settings/attributes are too late.

**Comment by pjones** [comment]
Right, it's the cursor theme.  When `MouseManager` sets the cursor to `XC_left_ptr` it reverts the theme/font back to the standard x11 black pointer for the root window.

**Comment by pjones** [comment]
I decided to go with a simpler solution to my problem by putting [this](https://github.com/pjones/hlwmrc/blob/fc89561a0e1c897fe41ae6b5e4174a5a23170764/config/autostart#L21) in my `autostart`:

```sh
set_cursor_cmd=$(grep xsetroot ~/.xsession | head -1)

if [ -n "$set_cursor_cmd" ]; then
  eval "$set_cursor_cmd"
fi
```

It's a bit of a kludge, but it gets the job done.  

I don't think there's a clear answer to this issue.  herbstluftwm is doing something nice by solving a common problem, nobody wants that ugly default X cursor.  But setting the cursor in the WM presupposes that something else isn't already setting the cursor.  A bit of a chicken and egg issue.  AFAIK most [other](https://github.com/i3/i3/issues/2182#issuecomment-177521015) [window](https://wiki.haskell.org/Xmonad/Frequently_asked_questions#Setting_the_X_cursor) [managers](https://github.com/baskerville/bspwm/issues/11) don't set the cursor and instead tell you to use `xsetroot`.  

I want to extend a heartfelt thank you to @t-wissmann and everyone that has contributed to herbstluftwm.  It's a fantastic window manager!
