### ISSUE TITLE
split window vertically by default

### ISSUE THREAD

**Issue by qbai** [herbstluftwm/herbstluftwm#1349]
one simple question :  by default, herbstluftwm use Mod + enter to split window horizontal。 how to change configuration file to make spliting window vertically by using mod + enter

**Comment by t-wissmann** [comment]
It's  `settings.default_frame_layout`, so e.g.:
```
hc attr settings.default_frame_layout horizontal
```
In order to apply the setting for *existing* tags, you can run:
```
hc foreach T tags.by-name. \
    sprintf ATTR '%c.tiling.root.algorithm' T \
    set_attr ATTR horizontal
```

(on very old hlwm versions, the method described in [the faq](https://herbstluftwm.org/faq.html#_q_i_set_default_frame_layout_to_my_favorite_layout_but_it_doesn_8217_t_work_with_the_root_frame_existing_frames) was necessary)

**Comment by qbai** [comment]
hi,
I copied hc attr settings.default_frame_layout horizontal into my autostart, it can not work, still split vertical.
and I also copied the following into my autostart, it can not work. why is that? 

hc foreach T tags.by-name. \
    sprintf ATTR '%c.tiling.root.algorithm' T \
    set_attr ATTR horizontal

**Comment by qbai** [comment]
I found one thing: after enter mod+space, it change to horizontal, so that is workround for this issue, and you can close this issue. thanks your help!

**Comment by t-wissmann** [comment]
> hi,
> I copied hc attr settings.default_frame_layout horizontal into my autostart, then reboot and it can not work, it still split vertical.
> and I also copied the following into my autostart, it can not work. why is that?
> 
> hc foreach T tags.by-name.
> sprintf ATTR '%c.tiling.root.algorithm' T
> set_attr ATTR horizontal

This has to be in *one line*, and if it is spread across several lines, you need the `\` (as in my post above)

**Comment by qbai** [comment]
herbstclient foreach T tags.by-name. sprintf ATTR '%c.tiling.root.algorithm' T set_attr ATTR horizontal                                   3 ↵
set_attr: "horizontal" is not a valid value for algorithm: attribute is read-only
set_attr: "horizontal" is not a valid value for algorithm: attribute is read-only
set_attr: "horizontal" is not a valid value for algorithm: attribute is read-only
set_attr: "horizontal" is not a valid value for algorithm: attribute is read-only
set_attr: "horizontal" is not a valid value for algorithm: attribute is read-only
set_attr: "horizontal" is not a valid value for algorithm: attribute is read-only
set_attr: "horizontal" is not a valid value for algorithm: attribute is read-only
set_attr: "horizontal" is not a valid value for algorithm: attribute is read-only
set_attr: "horizontal" is not a valid value for algorithm: attribute is read-only

it looks this can not work by run above command

**Comment by qbai** [comment]
and I also run the following command and it can not work, is it bug for herbstluftwm?
herbstclient attr settings.default_frame_layout 1

**Comment by t-wissmann** [comment]
You need the current version of herbstluftwm: 0.9.3.

**Comment by qbai** [comment]
thanks your help, it does work on 0.9.3. close it.
