### ISSUE TITLE
Firefox crashes

### ISSUE THREAD

**Issue by noctuid** [herbstluftwm/herbstluftwm#1355]
Firefox crashes if I drag a tab off to open as a separate window. I've tried disabling some things (killing picom, killing running herbstclient --idle processes, etc.) to see if it was an issue with my configuration, but it still happens. I will try some more things to see if I can find some way for it not to happen, but I haven't seen this issue in other window managers. Let me know what useful information I can provide.

Also, this happens only for firefox. Dragging a tab to a new window in chrome, for example, works fine.

**Comment by t-wissmann** [comment]
It does not happen here on arch linux with firefox 90.0.1-1. Can you run firefox from the terminal and post its output here? Is it really a crash in the sense of a segmentation fault or some other kind of issue happening here?

**Comment by noctuid** [comment]
Sorry for the noise; I should have double checked first. This is definitely not an issue with herbstluftwm. Looks like a theme/icon issue.
