### ISSUE TITLE
Smart, unmoving gaps and borders

### ISSUE THREAD

**Issue by noctuid** [herbstluftwm/herbstluftwm#1356]
Basically, I want it so that borders and gaps normally appear in the same places regardless of whether there is 1 empty frame, 1 non-empty frame with automatic tiling, or multiple frames and manual tiling. An empty frame and a frame with a single window would have a single border and gaps in the same places. One frame with 2 horizontal windows would have gaps and borders in the same places as 2 horizontal frames with 1 window each.

smart_frame_surroundings has some overlap with what I want, but I'd want a setting that only disables the frame gap and borders with a single, non-empty frame. A single, empty frame should still have the frame gap.

I'd like the behavior of smart_window_surroundings when there are multiple frames, but I wouldn't want it when there is only one frame. I always want exactly 1 gap unless both automatic and manual tiling were being used.

I'm not sure what the best way to achieve this is. I can automatically change global settings to use either a frame gap or a window gap, but it is visually glitchy (e.g. when creating a window on tag with single empty frame, the window visually resizes), and it will affect other tags if there are multiple monitors.

Maybe a new "smart" setting could be added with special behavior in the case that there is one non-empty frame. I set both the frame gap and window gap, and the setting has the following behavior:
- disables frame gap and borders when there is 1 non-empty frame on the tag
- it acts as smart_window_surroundings if there is more than 1 frame (same use of minimal theme attributes)

**Comment by Barbarossa93** [comment]
That sounds a bit complicated to add to hlwm itself, however, what if `smart_window_surroundings` and `smart_frame_surroundings` could instead take one of four options: `gaps`, `borders`, `both`, or `none`. Specifying either `gaps` or `borders` would mean that the one specified will be removed when there's no ambiguity between frames/windows. `both` and `none` would function the same as `true` or `false` do currently. With this, it sounds like you could probably put together an `hc --idle` script to achieve what you want.

@t-wissmann what do you think about this? Personally I'd use `smart_frame_surroundings = borders` to hide the border when when nothing is open on the current tag, but keep the gap when one window is opened (e.g. qutebrowser) and then use window borders to give that window a border (this would obsolete an `hc --idle` script I'm using now).

**Comment by noctuid** [comment]
> With this, it sounds like you could probably put together an hc --idle script to achieve what you want.

This wouldn't really change anything for what I want. I'd still use `both` for `smart_frame_surroundings`. As I mentioned, running a script that changes global settings based on whether there is 1 empty frame, 1 non-empty frame, or multiple frames looks very glitchy and doesn't work with a multi-monitor setup. If there were tag-local settings, and it was possible to change them in response to `hc --idle` before changes are displayed, then I could use a script, but I'm not sure if this would be any simpler to implement.

**Comment by t-wissmann** [comment]
Sorry, but I don't understand what you want to achieve. On the one hand you write:

> borders and gaps normally appear in the same places regardless of whether there is 1 empty frame, 1 non-empty frame with automatic tiling, or multiple frames and manual tiling

but on the other hand you write:

> I'd like the behavior of smart_window_surroundings when there are multiple frames, but I wouldn't want it when there is only one frame.

So the first quote says "no difference between one and multiple frames" and the second quote says "difference between between one and multiple".

What can't you just disable `smart_frame_surroundings`, disable all visible frame borders, and make `window_gap`, `frame_gap`, and -`frame_padding` match? (note the minus)
```bash
hc attr settings.smart_frame_surroundings false
hc attr settings.smart_window_surroundings false
hc attr settings.frame_border_width 0
hc attr settings.frame_transparent_width 0
GAP=4
hc attr settings.frame_gap "$GAP"
hc attr settings.frame_padding "-$GAP"  # compensate window_gap
hc attr settings.window_gap "$GAP"
```
Then, all you see is the borders of the client windows, and so this requirement of yours is fulfilled:
> One frame with 2 horizontal windows would have gaps and borders in the same places as 2 horizontal frames with 1 window each.

Here's how it looks. Note that you don't see a difference between 2 windows in one frame and two frames with a window each (`hc split explode`).
![invisible-frames](https://user-images.githubusercontent.com/9048813/151187041-2b1aef7a-fb40-481c-b1f5-e5eb35d1321f.gif)

**Comment by Barbarossa93** [comment]
@noctuid to put it concisely, is the goal to have only one set of borders and gaps around every window visible regardless of whether there is one or multiple frames? If so, @t-wissmann's solution should achieve exactly that.

However, you write:
>smart_frame_surroundings has some overlap with what I want, but I'd want a setting that only disables the frame gap and borders with a single, non-empty frame. A single, empty frame should still have the frame gap.

Does this mean that when there is a single empty frame, you want gaps to exist but not borders? If that is the case, the proposed `smart_frame_surrounding borders` would work, but you could certainly hide it with an idle script currently.

**Comment by noctuid** [comment]
It was hard for me to find a way to word this that wasn't confusing, but @t-wissmann understood mostly correctly. I want a single empty frame to have both gaps and a border though. I should have said "A single, empty frame should still have the frame gap and border."

> hc attr settings.frame_padding "-$GAP"  # compensate window_gap

Thank you, that is very close to what I want. I didn't realize you could use a negative frame padding like this. The only difference from what I want is that I'd prefer to have the border shown on empty frames only (regardless of the number of frames open). Somewhat similar to #1357, it would be nice if there was a way to have a different frame border for empty vs. non-empty frames. Would it make sense for me to open a separate issue for this?

**Comment by t-wissmann** [comment]
> Thank you, that is very close to what I want. I didn't realize you could use a negative frame padding like this. The only difference from what I want is that I'd prefer to have the border shown on empty frames only (regardless of the number of frames open).

Then, adjust `settings.frame_transparent_width` in the above code snippet:
```
hc attr settings.smart_frame_surroundings false
hc attr settings.smart_window_surroundings false
BW=1
hc attr settings.frame_border_width "$BW"  # only visible for empty frames 
hc attr settings.frame_transparent_width 2  # only visible for empty frames 
GAP=4
hc attr settings.frame_gap "$GAP"
hc attr settings.frame_padding "$((-GAP-BW))"  # compensate window_gap and hide border width
hc attr settings.window_gap "$GAP"
```
This shows a border width of 1, and a bit of the frame background (with width 2), but it is only visible for empty frames:
![2022-01-26-163909_938x538_scrot](https://user-images.githubusercontent.com/9048813/151195261-ae8dbda9-a067-41eb-b857-34cba54f9745.png)


> Somewhat similar to #1357, it would be nice if there was a way to have a different frame border for empty vs. non-empty frames. Would it make sense for me to open a separate issue for this?

I think having a dedicated setting for this will just introduce too many explicit settings.

**Comment by noctuid** [comment]
Brilliant, thank you! This is better than adding new settings.

**Comment by t-wissmann** [comment]
Great! :tada: :-)
