### ISSUE TITLE
Setting to control background opacity of empty frames

### ISSUE THREAD

**Issue by noctuid** [herbstluftwm/herbstluftwm#1357]
Here is the behavior I want:
- empty frames have ~50 opacity for the background but not borders
- non-empty frames have the background completely cut out

Currently
- It's not possible to set the opacity for empty vs. non-empty frames, only for active vs. normal frames.
- Changing the frame opacity affects the border opacity, but I want to only change the background opacity. It's possible to set the alpha in the background color, but it doesn't look very nice compared to using frame_active_opacity.
- It seems it's not possible to configure some frames to have no background. I'd like to be able to use the equivalent of frame_bg_transparent on just non-empty frames. The reason is compositing isn't required, and the border isn't affected.

I'm not really sure what the best way to allow for this setup would be. Maybe it's new global settings like `frame_empty_bg_opacity`:
- only affects background, not border
- doesn't rely on compositing and juts cuts out background if 0 (could also be a separate setting, but this seems like a reasonable thing to do since compositing isn't needed for 0)
- I'm not sure what the interaction should be with the "active" and "normal" versions. Maybe it overrides them.

An alternative would be to allow some way to do local settings. For example, if you could specify a script path to determine the appearance of specific frames, it would be possible to check the client count and output different settings based on that. This would allow easily having different behavior for active and empty vs. normal and empty if someone needed to. I don't need anything complicated like that for my use case though.

**Comment by t-wissmann** [comment]
You can set the opacity of the background color by specifying rgba-colors, e.g.
```
hc set frame_bg_active_color '#9fbc0088'
```
Here, the hexidecimal 88 is 50% transparency (FF is opaque, and 00 is fully transparent). The part of a (non-empty) frame that is behind a client is already cut out, such that the semi-transparent layers (frame + terminal background) do not pile up.

Unfortunately, semi-transparent colors in the frames are displayed wrong (see issue #1382), but as soon this issue is fixed, this should provide exactly what you want :-)

**Comment by noctuid** [comment]
> Unfortunately, semi-transparent colors in the frames are displayed wrong (see issue #1382), but as soon this issue is fixed, this should provide exactly what you want :-)

Okay, I wondered why it looked different. I didn't realize it was a bug. That will cover the second point ("Changing the frame opacity affects the border opacity...") but not the first (no way to distinguish between empty vs. non-empty). Did any of my suggestions make sense, or can you think of a better way to handle this?

> The part of a (non-empty) frame that is behind a client is already cut out, such that the semi-transparent layers (frame + terminal background) do not pile up.

For this point, I would like for the entire background to be cut out (including the portion not behind a client). I only want a background to be shown on empty frames as a way to visually distinguish empty vs. non-empty.

**Comment by t-wissmann** [comment]
> > Unfortunately, semi-transparent colors in the frames are displayed wrong (see issue #1382), but as soon this issue is fixed, this should provide exactly what you want :-)
> 
> Okay, I wondered why it looked different. I didn't realize it was a bug. That will cover the second point ("Changing the frame opacity affects the border opacity...") but not the first (no way to distinguish between empty vs. non-empty). Did any of my suggestions make sense, or can you think of a better way to handle this?

I still try to understand the behaviour you want.

> > The part of a (non-empty) frame that is behind a client is already cut out, such that the semi-transparent layers (frame + terminal background) do not pile up.
> 
> For this point, I would like for the entire background to be cut out (including the portion not behind a client). I only want a background to be shown on empty frames as a way to visually distinguish empty vs. non-empty.

If you set the `frame_border_width` to 0, then you will not see the frame border and the entire frame background will be covered (and therefore cut out) behind the window:
```
hc attr settings.frame_border_width 0
```

**Comment by noctuid** [comment]
> I still try to understand the behaviour you want.

Basically I want some settings like frame_bg_active_color but to distinguish empty vs. non-empty (not active vs. normal). Let me try to explain with screenshots to make it more clear. With empty frames, I want a solid border and semi-transparent background:

![2022-01-26T09:35:13_-_](https://user-images.githubusercontent.com/4250696/151190599-e7d68471-b68b-46d4-aab8-b42df480b4fb.png)

I want to show non-empty frames with a completely transparent background (preferably cut out to not require compositing). Since the settings are for active or normal not empty vs. non-empty, I can't do this. I'll still have the background if I open a window (this screenshot is the behavior I do not want):

![2022-01-26T09:38:25_-_zsh](https://user-images.githubusercontent.com/4250696/151190746-fc715262-05f4-43b4-8681-764e326254bd.png)


This is what I'd prefer a non-empty frame to look like (completely transparent/cut out frame background):

![2022-01-26T09:40:28_-_zsh](https://user-images.githubusercontent.com/4250696/151190984-3d65c59b-7232-4c86-bce7-6926ae4eb3f3.png)

> If you set the frame_border_width to 0, then you will not see the frame border and the entire frame background will be covered (and therefore cut out) behind the window

Not sure if I'm misunderstanding, but this just hides the border.  There is still stacked opacity (darker) with the terminal and you can see the semi-transparent frame background around the edges terminal. I want the background actually cut out (like the description for frame_bg_transparent but only for non-empty frames) because I have some windows that have their own transparency (either builtin or with picom) and don't want unnecessary compositing if the window is opaque. Here too the major point is that I only want this to happen for non-empty frames. With the current available settings, I can't customize the behavior of empty vs. non-empty frames.

**Comment by t-wissmann** [comment]
> > If you set the frame_border_width to 0, then you will not see the frame border and the entire frame background will be covered (and therefore cut out) behind the window
> 
> Not sure if I'm misunderstanding, but this just hides the border. There is still stacked opacity (darker) with the terminal and you can see the semi-transparent frame background around the edges terminal

Ah, this is where the confusion comes from: since hlwm 0.9.3, the opacity does *not* stack up, because hlwm actively cuts the out the areas in the frame that are behind the window. Note that no read frame border is visible behind the semi-transparent window decoration:

![no-frame-behind-clients](https://user-images.githubusercontent.com/9048813/108606722-f7e52400-73bb-11eb-9328-0a27d23ce104.png)

This feature was implemented in PR #1187.

Does this solve your issue already?

**Comment by noctuid** [comment]
If it is possible to have the opacity settings not apply behind windows, that would solve the issue, but that doesn't seem to be the case for me. I am on herbstluftwm 0.9.3 (9cdf6938 built on 2021-08-16). As you can see in my screenshots, the background on the second screenshot is darker than the third (where I set `frame_active_opacity` to 0). Not sure if this is a configuration issue? How are you setting opacity in your example? In the above screenshots, I am using `frame_active_opacity`. I will switch to using `frame_bg_active_color` if #1382 is fixed and it looks the same. Should this cutting out behavior be happening with either of these? I have `frame_bg_transparent` as off for real opacity and am running picom.

**Comment by t-wissmann** [comment]
Are you really on the specified commit and not on a patched version? In your screenshots, frames and clients have round corners, and hlwm does not have round corners implemented. My screenshot is with the default config (that is in `share/`).

The cutting should happen independent of `frame_bg_transparent`.

**Comment by noctuid** [comment]
I'm using herbstluftwm-git from the aur. I just updated and restarted and see the same behavior. The rounded corners are from my compositor (picom). Is it possible that my compositor settings could be causing this? I tried tweaking them, but I always see the window background become solid when moving from `frame_active_opacity` as 0 to 100.

**Comment by t-wissmann** [comment]
Are you using plain (unpatched) picom from https://github.com/yshui/picom ? Can you try with the default picom config? can you share paste your picom config, such that I can try to reproduce it?

Here, on picom (with even [an old compton config](https://github.com/t-wissmann/dotfiles/blob/master/config/compton.conf)), the bg is perfectly cut out:
![image](https://user-images.githubusercontent.com/9048813/151323676-06d95c3d-11a0-4b1b-80ae-b53871a75c9d.png)
(Note that the frame bg is non-transparent `black` and you can sill see the wallpaper through the semi-transparent terminal)

**Comment by t-wissmann** [comment]
Great! Thanks for sharing that it was actually the shadow that darkened the background!
