### ISSUE TITLE
; key does not function when paired with Super as the modifier key

### ISSUE THREAD

**Issue by fakedeltatime** [herbstluftwm/herbstluftwm#1358]
I'm trying to use my custom movement binds from Vim (JLK;) but when trying to use ; in combination with Mod or Mod+Shift nothing happens.

**Comment by t-wissmann** [comment]
The key is called <kbd>semicolon</kbd>, so e.g.
```
hc keybind Mod4-semicolon focus right
```

**Comment by fakedeltatime** [comment]
> The key is called semicolon, so e.g.
> 
> ```
> hc keybind Mod4-semicolon focus right
> ```

Thank you very much, I believe I'm too used to keys being defined with strings.
