### ISSUE TITLE
how to config tags for dual monitors?

### ISSUE THREAD

**Issue by qbai** [herbstluftwm/herbstluftwm#1359]
I have 2 monitors, here is my autostart for tag creation and monitor config :
................
tag_names=( {1..9} )
  tag_keys=( {1..9} 0 )
  
  hc rename default "${tag_names[0]}" || true
  for i in ${!tag_names[@]} ; do
      hc add "${tag_names[$i]}"
      key="${tag_keys[$i]}"
      if ! [ -z "$key" ] ; then
          hc keybind "$Mod-$key" use_index "$i"
          hc keybind "$Mod-Shift-$key" move_index "$i"
      fi
  done
...............
hc detect_monitors

but now when I click $Mod + 1, it looks 2 tags on these 2 monitors show up.
My question is that : what is method to configure the same tag index for different monitor, for example, if I used monitor 1, $Mod+1 only click tag on this monitor, when I focus another monitor, it will work only on another.

if there is no way to config this, how to seperate tag into 2 groups for 2 monitors? thanks a lot

**Comment by qbai** [comment]
herbstluftwm can not support the above requirement?

**Comment by t-wissmann** [comment]
https://herbstluftwm.org/faq.html#_q_how_can_i_have_a_separate_list_of_tags_per_monitor

**Comment by qbai** [comment]
thanks ,let me try this later. close it at first, if any problem ,I will reopen it.
