### ISSUE TITLE
"attr theme.padding.." with herbstluftwm-0.9.3_1 irregular behaviour

### ISSUE THREAD

**Issue by sdothum** [herbstluftwm/herbstluftwm#1366]
On Void Linux..

i use attr theme.active.padding_left and attr theme.padding_left to set a left side border. With 0.9.3_1 from the command line padding behaviour is irregular -- sometimes showing, sometimes not, with multiple windows and frames in view. Sometimes, even within a frame, the padding is inconsistent for windows within that frame (some showing, some not).

**Comment by t-wissmann** [comment]
please paste the precise comamnds you are using. Also note that writing `theme.padding_left` also updates `theme.active.padding_left`.

**Comment by sdothum** [comment]
herbstclient attr theme.active.color            red
herbstclient attr theme.active.inner_color      "#707070"
herbstclient attr theme.active.outer_color      black
herbstclient attr theme.background_color        red
herbstclient attr theme.color                   "#707070"
herbstclient attr theme.floating.outer_color    black
herbstclient attr theme.inner_color             "#707070"
herbstclient attr theme.normal.color            "#707070"
herbstclient attr theme.outer_color             black
herbstclient attr theme.urgent.color            orange
herbstclient set frame_bg_active_color          red
herbstclient set frame_bg_normal_color          "#707070"
herbstclient set frame_border_active_color      white
herbstclient set frame_border_normal_color      black

**Comment by t-wissmann** [comment]
I've run the commands you've pasted and I can't spot any irregularity in the padding on the left. Can you upload a screenshot that shows the issue?

**Comment by sdothum** [comment]
![With herbstluftwm-0.9.2_1](https://user-images.githubusercontent.com/300188/132101746-357af6c8-fc3b-4368-ac06-e4cc5e4a92b5.jpg)

With same startup..

![With herbstluftwm-0.9.3_1](https://user-images.githubusercontent.com/300188/132101779-19feb8a8-5d4c-432b-a302-652aed9baa4e.jpg)

Note: herbstluftwm-0.9.3_1 on startup showed NO frame gap (at least colored). The gap set at startup is 3. To reveal a gap i had to set it to  6 to get a 3 pixel gap showing (accounting for the missing gap). Coloring for gap looks partial (and missing on other frames).. due to some transparency state irregularity(?).

This is just a kludge to get a colored spine showing on the left edge. Of course, would be better to be able to set such at the window level (vs frame).

**Comment by sdothum** [comment]
i got similar results -- needing to set gap greater than initial setting to show, irregular gap color -- to the above in herbstluftwm-0.9.2_1 when i tried using "frame_active_opacity" and "frame_normal_opacity" in place of "frame_bg_transparent".

**Comment by sdothum** [comment]
I've skipped onto 0.9.4 and the above reported problem with 0.9.3 "appears" to be fixed.

However, i now have a head scratcher that has been driving me around the bend! The frame background i use to create the left hand border now only renders if i disable "picom" (compositor) -- with picom running the frame background is transparent.

This is probably something really obvious with 0.9.4 but for the life of me.. i can't spot it! I've tried alpha-value colors specs, explicitly defining "frame_bg_transparent false".

What am i missing?

**Comment by sdothum** [comment]
No problem. Next week..

**Comment by sdothum** [comment]
Got a bit further.. the default picom config which worked with 0.9.2 appears to be causing the frame transparency in 0.9.4.

i am still seeing some level of transparency with the frame background, but at least now i can see the frame. Problem now is the frame color is not showing properly (am getting greyish color instead of red).

Will keep playing around with picom config and hlvm theme settings to see if i can get further.

**Comment by sdothum** [comment]
i now have the proper colors showing :) 

The problem stemmed from my herbstluftwm config theme for 0.9.2 behaving slightly differently with all the substantive (and good!) changes made to 0.9.4.

Still working through some minor transparency states but i think it's just a matter of my becoming more familiar with the new changes -- this last issue relates to the "frame_bg_transparent" flag. Will let you know how i make out.

**Comment by sdothum** [comment]
Everything is working beautifully -- no need for the unnecessary frame gymnastics i was using with 0.9.2.

With the additional object data now available with 0.9.4 i can now go onto some "smarter" window placement rules.

Great work! i am closing this issue.

**Comment by t-wissmann** [comment]
Great! Sorry that I didn't help much on this issue but I'm happy that it now seems to be resolved :)
