### ISSUE TITLE
Is there a way to run a loop for move_monitor such that latency is low?

### ISSUE THREAD

**Issue by Animeshz** [herbstluftwm/herbstluftwm#1369]
I wanted to have a sliding animation like thingy, and I think I can do it with monitors since they are virtual (does not depend on physical screen).

To adjust monitor offset herbstclient need to connect again and again with the wm and it slows down the movement, is there a way to push a continuous command sequence at once?

**Comment by t-wissmann** [comment]
have you looked at the q3terminal.sh script? it calls move_monitor multiple times, but I'd say the animation is sufficiently smooth.

**Comment by Animeshz** [comment]
Looks quite smooth but does feel a bit jerky if height to move is sufficient enough (more than half of screen)😅😅

**Comment by Animeshz** [comment]
Can we have a dedicated command accepting information about animation and performing them with given parameters 👀🤔

**Comment by tiosgz** [comment]
Possible solutions I can think of –

- a `sleep`/`delay`/whatever command (if it wouldn’t increase the complexity too much)
- check if hlwm allows one client to call multiple commands (@t-wissmann, can you tell?) – if yes, reuse it for what you need (that is, if it improves the latency enough)
- try if e.g. `jonaburg/picom` [which is, iirc, the animation fork] would work for you

**Comment by Animeshz** [comment]
Fair, did not knew picom can animate virtual monitors 👀...
