### ISSUE TITLE
Can't figure out how to keybind xkill correctly

### ISSUE THREAD

**Issue by ojsl1** [herbstluftwm/herbstluftwm#1370]
Currently I'm using `hc keybind $Mod-y spawn "/usr/bin/xkill"`, but the colossal problem with this is when herbstclient spawns programs it also disowns them so I cant really exit xkill like I normally would with ctrl+c – this leaves my pointer unusable unless I kill something. How would I make a temporary keybind that sends a sigint to xkill when it's spawned?

**Comment by t-wissmann** [comment]
Of course you can do something like `hc keybind $Mod-Shift-y spawn killall xkill`, then you can stop xkill with another keybinding. But in your case, you can simply exit xkill by clicking with the right mouse button (only left click kills the application, right click just makes xkill exit).

**Comment by ojsl1** [comment]
> Of course you can do something like `hc keybind $Mod-Shift-y spawn killall xkill`, then you can stop xkill with another keybinding. But in your case, you can simply exit xkill by clicking with the right mouse button (only left click kills the application, right click just makes xkill exit).

Well... I knew there had to be a simple solution, but as simple as right clicking? I never would've guessed... /facepalm
Thank you for the quick reply!
