### ISSUE TITLE
Possible bug with floatplacement

### ISSUE THREAD

**Issue by cbf305** [herbstluftwm/herbstluftwm#1377]
I'm playing around with running HLWM in KDE and I seem to have a reproducible issue with the KDE panel items.  I also get the same results with Latte Dock, so I am not sure if this is a HLWM thing or a Plasma thing since it's not running KWin.

I have a 2 rules:
```
rule class='lattedock' floating=on floatplacement=none
rule class='plasmashell' floating=on floatplacement=none
```

When the panel, either KDE or Latte, is on the bottom and you click on any of the panel items, say for example the clock to get the calendar pop-up.  The first time it is opened it is right above the clock as it would be under KWin.  The second time it is opened it opens in the top left of the workspace.  The third time it is opened it is back above the clock.  This alternating location repeats indefinitely for any panel item that opens a pop-up.

If I move the panel to the top, the items open in their respective locations as expected every single time.  The only way I have found to have the panel on the bottom and keep the pop-ups in their respective locations is to set `manage=off`, but then they stay open when they lose focus.

Not a big deal, I can certainly live with the panel set to unmanaged, but if this really is a bug, I wanted to alert to it.

Thanks!

**Comment by cbf305** [comment]
I updated a couple of days ago and this seems to be fixed.  I can no longer reproduce this issue on multiple machines and the KDE panel pop-ups open right where one would expect with the panel at the bottom.  I am running hlwm 0.9.3 build a5be0915.  Thank you to who ever fixed this :-)

**Comment by t-wissmann** [comment]
Hi, thanks for checking again! Sorry that I didn't take a look at this yet. Also, I don't think this issue was really about `floatplacement`, but about something related to floating coordinates.
