### ISSUE TITLE
How can i hide the frame borders on empty frames on an empty workspace/tag?

### ISSUE THREAD

**Issue by PenguinBotOnGithub** [herbstluftwm/herbstluftwm#1378]
One thing that bothers me, is that herbstluftwm won't hide the empty frame/frame borders in an empty workspace/tag. So with nothing opened, herbstluftwm just shows a big colored border which bothers me. So is there any way to hide frame borders on an empty workspace/tag?

**Comment by PenguinBotOnGithub** [comment]
![Screenshot_20211113_104249](https://user-images.githubusercontent.com/87927635/141604480-9767c3bf-adef-4b6d-960c-e5c1b3b4da15.png)
Here is a screenshot

**Comment by t-wissmann** [comment]
No, it's not possible to hide this indicator frame. I'm not sure where the blurry wallpaper in your screenshot comes from, but with
```
hc attr settings.frame_bg_transparent true
hc attr settings.frame_transparent_width 0
```
you should be able to clearly see the wallpaper.

But I regularly see this request to hide the frame decoration if it is the only frame on an empty tag (even if it is focused). So maybe I should consider implementing it.

**Comment by Barbarossa93** [comment]
I asked @t-wissmann  some time ago on IRC about this exact feature. He was kind enough to offer me this script:
```
#!/usr/bin/env bash

# hide the frame border if the focused frame is empty

#: and . compare tags.focus.curframe_wcount = 0 \

herbstclient --idle focus_changed | while read event; do
  herbstclient mktemp int OPACITY chain \
    : set_attr OPACITY 100 \
    : and . compare tags.focus.frame_count = 1 \
    . compare tags.focus.curframe_wcount = 0 \
    . set_attr OPACITY 0 \
    : substitute VAL OPACITY set frame_active_opacity VAL
done
```
While it works fine, I would agree that an option builtin to herbstluftwm would be more desirable.

**Comment by RaZ0rr-Two** [comment]
I am not sure but doesn't this setting solve this ?

`hc set smart_frame_surroundings on`

**Comment by PenguinBotOnGithub** [comment]
> No, it's not possible to hide this indicator frame. I'm not sure where the blurry wallpaper in your screenshot comes from

It came from Picom, apparently it thinks herbstluftwm's frames are windows that needs to be blurred, so i disabled the blur effects

**Comment by PenguinBotOnGithub** [comment]
> I am not sure but doesn't this setting solve this ?
> 
> `hc set smart_frame_surroundings on`

That did the trick!, although it it fullscreens windows and now herbstluftwm only respect the frame gap value i set where there are more than 1 frame in the tag, but this is good enough for me. If t-wissmann still wants to make "hiding frame indicators when there are no windows in the tag" a feature, then i'll support it and maybe i'll use it in the future
