### ISSUE TITLE
move a special frame

### ISSUE THREAD

**Issue by zakariaGatter** [herbstluftwm/herbstluftwm#1380]
Hello Everyone 

this is just a question, i want to know if its possible to open a special application in a special frame ???

with herbstluftwm rules

**Comment by t-wissmann** [comment]
yes, it's possible with the `index=...` consequence. See also the `frame index` section in the [man page](https://herbstluftwm.org/herbstluftwm.html)

**Comment by zakariaGatter** [comment]
thank you so much
