### ISSUE TITLE
Separate "normal" color settings for unfocused tabs

### ISSUE THREAD

**Issue by Nairou** [herbstluftwm/herbstluftwm#1389]
Loving the new tab support!

Right now, if you have several windows stacked up with tabs across the top, the currently active window's tab gets the "active" coloring. But all of the inactive tabs have the same "normal" coloring that unfocused windows have. While this makes some sense, in practice it can be a little jarring.

For example, on my current theme, the active window it red, while all unfocused windows are white. This used to be fine, the white made the title seem invisible against the white window contents. However, I now have unfocused tabs in white as well, which makes them stand out next to the red.

They are technically unfocused, but they are still part of the active frame, so a separate color (in my case, something dark rather than white, so the red continues to stand out) would be nice.

**Comment by t-wissmann** [comment]
Thanks :-)

I understand, but then one would also need an extra option for urgent windows. Maybe one needs something like `theme.tiling.tabbed` (which sounds similar to what is requested in https://github.com/herbstluftwm/herbstluftwm/issues/1388)
