### ISSUE TITLE
Single window floating

### ISSUE THREAD

**Issue by The-Compiler** [herbstluftwm/herbstluftwm#14]
We could probably check how other tiling WMs with an internal tree (i3/bspwm come to mind) solves this issue.

**Comment by absolutejam** [comment]
Only thing lacking on my favourite WM. I'd help if I had any knowledge of the internals of the WM or C...

Any idea if this is a fantasy, or a possible reality?

**Comment by t-wissmann** [comment]
It will be implemented as soon as the winterbreeze branch is merged.

**Comment by gtors** [comment]
@t-wissmann Hi! Are there any plans to merge the winterbreeze branch?

**Comment by t-wissmann** [comment]
Plans yes, but no concrete plans, since it is not ready for being merged.

**Comment by gtors** [comment]
Can I somehow help to speed up this process?

**Comment by Alkeryn** [comment]
Anything new ?

**Comment by fdietze** [comment]
If its not finished, could you please make a beta-release for others to try and improve?

**Comment by shizonic** [comment]
@fdietze Why not just building it from source of the winterbreeze branch?

**Comment by Tucanix** [comment]
I left Herbstluftwm a couple years ago because of problems like this and now I'm back. This is a must have feature. Guess I wont stay here for long then.

**Comment by t-wissmann** [comment]
Dear @The-Compiler, @absolutejam, @gtors, @Alkeryn, @fdietze, @shizonic, and possible others who were waiting for this,

I've implemented single window floating in the current git version of herbstluftwm (and winterbreeze was merged two  weeks ago). I'm sorry for letting you all wait for this feature so long. If I recall correctly, this was one of the earliest feature requests (in 2011).

I'd be happy if you try the current git version of herbstluftwm and try it! The command
```
hc attr clients.focus.floating toggle
```
toggles the floating state of the focused window. I've added this keybinding to my (and the default) autostart
```
hc keybind $Mod-Shift-f attr clients.focus.floating toggle
```
Maybe you have another suggestion what the default keybinding should be (i3 uses `$Mod-Shift-space` iirc).

If you notice any strange behaviour or even crashes, please open an issue here on github, or report it by mail or on the irc.

Thank you for using herbstluftwm!

**Comment by shizonic** [comment]
@t-wissmann Thank you so much. Gonna try it assap.

**Comment by fdietze** [comment]
Great News! Thank you! This would be a reason for me to switch back from xmonad :)
