### ISSUE TITLE
New 'fixedsize' rule condition

### ISSUE THREAD

**Issue by wertiop121** [herbstluftwm/herbstluftwm#1406]
This 'fixedsize' condition, that is proposed here, would be true when the minimum size of a window is equal to its maximum size.

This is useful to recognize dialog windows that don't have the `_NET_WM_TYPE_DIALOG` property, and set them to `floating` or `pseudotile` to make them take a suitable size.

Some windows, like the alacritty terminal window, have the minimum and maximum size set to 0 when they are created, and changed later, but shouldn't be set to floating. To fix this, it should also be checked if the maximum window size is greater than 0.

**Comment by wertiop121** [comment]
I'm planning to make a pull request for this issue.

However, I'm unsure about what is the best way to use (or not use) input values. I'm considering these two options:
1 - Take "true" or "false", with "false" negating the condition, but we already have a "not" flag for rules that does this.
2 - Take no input value, and instead allow conditions without an operator, so that the syntax for this is simpler: `hc rule fixedsize floating=on`.

I'd like to hear your opinions about this.

**Comment by t-wissmann** [comment]
Hi, on January 1 I had implemented `fixedsize` (and I went for the second option). The only missing bits were the test cases and the documentation, which I have just added, and then uploaded it as PR #1419.

**Comment by akinokonomi** [comment]
> and then uploaded it as PR #1419.

Just tested, works great for me. Thank you for this!
