### ISSUE TITLE
Usability regression in #1404

### ISSUE THREAD

**Issue by gravndal** [herbstluftwm/herbstluftwm#1407]
Before https://github.com/herbstluftwm/herbstluftwm/pull/1404 it was possible to click the top edge of the monitor to focus clients when frame_gap was set to 0. This means you don't need to aim.

With https://github.com/herbstluftwm/herbstluftwm/pull/1404 you now have to click frame_width(?) pixels down from the edge.

As https://github.com/herbstluftwm/herbstluftwm/pull/1404 solves a real issue I would suggest adding a check if the resize action is for the top edge of the monitor, and skipping it. This shouldn't have any downsides as resizing on the top edge isn't something that makes all that much sense to do.

**Comment by t-wissmann** [comment]
Hi, you're right that this is even a real regression. To properly fix it, the handler in xmainloop should be fixed as follows:
```diff
diff --git src/xmainloop.cpp src/xmainloop.cpp
index 5f08703c..a36f9d61 100644
--- src/xmainloop.cpp
+++ src/xmainloop.cpp
@@ -246,6 +246,9 @@ void XMainLoop::buttonpress(XButtonEvent* be) {
             bool decorationClicked = be->window == client->decorationWindow();
             if (decorationClicked) {
                 resize = client->dec->positionTriggersResize({be->x, be->y});
+                if (resize) {
+                    resize = resize * client->possibleResizeActions();
+                }
             }
             if (resize) {
                 mm->mouse_initiate_resize(client, resize);
```

**Comment by gravndal** [comment]
Yeah, that's a much simpler fix. Works nicely. :+1:
