### ISSUE TITLE
Inconsistent border colour with equal border_width-, inner_width-, and outer_widths in max layout.

### ISSUE THREAD

**Issue by gravndal** [herbstluftwm/herbstluftwm#1418]
With `border_width == inner_width == outer_width` in the `max` layout you get this somewhat odd behaviour:

![hlwm_bw=iw=ow](https://user-images.githubusercontent.com/4656860/149198774-b9a3a229-ed74-466d-84b3-6f2ccfbea27f.gif)

Contrast this with other layouts or floating windows where the order of precedence is outer > inner > basic.

Having a chequered border might be neat, and this doesn't look too bad with two or three windows, but I don't think it's intentional?

Edit: settings used in the gif:
```
INNER_COLOR='#ebdbb2'
OUTER_COLOR=$INNER_COLOR
ACTIVE_TITLE_COLOR='#f2e5bc'
ACTIVE_COLOR='#282828'
NORMAL_TITLE_COLOR='#282828'
NORMAL_COLOR='#ebdbb2'
```

**Comment by t-wissmann** [comment]
Indeed, this is not intentional. I'm fixing this in PR #1423.
