### ISSUE TITLE
overlay with keyboard focus?

### ISSUE THREAD

**Issue by Turmfalke2** [herbstluftwm/herbstluftwm#1431]
hi,
Use case: I enjoy playing poe (https://www.pathofexile.com/) and would like to use the program APT (https://github.com/SnosMe/awakened-poe-trade) with it. APT uses a library from the same author (https://github.com/SnosMe/electron-overlay-window) to draw an overlay (extra client) over the game to display information when requested to do so.  

I totally understand this clashes with how herbstluftwm usually operates, but switch wm whenever I want to play poe is annoying. Herbstluftwm is quite powerful, so maybe I am just missing a trick here?

What I have tried:
I expect I will need a composer for the overlay to be transparent and have configured picom for that.
I have tried applying different herbstluftwm rules to APT's client. Setting it to be unmanged is pretty close to what I want, but focus handling is strange with unmanged clients. When I invoke the overlay my mouse gets captured, but my keyboard focus is still going to game. From what I have found keyboard focus is not intended to work with unmanaged clients?

Alternatively I have tried leaving it managed, but creating an extra monitor on top of my regular with idea of moving the overlay there. However I couldn't quite figure out how manage focus/transparency with overlapping monitors.

Is there any hope in getting such an overlay to work with herbstluftwm?

**Comment by gravndal** [comment]
While not perfect, the following works for me:
```
hc rule class='awakened-poe-trade' fullscreen=on focus=off
hc set focus_stealing_prevention 0
hc set focus_follows_mouse 0
```

Turning off focus stealing prevention is strictly speaking not necessary, but it does make the experience slightly nicer as you don't have to manually change focus to interact with (and raise) APT.

**Comment by Turmfalke2** [comment]
This is nice, better than I could get it to behave. Which part do you not consider to be perfect?

**Comment by gravndal** [comment]
The primary annoyance is APT still getting focussed when calling `hc cycle_all +1/-1` or similar. While this is solvable by adding some logic to whatever keybindings are relevant, I simply haven't bothered.

The PoE game window is also obviously raised above APT when focussed, and APT doesn't steal focus/raise itself on the default `Ctrl-D` mapping until the mouse actually moves over the non-transparent part of the overlay.

**Comment by Turmfalke2** [comment]
I think I can live with that. Thanks for your help.
