### ISSUE TITLE
Don't reinstall the build dependencies in every travis run 

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#146]
At the moment, most of the time in travis is spent on installing the dependencies. In gitlab, I one can setup a docker image that has the all the dependencies already installed. Can we do something similar here to get the test results quicker?

**Comment by t-wissmann** [comment]
Do I understand it correctly, @The-Compiler, that qutebrowser's travis sets up the docker image manually in https://github.com/qutebrowser/qutebrowser/blob/master/scripts/dev/ci/travis_run.sh to have all the dependencies already installed?

**Comment by dnnr** [comment]
I wondered that as well... from my superficial research, this isn't something they expect you to do.

In the section about caching, they even explicitly say that you "should not" cache things that can be quickly downloaded, such as Debian packages: https://docs.travis-ci.com/user/caching/#things-not-to-cache

I don't quite get it, to be honest...

**Comment by dnnr** [comment]
What we probably could do:
 * Run the tests using Docker images created on-the-fly
 * Manually publish reference images on the Docker Hub
 * Pull said reference images and use them as cache source (`--cache-from`) for the on-the-fly image creation

This basically abuses the Docker Hub as a manually maintained, persistent cache.
However, it if works, it should replace all time wasted on package installation with time spent on downloading the reference image (and a little overhead for a all-cache-hits run of `docker build`).

Disclaimer: I've worked a lot with Docker (in CI environments), but have never published images on the Docker Hub, nor have I used `--cache-from`.

A positive side-effect of that would be that it frees us from the constraints of the Travis environment, in terms of distribution and compiler choice.

**Comment by The-Compiler** [comment]
I only use Docker for qutebrowser in two jobs because I want to test on Archlinux (so I get an up-to-date Qt before PyQt releases its binary release). I'm not sure if it's really worth the additional complexity for hlwm, as according to Travis the apt install steps seem to take around 20 seconds?

**Comment by t-wissmann** [comment]
I can understand that one should not cache things that are just downloaded. But for the case of debian packages, more than just downloading is done. I'm fine with any of the docker options.

@The-Compiler: yes, its less than 20 seconds but for each of the jobs. (I've just looked at [qutebrowser's job](https://travis-ci.org/qutebrowser/qutebrowser) list and got scared...)

**Comment by t-wissmann** [comment]
Right! :)
