### ISSUE TITLE
A question about herbstclient foreach and possibly a feature request

### ISSUE THREAD

**Issue by lenneis** [herbstluftwm/herbstluftwm#1472]
Hi,

I use the following hc command to get a listing of all clients, client title string and window class:

`hc foreach CLIENT clients. and , echo CLIENT , sprintf ATTRSTR %c.title CLIENT substitute ATTRVALUE ATTRSTR echo ATTRVALUE , sprintf ATTRSTR %c.class CLIENT substitute ATTRVALUE ATTRSTR echo ATTRVALUE
`
The idea is to get all necessary client info for subsequent use in scripting. More fields will be necessary, like the tag and so on, but hopefully the idea is clear.

This command looks a bit daunting to me, so my question is, is there a better way? I was hoping to get it all into a single sprintf, but no joy so far. I tried this:

`hc foreach CLIENT clients. and , echo CLIENT , sprintf STR %s CLIENT.title echo STR`

But that only gives me the window ids and an error "sprintf: No such object CLIENT".

Now, a much nicer way would be to get all the information from the object tree in one request in machine readable form, something like this:

`hc object_tree_attr_json`

That could return the object tree plus attributes in JSON format for easy parsing. Bonus would be a parameter to only get a subtree or a set of subtrees. One would have to come up with a solution for circular structures, for instance by using a unique id for all objects and use that in place of a circular reference. 

best ,

**Comment by t-wissmann** [comment]
Hi, I can understand that the command is daunting, but there is no better way at the moment. It probably makes sense to have a json export option.

**Comment by lenneis** [comment]
Hi Thorsten,

looking forward to a JSON representation of the object tree, whenever you get around to it. In the meantime, I will enjoy herbstluftwm "as is".

**Comment by t-wissmann** [comment]
Can you create a feature request such that I don't forget?

Also, have you seen the [python bindings](https://github.com/herbstluftwm/herbstluftwm/blob/master/python/example.py) for herbstclient?

**Comment by lenneis** [comment]
Just created the feature request. I have looked at the python bindings. Correct me if that is wrong, but dosen't the code call herbstclient for every attribute that is queried?

**Comment by t-wissmann** [comment]
Thanks for creating #1473. Yes, you're right, herbstclient is called for every attribute queried. In most use cases, this is still acceptable in my opinion, but of course not optimal.

**Comment by lenneis** [comment]
OK, I see. It might be nice to have access to hlwm directly via some sort of IPC, bypassing the overhead of calling herbstclient. Maybe JSON-RPC that "mirrors" herbstclient behaviour? That would still make in accessible to all kinds of scripting languages. I would not mind chipping in on that.

**Comment by t-wissmann** [comment]
the ipc/rpc mechanism is already quite modular, the only remaining part is to configure cmake to create a library (i.e. `.so`) for which one can then create bindings in arbitrary languages. Also, any language with X11 bindings can implement the ipc mechanism.

Introducing two kinds of IPC/RPC-systems will just lead to a mess.

**Comment by lenneis** [comment]
OK, I see. Will have a closer look.
