### ISSUE TITLE
[feature request] IPC socket interaction

### ISSUE THREAD

**Issue by suconakh** [herbstluftwm/herbstluftwm#1474]
I made my own custom python script for changing tags that calls the herbstclient to get some information and then calls it again select the tag I need, but I ran into the problem that spawning a new process every time is very CPU intensive. This is not a problem if I call the script once every couple of minutes, but if I hold down the keybinding that calls this script, then the CPU load increases to 100%. Again, it's not a big problem, but it still annoys me a little. So I thought it might be more efficient to use a unix socket or something like that to interact with the herbstluftwm, like i3/sway does, so you don't have to spawn new processes each time?

**Comment by t-wissmann** [comment]
This is a duplicate of https://github.com/herbstluftwm/herbstluftwm/issues/1296 (https://github.com/herbstluftwm/herbstluftwm/issues/1472 might also be related).

**Comment by suconakh** [comment]
Oh, ok. Closing then
