### ISSUE TITLE
Peek application is not transparent, could not record

### ISSUE THREAD

**Issue by 13minutes-yt** [herbstluftwm/herbstluftwm#1507]
I use this very small useful application for recording small gif files. On herbstluftwm, the application by default is floating but the window which should record is not transparent
![image](https://user-images.githubusercontent.com/97451634/182495324-0c3f9fc9-d02e-4848-a201-61f6deee8aa5.png)
xprop result
$ xprop
```
_NET_WM_ICON_GEOMETRY(CARDINAL) = 638, 736, 100, 32
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_FRAME_EXTENTS(CARDINAL) = 4, 4, 4, 4
_NET_WM_DESKTOP(CARDINAL) = 1
HLWM_FLOATING_WINDOW(CARDINAL) = 1
_NET_WM_STATE(ATOM) = 
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x2a0002b
		bitmap id # of mask for icon: 0x2a00032
		window id # of group leader: 0x2a00001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):
	(not shown)
	Icon (48 x 48):
	(not shown)
	Icon (24 x 24):
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 44040201, 44040202
_NET_WM_USER_TIME(CARDINAL) = 262732362
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x2a00008
WM_CLIENT_LEADER(WINDOW): window id # 0x2a00001
_NET_WM_PID(CARDINAL) = 27534
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "dhcppc0"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 339 by 88
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "peek", "Peek"
WM_ICON_NAME(STRING) = "Peek"
_NET_WM_ICON_NAME(UTF8_STRING) = "Peek"
WM_NAME(STRING) = "Peek"
_NET_WM_NAME(UTF8_STRING) = "Peek"
```
Using herbstluftwm on Artix linux

**Comment by kriansa** [comment]
You can make any floating window tile by just calling `set_attr clients.focus.floating toggle` - then you can start recording and cycle to the window you want

The default keybinding for that is [`$Mod-Shift-f`](https://github.com/herbstluftwm/herbstluftwm/blob/master/share/autostart#L87)

**Comment by 13minutes-yt** [comment]
Just found an answer in Peek readme.
https://github.com/phw/peek/blob/fa271cfc7e0b53e5ab9c3c7d138757cc682e1de8/README.md#on-i3-the-recording-area-is-all-black-how-can-i-record-anything
I used picom and it worked.I am just new to tiling window manager. It will be good for any newbie like me looking for a solution..

**Comment by t-wissmann** [comment]
Also, you should disable the decorations (`hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle` in the default config) such that you can click in the area that you record.
