### ISSUE TITLE
Floating windows are always on top

### ISSUE THREAD

**Issue by jinithin** [herbstluftwm/herbstluftwm#1509]
Having some issues figuring out if floating windows are in the same "stack" as the tiled one.
Is it possible to make floating windows (`floating=on floatplacement=center`) cycle through alt-tab like the tiled ones?
Neither `cycle` or `cycle_all` seems to make them change place in the stack.

Right now in my configuration, floating windows are always on top. 
This makes them a bit of a pain to manage when you've got multiple windows on the same workspace.

Example:
![2022-08-05_21-34_1](https://user-images.githubusercontent.com/13984685/183148493-daae2d45-c1b9-444d-9e97-de84a0acdc8e.png)
![2022-08-05_21-34](https://user-images.githubusercontent.com/13984685/183148499-883d2f3e-c825-4f17-abc3-d4164de9f85c.png)

**Comment by kriansa** [comment]
Yes, floating windows are on a layer above and I don't think you can disable that. The only thing that can be on top of a floating window is another floating window -- and you can sort of control that behavior with `raise_on_click` and `raise_on_focus`.

You can try making these windows `pseudotile` which will make them occupy only the space needed but still be tiled so you can move other windows in front -- there's a shortcut for that in the default config which is `$mod-p`.

I personally float only windows that will be closed quickly, such as alert messages, popups, calculator, etc. If I want them around it's more interesting to tile or pseudotile so I can cycle and toggle layouts more easily.

Also, `cycle` _should_ work among floating windows as well, but they will be selected last.

**Comment by t-wissmann** [comment]
As kriansa already wrote, all floating windows are always above all tiling windows. If you want hide a particular floating window, you can minimize it. The keybindings in the default autostart for these are:
```
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
```
The first keybinding minimizes the focused window, and the second keybinding brings back the most recently minimized window (i.e. a lifo=stack order). If you want a fifo-order, you can replace `last-minimized` with `longest-minimized`.
Also, you can use any window selection utility (like rofi) or taskbar to raise minimized windows again.

I think the effect is almost the same as having floating windows below tiled windows, with the only difference that `cycle_all` does not traverse minimized windows. Also, minimization has the advantage that you don't see them behind semi-transparent tiled terminal windows :)

**Comment by jinithin** [comment]
Thank you both so much for clarifying. I'll create some keybinds for minimizing/raising instead.
