### ISSUE TITLE
Running old HLWM on ubuntu 20/ dependencies

### ISSUE THREAD

**Issue by 13minutes-yt** [herbstluftwm/herbstluftwm#1510]
I am currently running HLWM on fedora and arch with no problems and enjoying it. I tried to install it on `ubuntu 20`. The version I got through apt is` 0.7.2` which lacks a lot of features. Ubuntu 20 latest `glibc` is 2.31 while HLWM needs 2.34. using the binaries from arch gave the glibc warning. Any suggestions. (Installing from sources seems a little bit complicated)

**Comment by t-wissmann** [comment]
The herbstluftwm source does not depend on a particular glibc version, so you should consider building it from source. Hlwm's [continous integration](https://github.com/herbstluftwm/herbstluftwm/blob/master/.github/workflows/hlwm.yml) even verifies that hlwm still builds on ubuntu 14.04. The following commands should be sufficient to build it:
```bash
mkdir build && cd build
cmake ..
make
# and then maybe: sudo make install
```
If you lack the build requirements on your old ubuntu, you might try to build static binaries of `herbstluftwm`/`herbstclient` on a currnet ubuntu system (from source again) and then copy them over.

**Comment by 13minutes-yt** [comment]
I don't understand why ubuntu kept herbstluftwm at a very old version. I have built it on a VM and copied the binaries to my system. It worked but  spend some time to find the dependencies to use for building so here they are for `Ubuntu 20`.

```
`sudo apt install cmake git g++  `

`sudo apt install pkg-config libx11-dev libxrandr-dev libxinerama-dev libxfixes-dev libxft-dev libxrender-dev libfreetype-dev`
`
sudo apt install asciidoc`

git clone https://github.com/herbstluftwm/herbstluftwm.git
cd herbstluftwm
mkdir build && cd build
cmake ..
make
# and then maybe: sudo make install DESTDIR=~/hlwm-bin
```



asciidoc needs a lot of dependencies
 I tried apt --no-install-recommends asciidoc xsltproc docbook-xsl . still got asciidoc errors while performing make.

**Comment by t-wissmann** [comment]
If you don't want to install asciidoc, you can take the source [tarball from the homepage](https://herbstluftwm.org/download.html), which does not require asciidoc (man pages and html doc is pre-built).

You can also just run
```
make herbstluftwm herbstclient
```
to just build the main binaries (i.e. without the doc). Also, you can disable the `WITH_DOCUMENTATION` build flag of cmake:
```
cmake -DWITH_DOCUMENTATION=NO ..
```

**Comment by 13minutes-yt** [comment]
Thanks for your help. Well rounded answer. 👍
