### ISSUE TITLE
option to make `smart_window_surroundings` only hide if there is only one window on a tag

### ISSUE THREAD

**Issue by B4rc1** [herbstluftwm/herbstluftwm#1530]
I often find myself in the situation that I have frames with just one window because I want different sizes for them (think of a small terminal under your text editor). The only way to resize windows independently is to use frames.

The problem is, that I find it unacceptable to have just one window on my monitor AND window borders as they serve no purpose. This is what the `smart_window_surroundings` solves, although it also hides window borders in a frame with just one window.

Keeping the frame borders always on or making them look the same as the active window border is not an option since then you would get double borders, once for the frame and a second time for a window in case you have more than one window in a farme.

I was able to produce the desired effect in a fairly simple bash script, but IMO this is so fundamental, it should be an option in the WM itself.

This could be implemented much like the recent `show_frame_decorations` option with multiple values indicating different desired behaviours. Something like
- `off` for  the current `smart_window_surroundings off`
- `tag` for when the borders should be hidden when there is only one window in the current tag
- `frame` for when the borders should be hidden when there is only one window in a frame (the current `smart_window_surroundings on`)

The bash script I was talking about:
```bash
#!/usr/bin/env bash

herbstclient watch tags.focus.client_count

herbstclient --idle attribute_changed tags.focus.client_count "\d*" 1 | while read event; do
  herbstclient set smart_window_surroundings on
  # echo "toggeling window surroundings off"
done &

herbstclient --idle attribute_changed tags.focus.client_count "\d*" "[^1]" | while read event; do
  herbstclient set smart_window_surroundings off
  # echo "toggeling window surroundings on"
done &
```

**Comment by bileslav** [comment]
@B4rc1, thank you very much for your input. I was able to build a perfect solution (I believe) based on it. Yes, it would be great to have this as an option in the WM.

I found it's better to use `tags.focus.frame_count` instead of `tags.focus.client_count`. Using `tags.focus.client_count` here somewhat breaks herbstluftwm concepts. For example, that makes `theme.minimal` to be nonsense. Another issue I found: floating modals. Think of "Save Page As..." in Firefox. When using your solution, frame decorations will blink when such windows opened/closed.

My solution, batteries included:

1. Put the following in, e.g., `~/.config/herbstluftwm/settings-sws`:

```sh
#!/usr/bin/env sh

set -eu

hc() {
	herbstclient "$@"
}

sws() {
	hc set smart_window_surroundings "$@"
}

readonly attr=tags.focus.frame_count

if hc attr $attr | grep -q 1; then
	sws on
else
	sws off
fi

pkill -f $attr || true

hc watch $attr
hc -i attribute_changed $attr | while read -r event; do
	if echo "$event" | cut -f 4 | grep -q 1; then
		sws on
	else
		sws off
	fi
done
```

2. Make it executable:

```sh
chmod +x ~/.config/herbstluftwm/settings-sws
```

3. Run it somewhere in `autostart`:

```sh
~/.config/herbstluftwm/settings-sws &
```

I actually run it from another script called `settings`. Probably more sane way is to use user service manager, but that currently is too advanced for me, and out of scope.

WM reloading will not spam process table thanks to the `pkill` call.

**Comment by bileslav** [comment]
Just in case, I want to attract attention to this issue: @t-wissmann

**Comment by B4rc1** [comment]
@bileslav Thats awesome, thanks for sharing! Your solution is indeed way more robust than mine solves the problems with floating windows. I will test it with my second monitor if I have access to it again.
One small thing tho, I made the pkill call way more specific since if a window (e.g. firefox) has `tags.focus.frame_count` in the title it will get killed. Although I might just be paranoid, this is my pkill call, works flawlessly for me: `pkill -f "herbstclient -i attribute_changed $attribute" || true`

**Comment by bileslav** [comment]
@B4rc1, thank you! Corrected the `pkill` line.

**Comment by t-wissmann** [comment]
If someone wants to implement a better solution, I'm welcoming PRs.

**Comment by t-wissmann** [comment]
If someone wants to implement a better solution, I'm welcoming PRs.

I leave a few comments / implementation steps here; either for some volunteer or my future self:

* Create a new attribute `them.when_window_minimal` (in `theme.h`) whose type is a new `enum class` (similar to `TitleWhen`).
* This `enum class` should have entries named along the lines of `never`, `only_window_in_frame`, `only_window_and_only_frame`
* All uses of the old `smart_window_surroundings` should now be replaced by the new theme setting.
* The `smart_window_surroundings` attribute (in `settings.h`) and should still mirror the value of`them.when_window_minimal`. This can be done by mutually connecting their change-signals (similar to how it was done for `always_show_frame` in `settings.cpp`).
* The documentation needs to be updated (similar to `always_show_frame` in `settings.cpp`)
* New entires in `NEWS` and `MIGRATION` need to be added
* A few test-cases in `test_settings.py` should verify that the connection between the old and the new attribute works as expected

**Comment by bileslav** [comment]
@t-wissmann, I haven't touched C++ in about 7–8 years and have almost no such experience with git(hub), but *I think* I can do it. If I understand correctly, the only thing stopping me is that I have absolutely no idea how to access the theme attributes from `FrameLeaf::computeLayout()`, which, as I see, is where the actual implementation of `smart_window_surroundings` is located.

**Comment by t-wissmann** [comment]
Hi @bileslav: good catch! I didn't think of this. Then, it might be easier to put `when_window_minimal` in `settings` again.
