### ISSUE TITLE
Numpad keys binding ?

### ISSUE THREAD

**Issue by EtienneProthon** [herbstluftwm/herbstluftwm#1532]
I have an Azerty keyboard so it break the tags behavior because you always need to press shift to be able to get the number, if you don't you get the special charaters. Hopefully i have numpad but i don't know how to map it. I check i3 and tried `$Mod+KP_1` but it doesn't work. Do you have any idea for this bindings ?

**Comment by olaf-rogalsky** [comment]
Depending on the Numlock modifier X11 sends one or the other of the following keysym pairs:

KP_0   <->   KP_Insert
KP_1   <->   KP_End
KP_2   <->   KP_Down
KP_3   <->   KP_Next
KP_4   <->   KP_Left
KP_5   <->   KP_Begin
KP_6   <->   KP_Right
KP_7   <->   KP_Home
KP_8   <->   KP_Up
KP_9   <->   KP_Prior

Just bind to both of them.

**Comment by EtienneProthon** [comment]
Ok thanks for the information i will close the issue.
