### ISSUE TITLE
How do I use conky/any desktop widgets?

### ISSUE THREAD

**Issue by 5271** [herbstluftwm/herbstluftwm#1533]
I've been trying to find some desktop widgets program and I found Conky which seems to be the most popular although when I run it (with default configs) it looks like this
![image](https://user-images.githubusercontent.com/46242934/203275205-5bf073a0-52e1-43b7-94a4-e1ac2cb600dd.png)
I tried changing rules of the window with `herbstclient rule`. I changed every single rule, after every change I restarted conky and it never did anything.
How can I fix it? Or maybe is there some alternative to conky that works better with herbstluft?

**Comment by 13minutes-yt** [comment]
just try to use the following settings in .cokyrc
```
own_window yes
own_window_colour 141414
own_window_class Conky
own_window_type override
own_window_transparent no
```

**Comment by 5271** [comment]
Oh that actually fixed it. Thanks! ^^
But also, the config syntax has changed and for the current syntax it looks like this
```
own_window=true,
own_window_class="Conky"
own_window_type="override",
own_window_transparent=false,
```
