### ISSUE TITLE
rule to close window

### ISSUE THREAD

**Issue by fdietze** [herbstluftwm/herbstluftwm#1536]
I'd like to write a rule which automatically closes annoying popups. I have a rule to detect my popup, but I didn't find a corresponding consequence in the docs. Am I missing something?

**Comment by Wasja7** [comment]
You could create a rule with a custom hook like this `herbstclient rule <conditions> hook=close-hook` and then have this script running:
```
#!/usr/bin/env bash
herbstclient -il rule close-hook | while read win_id
do
    herbstclient close $win_id
done
```

**Comment by fdietze** [comment]
Thank you!

I execute it directly in my `autostart`:
```bash
herbstclient -il rule close-hook | while read win_id
do
    herbstclient close $win_id
done &
```
