### ISSUE TITLE
q3terminal script does not show an empty frame

### ISSUE THREAD

**Issue by jeromg** [herbstluftwm/herbstluftwm#1548]
Hi there,

Apologies in advance as I'm new to herbstluftwm (just used it a bit a few years back). I'm trying to use the q3terminal.sh script but I can't see the frame that is created when toggling the scratchpad on.

I expected an empty frame to be visible. I initially thought it was not working at all, but after some research, I realized the empty frame is created but is just not visible.

Is it the expected behavior or something in my setup which conflicts with it?

Thanks in advance for your help.

Cheers,

Jerome

**Comment by shvmsaini** [comment]
Maybe your `smart_frame_surroundings`  setting is turned on which doesn't show frame if there's only one

**Comment by jeromg** [comment]
Thanks @shvmsaini for the suggestion, I already have explicitly set `smart_frame_surroundings` and `smart_window_surroundings` to `false`

**Comment by shvmsaini** [comment]
It could be an opacity or width issue as well, also check your `show_frame_decorations`  setting.

**Comment by jeromg** [comment]
Thanks @shvmsaini, setting `show_frame_decorations if_empty` did the trick!
