### ISSUE TITLE
Move client to tag?

### ISSUE THREAD

**Issue by eirenicon** [herbstluftwm/herbstluftwm#1555]
I have been unable to find a method  by which to move an active window to another (a different)  tag. In other windows managers I tend to use MOD4+Shift+<tag#> to accomplish that function (dwm,bspwm,i3, etc.).  Is there something similar available in hlwm?

**Comment by t-wissmann** [comment]
The hlwm command for this is called `move_index` and the default keybind for it is as you metioned (MOD4+Shift+<tag#>), see [the default autostart](https://github.com/herbstluftwm/herbstluftwm/blob/master/share/autostart#L75).

**Comment by eirenicon** [comment]
It turns out my problem was an error in my autostart... here's what fixed it for me (the repaired code)

########### Tags/ Workspaces & Set Keys for accessing Tags/Workspaces
# Names to Display on Menu...
tag_names=(           ) 
```
# Qwerty Keyboard Settings
tag_keys=( 1 2 3 4 5 6 7 8 9 0 )
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
```
