### ISSUE TITLE
Emacs does not show tabs in initial frame

### ISSUE THREAD

**Issue by smartmic** [herbstluftwm/herbstluftwm#1558]
I am not sure if this a herbstluftwm bug (or expected behaviour) and where to look into the root cause (herbstluftwm?, X11?, GTK3?, Emacs?)

I use Emacs 29.1 with [Tab Bars](https://www.gnu.org/software/emacs/manual/html_node/emacs/Tab-Bars.html) and also in [`(desktop-save-mode)`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Saving-Emacs-Sessions.html#Saving-Emacs-Sessions). Normally, Emacs will restore the window configuration including any open tabs from a desktop file. The thing is: the latter part only works if I start Emacs with `emacs --maximized` or if I start from floating mode (I have not tried other workarounds).

If I start Emacs "normally" without any display options in tiling mode, the tabs are not shown in the initially created Emacs frame/window. Only if I switch to another tag or cycle layout, the tabs appear again.

This is not really a serious thing as there are easy workarounds, I was just really confused while setting up my Emacs and it took a while until I could reproduce the issue.

**Comment by BBoal** [comment]
Hi there!
I use Herbstluftwm and Gnu Emacs 30 on a daily basis and never had an issue similar to your description. In the attempt of reproduce your "error" I tried desktop-mode with tab-bar after setting up some personal preferences and evaluated (desktop-save-mode t) and (tab-bar-mode t). Both had the desired behavior and were restored after exiting Gnu Emacs. Perhaps if you share how you load your setup more assistance can be given.

Best regards,
BB

**Comment by BBoal** [comment]
I finally was able to reproduce this and found a solution.
I don't think it has anything to do with Herbstluftwm.

Try the following, in `early-init.el` add:

`(modify-all-frames-parameters '((tab-bar-lines . 1)))`

It should work as intended.

**Comment by smartmic** [comment]
Yes, that fixes the issue, many thanks, @BBoal !

I agree, this is probably completely unrelated to Herbstluftwm, but hey, here are great people with Emacs voodoo magic, so it was worth it anyway :)

**Comment by BBoal** [comment]
You're welcome @smartmic ! Glad I could help with a little of my hocus pocus, ahahah
