### ISSUE TITLE
Moving tabbed windows within the tabbed_max layout

### ISSUE THREAD

**Issue by JosephFerano** [herbstluftwm/herbstluftwm#1559]
Hello, thank you for the package, it works great! I recently started using HLWM and I am using the tabbed_max layout extensively, but one think I tried to do was moving the windows so I can manually control the tab/cycling order. The only thing I have found that works is to move the window to a different split, then go back and focus on the window that I want to come before the target, then move back to the new split and move the target back into the tabs. Not terrible until I want it to be the first tab, then it gets more involved. Anyway to achieve this behavior?

**Comment by t-wissmann** [comment]
There is the `--level=...` parameter of the `shift` command for this. The documentation for it is in the section of the `focus` command. Also, the tab completion lists the options:
```
hc shift --level=
--level=all       --level=frame     --level=tabs      --level=visible
```
