### ISSUE TITLE
Question: Is there a way to assign a program to a certain tag ONLY on startup?

### ISSUE THREAD

**Issue by dylanpjx** [herbstluftwm/herbstluftwm#1574]
For instance, on startup, I'd like to send all Firefox windows to tag 2. Rules work but I'd prefer a solution that doesn't persist after startup.

**Comment by yousufinternet** [comment]
would the --once flag work?

**Comment by dylanpjx** [comment]
Hey thanks, I missed that!

**Comment by dylanpjx** [comment]
For others that chance upon this thread, the better way would probably be to use `maxage` if you need to set multiple windows only on startup
