### ISSUE TITLE
Previously transparent frames are rendered with incorrect size when `frame_bg_transparent=off`

### ISSUE THREAD

**Issue by Storchschnabel** [herbstluftwm/herbstluftwm#1576]
#### Steps to reproduce:
```
Xephyr :1 -screen 1920x1080 -resizeable &
export DISPLAY=:1
herbstluftwm &
herbstclient set frame_bg_transparent off 
herbstclient split right 0.5 
xclock &
sleep 1
herbstclient resize left +0.05
herbstclient focus right
killall xclock
herbstclient remove
```
#### Observed behaviour:
There is only one frame (`herbstclient dump` prints `(clients max:0)`), but it is only filled about half.
#### Expected behaviour:
The frame should be filled fully.

**Comment by t-wissmann** [comment]
Thanks for the very precise description, I can reproduce the issue!
For the reproduction of this issue with the default autostart, I also had to set
```
hc set always_show_frame on
```
