### ISSUE TITLE
(Virtual) desktop size not adjusting upon xrandr resolution change

### ISSUE THREAD

**Issue by SuperFluffy** [herbstluftwm/herbstluftwm#194]
My system starts in the wrong resolution, and I manually adjust it after start. Now it appears as if herbstluftwm still thinks the old resolution is active, and only tiles windows on the upper left rectangle that represented the screen before the resolution change.

If I switch to floating mode, I can move windows into the new extra area. But in tiling mode, only the upper left rectangle is considered. To demonstrate, see the images below.

This is floating, I can reach all areas: https://imgur.com/8DhtpMq
This is tiling, you can see that a new split is in the bottom right of the reduced area: https://imgur.com/kGKROyE
This is "fullscreen", again only the reduced are is considered: https://imgur.com/GHn37x8

**Comment by t-wissmann** [comment]
Simply run
```
herbstclient detect_monitors
```

**Comment by SuperFluffy** [comment]
I think that did it, at least for going from 5120x2160 -> 3840x2160 (different monitor after suspend). So I bet going 3440x1440 -> 5120x2160 will no problem.

Thank you, @t-wissmann.
