### ISSUE TITLE
Frame objects

### ISSUE THREAD

**Issue by The-Compiler** [herbstluftwm/herbstluftwm#2]
I've been working on frame objects for the object tree - we merged the code at 30c3 but it turned out there was some bug.

WIP code:http://git.the-compiler.org/herbstluftwm/log/?h=frame_objects

Bug:

When splitting a frame many times there was a segfault.

The code also should be rebased on master.

**Comment by t-wissmann** [comment]
Is there any feature of your frame objects patch that I didn't implement yet? If not, we can close this :-)

**Comment by t-wissmann** [comment]
Looks as if we could close it :)
