### ISSUE TITLE
Compile warnings with -Wextra

### ISSUE THREAD

**Issue by The-Compiler** [herbstluftwm/herbstluftwm#27]
Compiling with `-Wextra` gives us some additional warnings - maybe we should fix/workaround them and then compile using `-Wextra` for additional warnings? I caught some bugs in the wild in some of my programs this way.

Also, `-Wextra` still doesn't mean "all warnings"...

**Comment by t-wissmann** [comment]
We even have `-Wall -Wextra` now.
