### ISSUE TITLE
Addressing of monitor by negative relative index doesn't wrap around 0

### ISSUE THREAD

**Issue by mkoskar** [herbstluftwm/herbstluftwm#36]
Example:

```
1) hc keybind $Mod-e focus_monitor +1
2) hc keybind $Mod-w focus_monitor -1
```

In case `1)` when current monitor is the last one, `+1` will match monitor with index `0` (wraps around end of the "list"). In case `2)` when current monitor is the first one (`0`), `-1` would **not** wrap around to match last monitor as one would expect from consistency point of view.

**Comment by t-wissmann** [comment]
Sorry, for not noticing this message for so long...

Here, `focus_monitor -1` wraps around the 0. Do you still experience this issue?

**Comment by mkoskar** [comment]
I can't test this right now since I don't have a multi-monitor setup right now (just laptop). I suppose it's safe to close this if you say it's working for you. I will re-check sometime in future and possibly reopen this then. Thanks!

**Comment by t-wissmann** [comment]
Don't hurry. Anyway, I recommend you to use the `toggledualhead.sh` script. It splits a monitor into two monitors side by side; i.e. you can have a multimonitor setup on your laptop screen. (I have it bound to <kbd>Mod-]</kbd>)
