### ISSUE TITLE
Using frame index in herbstclient

### ISSUE THREAD

**Issue by dkrikun** [herbstluftwm/herbstluftwm#375]
It is explained in the manual how a frame has an index assigned to it.
However, there are few commands that accept frame index as a way to address a frame.

In particular, I would like to be able to:
1. Get focused frame index (without using '@').
2. Focus first window in a frame by index.
3. Swap frames by index.
4. Etc etc...

Are the above possible?

**Comment by t-wissmann** [comment]
The above aren't possible directly. Have you looked at the `load` command? It allows you to modify the layout (swapping frames around, etc).

Am I assuming it correctly that you need this in scripts? Maybe we'll find another way to accomplish it for the time being.

**Comment by dkrikun** [comment]
I thought I could use it for #376

**Comment by t-wissmann** [comment]
Alright. Then let's try to solve your actual problem.
