### ISSUE TITLE
Getting the Correct Root WID with HLWM (v0.7.0)

### ISSUE THREAD

**Issue by terminalforlife** [herbstluftwm/herbstluftwm#389]
Hi,

I'm experimenting with having a video (via mpv) play on the root window, but the best I can get, is it playing (correctly) over the current terminal window into which I enter the following command:

`mpv --wid="$(xprop -root _NET_ACTIVE_WINDOW | cut -d "#" -f 2)" /video/file.mp4`

Using 0 as the WID, as suggested in the mpv man page, also doesn't work; it gets audio, but no video at all.

Is this just me misunderstanding window IDs in Linux, or is it just something for which HLWM isn't suited?

I use feh on login (successfully) to set the background as an image, if that helps at all.

Thank you for your time.

PS,
I'm using an Ubuntu 16.04.6 setup.

**Comment by t-wissmann** [comment]
Here, playing a video on the root window via mpv only works if no composite manager (compton or xcompmgr) is running. If I run compton, then I get the same effect as you: audio but not video.


Regarding the question in the title:

The window id of the root window is not 0, but mpv interpretes 0 as the root window. If you want to find out the actual window id of the root window, you can use `xwininfo`:
```
xwininfo -root|sed -n 's,.*Window id: \(0x[^ ]*\).*$,\1,p'
```
i.e. the following two commands are equivalent:
```
mpv --wid=0   /video/file.mp4
# and
mpv --wid=$(xwininfo -root|sed -n 's,.*Window id: \(0x[^ ]*\).*$,\1,p') /video/file.mp4
```

I guess that you want to run a video and still see it through semitramsparent windows, right? If yes, you could try running mpv as an unmanaged window with the full size of your screen and below all windows. Currently I don't know how to lower the mpv window, but the worst that can happen is that we need a dedicated 10-line programe in C.

**Comment by terminalforlife** [comment]
Thank you for the speedy reply.

I'm aware of the 0 with mpv thing. However, this whole time what I thought was the root WID (based on what xprop told me) apparently wasn't. Thank you so much for clarifying. I find it weird that `xprop -root` and `xwininfo -root` show a different WID.

Shame about compton. I've always used compton, so it didn't occur to me to be the issue. I wonder now if there's a workaround for this issue, but realise this is now a compton issue, and no longer a HLWM issue.

Thanks for the idea of having the mpv window set to unmanaged.
