### ISSUE TITLE
Move coding style CI checks to separate build job

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#399]
cf. #395:

There is something I really dislike about our current ci setup, namely:

_If there is some non-entirely-standard whitespace placement in the test-system's python script, then not a single testcase is run on the actual herbstluftwm system_

We should really get rid of this by moving all the code-style checks (whitespace in py, order of includes, usage of using std::… to a spearate build job.

When creating a new PR, in a new branch, it's simply frustrating when the CI did not run any test cases because the includes weren't ordered alphabetically...

**Comment by blarz** [comment]
This issue can be closed, right?

**Comment by t-wissmann** [comment]
Right! Thanks for the reminder.
