### ISSUE TITLE
CircleCI integration

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#401]
I've received a request by @dnnr to include CircleCI in herbstluftwm. I didn't really get what circle ci is. Do I understand https://circleci.com/docs/2.0/about-circleci/#section=welcome correctly, that circleci is an alternative to travis? (which we are using currently).

**Comment by dnnr** [comment]
This was by mistake, sorry. Feel free to deny the request.

You're right about CircleCI, and it's relevant to our interests, in my opinion.
See also my previous comment on it: https://github.com/herbstluftwm/herbstluftwm/pull/358#issuecomment-468011201
