### ISSUE TITLE
Frame layout confuses me

### ISSUE THREAD

**Issue by dkrikun** [herbstluftwm/herbstluftwm#403]
I have the following UX problem:
1. I open a single window in a frame
2. Add a second one, in a vertical layout (my default)
3. At some time, I switch to max. layout to work with one of the windows, lets say vim.
4. Later on I want to open a terminal in the same frame, so I hit $Mod+d (my binding for it) but, alas, nothing happens. I hit $Mod+d few more times..
5. Eventually, I remember or discover that in fact, the frame is in the max. layout, and not in the vertical one. By then I have opened quite a few terminals))

If only there was a sign to the frame that it is in the max. layout.
I could probably hack something with chaining and e.g. frame color, to designate the frame layout..

**Comment by t-wissmann** [comment]
I think the easiest is to always focus new windows, you can do this by writing the following at the beginning of your rules section in the autostart:
```
hc unrule -F
hc rule focus=on
# the other rules...
```
Please ensure that there is no `unrule` call afterwards in the autostart.

**Comment by dkrikun** [comment]
Focusing new window has 2 problems:
1. If the existing window had a terminal window, starting one another won't be very clear. It could be mistaken as clear screen.
2. In general, I do not like focusing new windows by default, because sometimes I run a slow-starting application, e.g. chrome, while it is starting, I switch to doing something else. I do not like the slow application stealing focus from me while I am doing the other thing.

**Comment by dkrikun** [comment]
It would be great to have an option for a per-frame status bar, customizable with e.g. current layout, number of windows in the frame etc.
Having a "tabbed" layout for frames would be great too.

**Comment by t-wissmann** [comment]
> 1. If the existing window had a terminal window, starting one another won't be very clear. It could be mistaken as clear screen.

So you're accidentally open a new terminal window with out noticing it and then you mistakenly think that you have triggered a clear screen in your existing terminal?

> 2. In general, I do not like focusing new windows by default, because sometimes I run a slow-starting application, e.g. chrome, while it is starting, I switch to doing something else. I do not like the slow application stealing focus from me while I am doing the other thing.

Maybe the following solves the issue for you: If you use something like rofi for starting applications, you can configure the following:
```
rofi.run-command:                    /usr/share/doc/herbstluftwm/examples/exec_on_tag.sh "" {cmd}
```
With this, the applications appear on the tag (i.e. virtual desktop) where you have started them. This means that you can go to tag *A* and start chrome, switch to tag *B*, and when chrome appears, it is moved directly to tag *B*. 

Something like proper window decorations allowing something like a tabbed layout is on the must-have feature list!

**Comment by dkrikun** [comment]
Its not that I immediately forgot what I have done 1 second ago))
But yes, I might leave a frame with a clear terminal to work on something else or whatever.
Great to hear about the decorations.

**Comment by syslino** [comment]
I dont like the idea of window decorations. Or tabs. I enjoy the simplicity as it is now. Most of this can be achieved with writing custom scripts, thats why I chose this wonderful WM. It's truly light - If I miss something, I do it myself. But great that development is going on. I appreciate what you guys are doing. Thank you for this software so far! :+1:

**Comment by t-wissmann** [comment]
I propose to close this, because I think some questions raised here have been answers and the only remaining thing is the feature request for window decorations, which (in the meantime) has an own issue: https://github.com/herbstluftwm/herbstluftwm/issues/567
