### ISSUE TITLE
Add an option to close all open windows

### ISSUE THREAD

**Issue by meskarune** [herbstluftwm/herbstluftwm#45]
I would like to have an option added to herbstclient to close all open windows. Something like

```
herbstclient close all
```

This would make it easy to gracefully close all windows before issuing a reboot or shutdown command.

**Comment by razzintown** [comment]
I would also like to have this.

**Comment by sdothum** [comment]
It is easily scriptable enough (the beauty of herbstluftwm)..

<code>for i in $(herbstclient attr clients | grep '0x');do</code>
<code>  herbstclient close $i</code>
<code>done</code>

**Comment by ypnos** [comment]
I'm not even sure if this is what the user intends. For example, if you have multiple browser windows open, the will get closed one by one. When the browser is configured to recover its session on startup, it will only recover the window that was closed last (at random).

Btw there is also `xkill -all`

**Comment by t-wissmann** [comment]
I don't think that the window manager can prevent this browser problem. And the `hc close all` just does this for loop internally. So I don't see what @ypnos means.

**Comment by ypnos** [comment]
I mean that the window manager cannot solve the problem of "proper session shutdown" in a satisfying. Therefore I would refrain from implementing a "close all" functionality, given it would not add anything to the already available options for plainly killing all windows (shell for-loop, xkill, `xdotool search --maxdepth 1 "" windowkill %@` etc).

**Comment by meskarune** [comment]
I'm using this currently but it requires wmctrl:

   wmctrl -l -p | awk '{print $3}' | while read PID; do kill -15 $PID; done

kill -15 tells a window to gracefully stop it is different from just killing processes like with kill all. I'm not sure how other window managers handle gracefully shutting down all apps before quitting. It was an annoyance I had when doing "herbstlufclient quit" because I would lose data or app state. If it would be useful, I could try write a patch myself, but I'm very new to C and not too sure where to even begin.

**Comment by t-wissmann** [comment]
I don't know what the general solution of other WMs is, but I guess it's not via the pid because it's not a mandatory to provide the PID information and because the application might run on another host (or user) than the WM and thus can't be `kill`ed by the WM.

One solution would be to provide a minimalistic session manager interface, which iirc can tell applications to safe there state and quit.

To your `kill` vs `kill -15` vs `killall`: it is no difference between those, because signal number `15` denotes `SIGTERM` which is the default signal for `kill` and `killall` (see `man 7 signal` and `man 1 kill killall`). The really bad and ruthless one is `SIGKILL` (number `9`), but it's fortunately not the default. :-)

**Comment by ypnos** [comment]
Unfortunately, there is no general solution and I doubt standalone WMs like blackbox, fluxbox etc. do anything like this at all.

KDE and Gnome have their own mechanisms to save sessions or gracefully quit. In KDE there is even the Activities concept heavily relying on it (you can "pause" activities which gracefully kills all clients in the activity, and they will restore state when restarted).

KDE recently stripped out many core functionalities (like KWindowSystem), and I believe also the activity management is one of them. So it can be used outside KDE but when I went through the cody quickly (researching for this issue) I didn't really find any starting points to how clients are told to quit/save session and restore…

**Comment by t-wissmann** [comment]
There's a `foreach` command in the current git version. For closing all windows, you can run the following slightly complicated command:
```
$ herbstclient foreach C clients. sprintf WINIDATTR '%c.winid' C substitute WINID WINIDATTR echo close WINID
close 0x100000f
close 0x1a00021
close 0x2a000cb
close 0x300000a
close 0x320000d
close 0x360000a
close 0x380000a
close 0x3a0000a
close 0x440000a
close 0x80000a
close 0xc0000a
close 0xe00006
close 0x3a0000a
```
If you really want to use it, you can remove the `echo` from the above command. Unfortunately, the command is issued twice for the focused client (0x3a0000a in the above example), but it shouldn't matter much for `close`.

**Comment by t-wissmann** [comment]
As soon as #1394 is merged, one can solve the duplication issue in two ways: by either `--unique` or `--filter-name='0x.*'`
```
$ herbstclient foreach C --filter-name='0x.*' clients. sprintf WINIDATTR '%c.winid' C substitute WINID WINIDATTR echo close WINID
close 0x240000a                                                                                                                     
close 0x2600006
close 0x280000a
close 0x2a0000a
close 0x2e0000f
close 0x3a0000c
close 0x3e0000a
close 0x400030f
close 0x420000a
close 0x4c0000a
close 0x540000a
close 0x620000a
close 0x6600001
close 0x6e000ca
close 0x700000a
close 0x720000e
```
So I think this issue here can be closed. If I missed anything, please (re-)open this or another one.
