### ISSUE TITLE
Herbstluftwm website link to musca leads to an unrelated site

### ISSUE THREAD

**Issue by davidv171** [herbstluftwm/herbstluftwm#495]
On the website (https://herbstluftwm.org/)

Under the first "chapter", both links to "musca" lead to an unrelated site:

http://aerosuidae.net/

Now I've never heard of musca but the website does not seem like it's related at all to tiling window managers, as the herbstluftwm website suggests.

I could not find a github page or an avenue to report this so I resorted to opening an issue here. Sorry if I broke any rules.

**Comment by t-wissmann** [comment]
There's a backup of the source code at https://github.com/enticeing/musca but I'm not sure whether this is the best resource to link at (but definitely better than the old abandoned url)

**Comment by davidv171** [comment]
You didn't ask but I think just mentioning the legacy wm and what happened to the project should be enough. Don't need to bother with links to potentially modified code.
