### ISSUE TITLE
Clients in frame by index

### ISSUE THREAD

**Issue by BerberBerthold** [herbstluftwm/herbstluftwm#536]
I notice that there is the attribute `curframe_windex` in tags, which makes it possible to get the index of the currently focused client inside its frame.  It isn't possible to get the index within their frames of arbitrary clients, though, which makes the function `focus_nth` kind of hard to make use of.  It would be cool to have this attribute.

One example of a use would be if I wanted to focus on the (i+1)st client in the frame of a known client X, where i is the index of client X within its frame.  I would focus to X and then run focus_nth i+1.

Here is the next problem:  I can't do any other actions by index of the client within a frame other than focusing.  It would be cool to have a "get the client id of the nth client in frame Y" function.

**Comment by t-wissmann** [comment]
Isn't the `cycle` command what you are looking for. You can additionally get the entire frame information by the `dump` command (and after modification you can load it in via the `load` command)

**Comment by BerberBerthold** [comment]
sorry, i don't see how the cycle function would help me.  it just cycles the focus of the clients within a frame (by a number).

let's say i have a client with id X, and a few other clients in the same frame.  now suppose i am currently in a different frame on a client Y, but i want to kill the client that comes 2 delta after client X.

i guess i could just focus client X, then cycle by 2, then kill, cycle back to have X on the top of the frame (in max mode), and then focua back to Y.
it would look ugly because there are some redraws and it just isn't an elegant solution.

it just seems like an "index" attribute is missing

**Comment by t-wissmann** [comment]
If you want to kill client `X` with windowid `W`, you can run the command `close W`

**Comment by BerberBerthold** [comment]
if i know the id of the client, yes.  but not if i don't know the id of a client Y, but only know that th client Y is 2 spots further in the cycle of a frame of a different known client X with window id W, there is no convenient way to get the id of Y (or you tell me how 😁).  i am looking something like `get_attr clients.W.index` which say outputs 2, and then i want to get the id of the 2+2 = 4th index of the frame of X, say that id is Z (so I just found out that Y has id Z), and then i could finally do `close Z` to kill client Y.

**Comment by t-wissmann** [comment]
> if i know the id of the client, yes. but not if i don't know the id of a client Y, but only know that th client Y is 2 spots further in the cycle of a frame of a different known client X with window id W, there is no convenient way to get the id of Y (or you tell me how ).

Can't you simply hit the keybinding for `cycle` twice and then hit the keybinding for close? Everything else seems to be much more complicated...

**Comment by BerberBerthold** [comment]
if i want to write a script that closes the client that is 2 places up within the frame `F ` from a given client `X` (say, because i always know that the client `X` will spawn two new clients after a certain action, and i want to close the second one), then i guess it would be possible to do the following:

1. remember current focused client `Z`
2. switch to frame `F` that `X` is contained in
3. remember the focused client say `Y`
4. focus client `X`
5. cycle twice
6. close that client
7. focus client `Y` again (so that frame `F` has frame `Y` focused again)
8. focus back to client `Z`

this seems like it is more prone to jank than just having:

1. remove client `X+2`

which would be possble if by getting the window index and just adding `2` and then closing it.

**Comment by t-wissmann** [comment]
This "one step" does not take care of the focus and it still requires that you manually enter the window id `X`. And your motivation seems to be something very specific to your setup. I wrote a script for you that does exactly what you want:

```bash
#!/usr/bin/env bash

WINID_X="$1" # expects a window id as the first parameter
# e.g. something like "0x220000a"

DELTA='+2'

# extract the frame description of the frame containing WINID_X.
# the 'mapfile' fills the array variable 'frameclients'
mapfile -t frameclients < <(
    herbstclient complete 1 use |
       while read t ; do
           herbstclient dump "$t" ;
       done |
       grep -oE "[^()]*${WINID_X}[^()]*" | # extract what's between ( and )
       head -n 1 | # only take the first frame
       cut -d' ' -f3-| # remove the 'clients' and sth like 'max:0'
       tr ' ' '\n' # turn words into lines for mapfile
)

# determine the index of the window $WINID_X in its frame:
X_index=''
for i in "${!frameclients[@]}" ; do
    if [[ "${frameclients[$i]}" = "$WINID_X" ]] ; then
        X_index="$i"
    fi
    # debug output:
    #echo "$i = \"${frameclients[$i]}\""
done

if [[ -n "$X_index" ]] ; then
    # if the windowid of $WINID_X has been found, compute the
    # winid of the window that is $DELTA places next to it
    windowcount=${#frameclients[@]}
    TARGET_index=$(((X_index + windowcount + DELTA) % windowcount))
    TARGET_WINID="${frameclients[$TARGET_index]}"
    echo closing "$TARGET_WINID" # Debug output
    # herbstclient close "$TARGET_WINID"
else
    echo "cannot find window $WINID_X in any frame"
fi
```

**Comment by BerberBerthold** [comment]
thank you very much!

**Comment by t-wissmann** [comment]
The script does not need to worry about the focus at all because the layout isn't modified. And you're right, the window that is focused in the frame also stays the same.

I don't know an application of the `focus_nth` command, I don't use it myself. It is also a very specific command indeed.
