### ISSUE TITLE
Spurious focus for client under mouse cursor

### ISSUE THREAD

**Issue by ypnos** [herbstluftwm/herbstluftwm#54]
Whenever the focus is changed, the client under the mouse cursor temporarily gets focus. That is, it is sent focus in and focus out events.

This seems to happen on all focus changes, even if they happen in other frames etc.

It is easy to test this behavior with an application that reacts to focus (e.g. a terminal that changes the cursor shape) or xev.

**Comment by ypnos** [comment]
This also happens when switching away to another tag.

**Comment by ypnos** [comment]
Probably related to this problem and also #33:

Have two frames, one of them empty, the other with one or several clients. Put mouse cursor over one of the clients. Open a client in the previously empty frame without moving the mouse. The new client gets focus. Close new client.

*Expected:* Focus stays in the previously empty frame which is empty again.
*Observed:* Visual feedback (frame/window borders) indicates that the empty frame is focused. However keyboard input is directed to the client under the mouse cursor. The client in question also got a focus in event, but no focus out event.

**Comment by t-wissmann** [comment]
This is a bug about key grabbing and not about the focus change. Create a key binding
```
herbstclient keybind Alt-x true
```
- Create an xterm, but focus something else (another client or an empty frame).
- Place the mouse cursor over it
- Pressing the keybinding makes the cursor flicker.

**Comment by t-wissmann** [comment]
It seems that this is an inherent issue in X, that is also present in other window managers, e.g. fluxbox:

* Open xterm twice in fluxbox
* Focus one xterm, and place the cursor over the other xterm
* Press Alt-Space (default keybinding for the window menu)
* Notice how the cursor flickers

(If you don't want to boot into a fluxbox session, run `Xephyr +extension kb -resizeable :13` from a terminal and `DISPLAY=:13 fluxbox` from another terminal, and you'll have a fluxbox session in a Xephyr/Xnest window).

**Comment by t-wissmann** [comment]
I fear that hlwm can't fix this because it's inherently related to X.
