### ISSUE TITLE
Winterbreeze: Pseudotile rule does not apply to windows with multiple window types

### ISSUE THREAD

**Issue by olmokramer** [herbstluftwm/herbstluftwm#554]
I'm trying out winterbreeze (commit cf7a170c) and most things work just as they did before. The rules I used pre-winterbreeze to make the gpg-agent pinentry window pseudotiled automatically do not work anymore, however. Any one of these rules worked pre-winterbreeze but does not get applied in winterbreeze:

```
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH) focus=on pseudotile=on

herbstclient rule class~'[Pp]inentry' focus=on pseudotile=on
```

The former still does seem to work for some of the windows it should target, such as GIMP's splash window.

Following rule also still works (you can open it via the menu, 'File' -> 'Document Properties...'):

```
herbstclient rule class~'[Ii]nkscape' title~'Document Properties.*' focus=on pseudotile=on
```

**Comment by olmokramer** [comment]
This also appears to happen to qutebrowsers "open file" dialog that opens, for example, when clicking the "Attach files ..." text below these GitHub textboxes. When I noticed this I also tried Chromium's "open file" dialog, and it _does_ get the pseudotile applied.

Upon investigating, I think `xprop` may have revealed (part of) the issue: both the pinentry and qb's "open file" dialog have

```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL
```

while Chromium's "open file" dialog had

```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
```

I tried changing the rule to read like below, but none of the variations worked:

```
windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH).*'

windowtype~'.*_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH).*'

windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH), _NET_WM_WINDOW_TYPE_NORMAL'
```

This does not explain why the `class~'[Pp]inentry'` rule did not work, though, unless the problem is that pseudotiling windows with multiple window types is broken, which appears not to be the case, as `herbstclient pseudotile on` from the terminal does work.

**Comment by t-wissmann** [comment]
Hi, thanks for opening this issue!

I think I have the issue.... but in case I'm not able to fix it, we should do the following:





 I will try to reproduce it in the next days. Here, qutebrowsers open file dialog has
```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
```
Which explains why the issue does not appear here. Can you try some things for me?

Can you please change the rule to 
```
herbstclient rule class~'[Pp]inentry' focus=on pseudotile=on hook=pinentry
```
and then run
```
herbstclient --idle rule pinentry
```
from a terminal and check whether it has some output when you start the gpgagent pinentry?

It will also print the `WINID` of the pinentry window. Can you please run
```
herbstclient attr clients.WINID # with the WINID replaced
```
and paste its output here?

**Comment by t-wissmann** [comment]
As soon as #555 is merged, can you please try again?

**Comment by olmokramer** [comment]
I tried with #555 applied, and that does seem to work! Thanks! Do you still want me to try the steps in your first post? I can do that tonight when I get home.

**Comment by t-wissmann** [comment]
Thanks! You don't need to do the steps above. If I didn't miss anything then this issue is solved. If I missed something, please open it again.
