### ISSUE TITLE
Winterbreeze: monitor=X rule does not raise window if started from other monitor

### ISSUE THREAD

**Issue by olmokramer** [herbstluftwm/herbstluftwm#556]
I've found another rule(set) that used to work pre-winterbreeze but doesn't anymore. I'm on commit [e887b77](https://github.com/herbstluftwm/herbstluftwm/commit/e8887b77eb35ed53a26579ef7a9bc5f0f16a2dd2).

Given the following rules

```
herbstclient rule focus=on
herbstclient rule class~'[Mm]pv' monitor=0
```

When I launch mpv from monitor 0 everything works as expected: the mpv window is on monitor 0 and in the foreground.

When launched from another monitor, though, the window is placed on monitor 0, but it is not raised to the foreground. As soon as I focus monitor 0, it pops to the foreground. Pre-winterbreeze the window would immediately be in the foreground.

I tried to change the second rule to

```
herbstclient rule class~'[Mm]pv' monitor=0 focus=on
```

but that also left the mpv window in the background.

PS I also have `fullscreen = yes` in `~/.config/mpv/mpv.conf`. I tried removing that to see if it had any effect but it didn't. The mpv window was still in the background until I focused the monitor.

PPS My monitor setup is very basic: I have two physycal monitors and one herbstluft monitor per physical monitor, set up with `herbstclient detect_monitors`.

**Comment by t-wissmann** [comment]
Thanks! I can reproduce the bug here.

**Comment by olmokramer** [comment]
Gave 791d0b8a9af125cb8cfa687e94d90eba501da5ca a try and it does seem to work as intended. Thanks for the quick fix!

**Comment by t-wissmann** [comment]
Thanks for your feedback!
