### ISSUE TITLE
Update _NET_WM_DESKTOP atom for all clients when removing a tag

### ISSUE THREAD

**Issue by ctx** [herbstluftwm/herbstluftwm#56]
When you remove a tag, you need to update the _NET_WM_DESKTOP atom for all clients.

* Steps to reproduce this bug:
  * start an EWMH panel like bmpanel2 or lxpanel (or look at the _NET_WM_DESKTOP atoms)
  * create 3 tags with at least one client on the second and third tag (A,B,C)
  * remove the first tag (A)
* What you would expect:
  * the panel shows the clients on the correct tag
* What happens (on the panel):
  * on the first tag (B) there is no client
  * on the second tag (C) you can see the client(s) from the previously second tag (B)
  * the client(s) of the second tag (C) are not shown on any tag

I couldn't find a way to ignore clients on tags with a lower index than the removed one.

This patch fixes the bug for me:

```diff
diff --git a/src/tag.cpp b/src/tag.cpp
index 8869bd0..d731819 100644
--- a/src/tag.cpp
+++ b/src/tag.cpp
@@ -301,6 +301,15 @@ int tag_rename_command(int argc, char** argv, GString* output) {
     return tag_rename(tag, argv[2], output);
 }
 
+static void client_update_tag(void* key, void* client_void, void* data) {
+    (void) key;
+    (void) data;
+    HSClient* client = (HSClient*)client_void;
+    if (client) {
+        ewmh_window_update_tag(client->window, client->tag);
+    }
+}
+
 int tag_remove_command(int argc, char** argv, GString* output) {
     // usage: remove TAG [TARGET]
     // it removes an TAG and moves all its wins to TARGET
@@ -365,6 +374,7 @@ int tag_remove_command(int argc, char** argv, GString* output) {
     ewmh_update_current_desktop();
     ewmh_update_desktops();
     ewmh_update_desktop_names();
+    clientlist_foreach(client_update_tag, NULL);
     tag_set_flags_dirty();
     hook_emit_list("tag_removed", oldname, target->name->str, NULL);
     g_free(oldname)
```

**Comment by t-wissmann** [comment]
Thanks for fixing that! The diff seems fine. Do you want me to commit this with your (real) name and (real) E-Mail or with my name referencing your nick in the commit message?

**Comment by ctx** [comment]
I use ctx <ctroxler@gmail.com> for commits, but do as you wish.
