### ISSUE TITLE
Window decorations

### ISSUE THREAD

**Issue by Nairou** [herbstluftwm/herbstluftwm#567]
Are there any plans to add window decorations at some point? What kind of effort would that take, would it require a big shift from herbstluftwm's goals?

This is the only thing I feel herbstluftwm is missing. It can be a little frustrating not knowing whether an app is open, or how many windows are hiding below the ones you can see, just from looking at the screen. Something like titlebar tabs across the top of each frame would be nice.

**Comment by t-wissmann** [comment]
Information texts in the window decorations are definitely planned; and they are needed especially for the max layout.

**Comment by blarz** [comment]
Basic window title support is in since #1090 and there is an ongoing discussion in #1097, too.

**Comment by bew** [comment]
Does the ongoing work on window decorations will make possible to have frame decorations too? (without window decorations for example)

**Comment by t-wissmann** [comment]
> Does the ongoing work on window decorations will make possible to have frame decorations too? (without window decorations for example)

Not sure whether it will happen. But if I understood it correctly, this has also been requested in https://github.com/herbstluftwm/herbstluftwm/issues/1097#issuecomment-754020064 and if many people want it, it's worth the implementation effort.

**Comment by t-wissmann** [comment]
I think all suggestions from this thread are either implemented already (titlebars and tabs #1381) or were mentioned in the discussion of #1097. So let's close this.
