### ISSUE TITLE
Line in share/autostart causes artifacts with xcompmgr

### ISSUE THREAD

**Issue by astier** [herbstluftwm/herbstluftwm#570]
The FAQ says that its caused by the setting `frame_bg_transparent`. This setting however is still in the example autostart file in the share folder. I think this line should be removed from there.

https://github.com/herbstluftwm/herbstluftwm/blob/b6925946bed73b7b9a74d84e5ed47209ee669eca/share/autostart#L118

**Comment by t-wissmann** [comment]
The FAQ just explains this corner case. If you don't use any compositing manager or if you use compton (which extends xcompmgr massively), then no issues are known.

The frame_bg_transparent makes the user see the desktop background and allows to use a desktop application with desktop icons (e.g. xfdesktop). This is why I'd keep this setting in the default autostart.
