### ISSUE TITLE
Subscribe to workspace changes

### ISSUE THREAD

**Issue by clitetailor** [herbstluftwm/herbstluftwm#572]
In `bspwm` we can subscribe to workspace changes by using `bspc subscribe desktop` or `bspc subscribe report`, etc. Is there any feature like this in hlwm?

**Comment by t-wissmann** [comment]
Are you looking for `herbstclient --idle`? It prints all kinds of events. You can filter them by adding further arguments, e.g. `herbstclient --idle tag`.

**Comment by clitetailor** [comment]
Oh, thank you so much @t-wissmann. I will close this issue now!
