### ISSUE TITLE
Frames start to glitch when resizing.

### ISSUE THREAD

**Issue by awsyoos** [herbstluftwm/herbstluftwm#574]
I've been trying to resize frames, but every time I try to this happens.
![2019-08-17-171428_1600x900_scrot](https://user-images.githubusercontent.com/49397752/63214679-3d63c980-c113-11e9-8095-49a185cba22e.png)
I tried several terminal emulators, but it didn't work.

**Comment by t-wissmann** [comment]
How are you trying to resize? With only the mouse or are you pressing Mod-Right?

**Comment by awsyoos** [comment]
The issue is fixed, there's a bug in `xcmopmgr` that causes transparent windows to do that, but now I'm using `compton`.
Thanks anyways/
