### ISSUE TITLE
build fails on up-to-date ubuntu

### ISSUE THREAD

**Issue by jpicht** [herbstluftwm/herbstluftwm#575]
Hi all,

I cannot build the current code on my up-to-date ubuntu machine. Here is a Dockerfile to reproduce:
```
FROM ubuntu:disco
RUN apt-get update && \
	apt-get install -y \
	asciidoc \
	build-essential \
	libglib2.0-dev \
	libx11-dev \
	libxext-dev \
	libxml2-utils \
	make \
	xsltproc \
	checkinstall \
	--no-install-recommends
COPY . /build
RUN make -C /build -j $(nproc)
RUN cd /build && \
	checkinstall -D -y \
		--pkgname herbstluftwm \
		--pkgversion 0.7.2 \
		--pkgrelease 1 \
		--pkgsource https://github.com/herbstluftwm/herbstluftwm/ \
	  make install
```

Though this is a problem with asciidoc, it can be worked around by disabling the XML validation (adding the -L command line option to a2x):
```
diff --git a/Makefile b/Makefile
index 7849896..307aa51 100644
--- a/Makefile
+++ b/Makefile
@@ -93,7 +93,7 @@ tar: doc
 
 doc/%.1 doc/%.7: doc/%.txt version.mk
        $(call colorecho,DOC,$@)
-       $(VERBOSE) $(A2X) -f manpage -a "herbstluftwmversion=herbstluftwm $(VERSION)" -a "date=`date +%Y-%m-%d`" $<
+       $(VERBOSE) $(A2X) -L -f manpage -a "herbstluftwmversion=herbstluftwm $(VERSION)" -a "date=`date +%Y-%m-%d`" $<
 
 doc/%.html: doc/%.txt version.mk
        $(call colorecho,DOC,$@)
```

I don't know if this workaround should be applied to the actual (C)Makefile or if it's better to leave the validation step on by default and just add a comment to the documentation on how to work around the error?

**Comment by t-wissmann** [comment]
Thanks for the report, and sorry for letting you wait. To be honest, I didn't know whether to add the `-L` or not. Actually, one would expect that if the xml does not validate, then it should not be the fault of the asciidoc source...

So I think it's reasonable to disable xmllint.

**Comment by t-wissmann** [comment]
This is fixed by #813.

**Comment by blarz** [comment]
Can this issue be closed?

**Comment by t-wissmann** [comment]
Yes.
