### ISSUE TITLE
"herbstclient load" does not send correct EMWH hints

### ISSUE THREAD

**Issue by dnnr** [herbstluftwm/herbstluftwm#577]
I have not looked into this very much, so the issue title is only my *interpretation* of what the underlying bug is.

Steps to reproduce:
 * Use a bar that shows workspaces using EMWH
 * Open a couple of clients on several tags
 * Use the `restart.sh` trick to restart hlwm with state restoration (this probably just boils down to relocating clients using the `load` command)

Expected results:
 * Occupied state of workspaces as shown by the bar matches reality

Actual results:
 * Clients seem "hidden" to the bar (workspaces are shown unoccupied) until they are moved to another tag manually

**Comment by t-wissmann** [comment]
I could reproduce and fix it.
