### ISSUE TITLE
Horizontal tiling at startup by default on all tags

### ISSUE THREAD

**Issue by erikdubois** [herbstluftwm/herbstluftwm#580]
When I boot up herbstluftwm, it is standard set to vertical tiling.
Can I give it the command to boot up with horizontal tiling by default on all tags?

**Comment by t-wissmann** [comment]
See the setting `default_frame_layout` and http://herbstluftwm.org/faq.html#_q_i_set_default_frame_layout_to_my_favorite_layout_but_it_doesn_8217_t_work_with_the_root_frame_existing_frames

**Comment by erikdubois** [comment]
I nodged me in the right direction
what I want to achieve is done with this command

`hc set_layout horizontal`

Thanks - closing
