### ISSUE TITLE
vmware dynamic resolution support

### ISSUE THREAD

**Issue by sum-catnip** [herbstluftwm/herbstluftwm#581]
heyo,

i installed herbstluftwm in a vmware virtual machine and noticed the dynamic resolution/resizing doesnt seem to work. So i tried it with awesomewm and i3 to see if it was related to herbstluft and both properly updated the size.

[on i3](https://imgur.com/czBQuhX)
[on herbstluft](https://imgur.com/a/QbsoGBF)

Is dynamic resolution not supported, am i doing something wrong or is this specific to vmware?

**Comment by t-wissmann** [comment]
Does the resolution update correctly if you run
```
herbstclient detect_monitors
```
after resizing the window?

If yes, you can set
```
herbstclient set auto_detect_monitors 1
```
in your autostart.

**Comment by sum-catnip** [comment]
that works perfectly, thank you so much :D
