### ISSUE TITLE
Add support for mouse button 8 and 9

### ISSUE THREAD

**Issue by astier** [herbstluftwm/herbstluftwm#582]
I would like to bind actions to the mouse-buttons 8 and 9. Those can be found on some mouses usually on the left side. Currently I rely on sxhkd to make use of them in order to call herbstclient actions when I press them. It would be nice if It would be possible to bind this buttons directly in hlwm.

**Comment by t-wissmann** [comment]
I don't know how to access these buttons. They don't seem to be covered by the core X11 functionality. Do you know how sxhkd accesses these extra buttons?

**Comment by astier** [comment]
I looked at his code but I don't really know anything about C++ or X11. If you have no idea either then close it.

**Comment by jer-gentoo** [comment]
`parse_event()` at https://github.com/baskerville/sxhkd/blob/master/src/parse.c#L2418 uses an `xcb_button_press_event_t` to read a `xcb_button_t` (uint8_t) `detail`. It thereby intrinsically supports any uint8 that X throws at it, and elsewhere in `parse_button()` it matches that with a configured `buttonNN` event handler.

It seems hlwm isn't using xcb (yet).

**Comment by xxxserxxx** [comment]
It looks like Herbstluftwm is just using `XButtonEvent` from xlib directly, and so `XButtonEvenct->button` (uint) should be reporting the button number -- even if it's higher than 5, which is the highest for which X provides a `#define`.

A simple test program:
```c
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/cursorfont.h>

int main(){
    Display* display;
    int screen_num;
    Screen *screen;
    Window root_win;
    XEvent report;
    XButtonEvent *xb = (XButtonEvent *)&report;
    int i;
    Cursor cursor;
    display = XOpenDisplay(0);
    if (display == NULL){
        perror("Cannot connect to X server");
        exit (-1);
    }
    screen_num = DefaultScreen(display);
    screen = XScreenOfDisplay(display, screen_num);
    root_win = RootWindow(display, XScreenNumberOfScreen(screen));
    cursor = XCreateFontCursor(display, XC_crosshair);
    i = XGrabPointer(display, root_win, False,
                ButtonReleaseMask | ButtonPressMask|Button1MotionMask, GrabModeSync,
                GrabModeAsync, root_win, cursor, CurrentTime);
    if(i != GrabSuccess){
        perror("Can't grab the mouse");
        exit(-1);
    }
    for(i = 0; i < 10; i++){
        XAllowEvents(display, SyncPointer, CurrentTime);
        XWindowEvent(display, root_win, ButtonPressMask | ButtonReleaseMask, &report);
        switch(report.type){
            case ButtonPress:
                printf("Press @ (%d, %d) - button %d\n", xb->x_root, xb->y_root, xb->button);
            break;
            case ButtonRelease:
                printf("Release @ (%d, %d) - button %d\n", xb->x_root, xb->y_root, xb->button);
            break;
        }
    }
    XFlush(display);
    XUngrabServer(display);
    XCloseDisplay( display );
    return 0;
}
```
shows that all buttons are reported by `XButtonEvent->button`, even those that have no `#define`s:
```bash
$ gcc -lX11 main.cpp
$ ./a.out                                                                                                                                                       /tmp/xtest 10043
Press @ (3097, 505) - button 1
Release @ (3097, 505) - button 1
Press @ (3074, 508) - button 3
Release @ (3074, 508) - button 3
Press @ (3075, 509) - button 8
Release @ (3075, 509) - button 8
Press @ (3075, 509) - button 9
Release @ (3075, 509) - button 9
```

I'm not a C programmer; I just copied and pasted some code I found online -- so I don't feel confident making a patch; but, if a non-C programmer can see that all mouse buttons are reported in the same mechanism `herbstluftwm` is using to get at mouse buttons, and that the only barrier is some missing `#defines` for the higher buttons... surely this isn't a challenging problem, and the "how" isn't a hard question.

This was closed as "completed," which isn't really true. It might be closed as "won't fix," but the current state implies this is fixed, when it isn't.
