### ISSUE TITLE
Resize inside frame 

### ISSUE THREAD

**Issue by zakariaGatter** [herbstluftwm/herbstluftwm#583]
i just move from I3 to HERBSTLUFTWM and i love it so easy to config and so beautiful 

but i miss one thing: resize windows inside frame 

why there is not action for that and can u add it ??

**Comment by The-Compiler** [comment]
Manual control over windows is the whole point of frames - inside frames, windows are tiled automatically. Personally I don't think that should change. Could you elaborate why you want such a feature?

**Comment by zakariaGatter** [comment]
i know that why u make frame but some time inside a frame i create 2 terminal and i want one bigger then the other thats why 

if i can't resize inside frame, is there is any rule that create a frame each time i open a window ??

**Comment by spijet** [comment]
Hello @zakariaGatter!
I'm not sure if there's a way to make a rule that would behave like you ask, but you can use "explode" function instead:
```
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode
```

When used, it splits the focused frame into many frames according to window layout inside the frame. So, if you had a frame with two terminals (top/bottom), you'll get two frames with one terminal inside each and you can freely resize them.

**Comment by t-wissmann** [comment]
Hi @zakariaGatter,
What you can do is the following, which is a bit hacky: add to your autostart
```
hc rule hook=new_client
```
and as a separate script, run:
```
#!/usr/bin/env bash
herbstclient --idle rule new_client | while read h ; do
    herbstclient and , compare tags.focus.curframe_wcount ge 2 \
                     , split explode
done
```
It will split your frame whenever a new client appears and if there are at least two clients in the focused frame.

But I really agree with @spijet: Binding `split explode` to a easy to reach keybinding is the much cleaner way.
