### ISSUE TITLE
Changes in winterbreeze 

### ISSUE THREAD

**Issue by syslino** [herbstluftwm/herbstluftwm#585]
Hi, I really like to know where winterbreeze is taking hlwm. 
I tried the packaged version on Arch but didn't find too much effective changes. The website and documentation isn't very informative either.

Could someone elaborate on what is already implemented and what is planned?

**Comment by t-wissmann** [comment]
I fear the answer is dissappointing. There are nearly no user-visible changes intended. In winterbreeze, we have rewritten the internals of hlwm to make it easier to incorporate future features (e.g. single-window floating) more easily. The list of user visible changes and bug fixes have a quite technical nature and can be found in the NEWS file:
https://github.com/herbstluftwm/herbstluftwm/blob/winterbreeze/NEWS

**Comment by syslino** [comment]
Thank you for your quick reply, not disappointing at all! Still a good read to me! :smile: 
I really appreciate your work on hlwm. I reinstalled winterbreeze, the least thing I can do is hunt for bugs. The "hookable" attribute, will this be exposed to the user? If I think about it, this could be a unique an very powerful thing to have!

Again, thank you for this, I think I wont be able to use another WM...

**Comment by t-wissmann** [comment]
Yes, the hookable will be exposed to the user!

**Comment by astier** [comment]
Hey the winterbreeze link doesn't work anymore. There is also no winterbreeze branch anymore. Was it already merged? I certainly can appreciate improvements to the codebase without immediate visible improvements to the end-user. Thank you for your work.

**Comment by tiosgz** [comment]
Yes, it was already merged. You can look at NEWS in master.

**Comment by t-wissmann** [comment]
@astier: yes it's merged and there are already some new features ([NEWS](https://github.com/herbstluftwm/herbstluftwm/blob/master/NEWS))
