### ISSUE TITLE
Removing a manual tile switches window focus and can re-order the layout

### ISSUE THREAD

**Issue by jsteel44** [herbstluftwm/herbstluftwm#587]
If I open two windows and manually split them, then switch focus to the right (or bottom) window and then remove the manual split, focus shifts to the left window (or top window).

What is even stranger, is if the left (or top) window is focused, then removing the manual split swaps the position of the two windows and the right window moves to the left (or the bottom window moves to the top).

This behaviour is very strange; the windows should maintain their focus and relative position (or position before the manual split was made) when a manual split is removed.

If my explanation isn't very clear I can make a video if that would help.

Thanks!

**Comment by t-wissmann** [comment]
I know what you mean, and this bugs me as well. The behaviour comes from "removing" the focused frame and adding the windows to the sibling of the removed frame.
I guess we should change the behaviour here to some smarter and more difficult strategy that looks less surprising from a visual point of view.

**Comment by t-wissmann** [comment]
This is the same issue as https://github.com/herbstluftwm/herbstluftwm/issues/593 and I've fixed it today (PRs #621/#622).
