### ISSUE TITLE
Initial frame layout

### ISSUE THREAD

**Issue by linwaytin** [herbstluftwm/herbstluftwm#591]
Hi community,

I want to use herbstluftwm as my window manager, but there is one thing I cannot figure out.
How do I set up the initial frame layout?
are there any log files I can look at to find the problem or give you more information?

My autostart is like this
```bash
#!/usr/bin/env bash
 
# this is a simple config for herbstluftwm
 
hc() {
    herbstclient "$@"
}
 
hc emit_hook reload
 
xsetroot -solid '#5A8E3A'
 
#hc set_layout max
hc set default_frame_layout 2
 
# remove all existing keybindings
hc keyunbind --all
 
# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
```

The initial windows are still laid out in a vertical tiling way.

**Comment by t-wissmann** [comment]
Existing tags are not affected by a change of that variable (only new ones), so be sure to set it before creating any tags. For existing tags (e.g. only the tag named `default`), you can change the default layout by running
```
hc load '(clients max:0)'
```

**Comment by linwaytin** [comment]
Thank you!
