### ISSUE TITLE
Winterbreeze:`herbstclient remove` focuses the wrong client

### ISSUE THREAD

**Issue by olmokramer** [herbstluftwm/herbstluftwm#593]
When I have two frames side by side and merge them with `herbstclient remove`, the client that was focused in the unfocused frame will get focus after the merge. Both of my frames are in the "max" layout.

Update: Ok, so I kinda forgot about this, I'm sorry, but here's a more detailed description of the issue :-)

So let's say I have this frame layout (where the `+` border indicates the focused frame), and frame A and B contain one client each, client A' and B', respectively.

    +-----+++++++
    |     +     +
    |  A  +  B  +
    |     +     +
    +-----+++++++

and I then run `herbstclient remove`, then I'm left with only a single frame (which is good) but now client A' is focused. If I instead focus the other frame before the `remove`, like so

    +++++++-----+
    +     +     |
    +  A  +  B  |
    +     +     |
    +++++++-----+

then client B' is focused after running `herbstclient remove`.

It does not seem to matter how the frame was split, horizontally or vertically.

I am running the Winterbreeze branch, commit af41a0d5. I haven't been able to test this behaviour on the master branch, but either way I don't think this is expected behaviour.

Please let me know if there's more information you need :)

**Comment by t-wissmann** [comment]
I've addressed this in PR #621, and I can comment on this a this is 'issue' exists in the old code base as well, not only in winterbreeze.

**Technical explanation:** The reason for this behaviour is that my original understanding of the 'remove' command is: remove the focused frame entirely with all its containing client windows and act as if it was not there anymore. Of course, we can't remove the clients, so they need to go somewhere, so just append them to the frame that is focused from now on.

In your example, this is precisely what happens: the frame containing B is removed, so there is only one frame left that can be focused: the one with A. And as a courtesy to client B, we allow it to live on in frame B.

Of course, this is not what **users (including myself) intend**: I guess one only wants to resize the client, but still want it focused. I hope the PR fixes this. (There is still another subtlety when frame A itself consists of two side-by-side frames.. I'll address it in another PR)

**Comment by olmokramer** [comment]
Awesome, thanks for the fix and the explanation! I will try it out in the weekend.

**Comment by olmokramer** [comment]
Finally got around to trying this out, and it works great. Thanks again!

**Comment by t-wissmann** [comment]
Thanks!
