### ISSUE TITLE
HiDPI

### ISSUE THREAD

**Issue by linwaytin** [herbstluftwm/herbstluftwm#596]
Sorry this might not be really related to herbstluftwm,
but I cannot find the answer in other places.

I have set `Xft.dpi` in .Xresources,
but after `startx /bin/herbstluftwm` the font is still small.
Does anyone know how to solve this?

Thank you.

**Comment by t-wissmann** [comment]
I have the line
```
Xft.dpi: 160
```
Does it help if you load your .Xresources from within the session?
```
xrdb -load $HOME/.Xresources
```
This only affects new terminals.
If it does I recommend that you create the following `~/.xinitrc` and mark it executable:
```
#!/usr/bin/env bash

xrdb -load $HOME/.Xresources
exec herbstluftwm
```
Afterwards, you can simply type `startx`

My full font configuration by the way is:
```
Xft.dpi: 160
rofi.dpi: 160
Xft.autohint: 0
Xft.lcdfilter:  lcddefault
Xft.hintstyle:  hintfull
Xft.hinting: 1
Xft.antialias: 1
Xft.rgba: rgb

urxvt*background:rgba:2828/2828/2828/dddd
urxvt*depth: 32
xterm*faceName: 'xft:Bitstream Vera Sans Mono:style=bold:pixelsize=20'
```

**Comment by linwaytin** [comment]
It does!
After `xrdb -load ~/.Xresources` the dpi changes.
Thank you.

**Comment by linwaytin** [comment]
One more question.
Can I write these in another file instead of `.xinitrc`?
say `myHerbrc` and `startx ~/myHerbrc`

It's because I have already had an .xinitrc and I don't mess it up.
Thank you.

**Comment by t-wissmann** [comment]
Yes that's possible according to the `startx` manpage. (I didn't test it though).

**Comment by linwaytin** [comment]
Thanks! That works
