### ISSUE TITLE
[Question] What is the tag_flags hook for?

### ISSUE THREAD

**Issue by syslino** [herbstluftwm/herbstluftwm#603]
And will it get useful anytime soon? Or am I missing anything? It pops up if for example a client gets urgent state, would be tremendously useful if this would be accompanied by a wind, for example. Right now I'm looping through all the clients - a rather inefficient thing to do. Is there a reason for this? I cannot C, but I also cannot believe that it would be a super-difficult to give that hook some verbosity.
Thank you.

**Comment by t-wissmann** [comment]
Sorry for replying late...

The `tag_flags` signals that the output of `tag_status` has changed. This is used to update the color indicators for the tags in the panel (e.g. whether a tag is empty or not, or whether it conatins an urgent window).

If a window becomes urgent, the `urgent` hook is fired, for example
```
urgent	on	0x340000a
tag_flags
focus_changed	0x340000a	thorsten@x1 ~
urgent	off	0x340000a
tag_flags
```
The first argument is the new urgency state and the second argument is the window id whose urgency state has changed.

**Comment by syslino** [comment]
Thank you for your reply!
