### ISSUE TITLE
Bring a window by its title or class

### ISSUE THREAD

**Issue by linwaytin** [herbstluftwm/herbstluftwm#607]
The `bring` function can bring a window and focus it in the current frame.
I think this is a very useful function, like `stumpwm`'s `pull-from-windowlist` or Emacs's `switch-to-buffer`.
However it accepts only WIN ID. 
Is it possible to get WIN ID by its title or class?

**Comment by t-wissmann** [comment]
One can easily build this with the tools `wmctrl` and `rofi`:
```
winid=$(wmctrl -l | rofi -dmenu -i -p "bring"|cut -d" " -f1) && herbstclient bring "$winid"
```
This opens a menu with all windows and the id of the selected window is passed to `herbstclient bring`. If you want it as a key-binding (e.g. <kbd>Win</kbd>+<kbd>B</kbd>) you can add the following to your autostart:
```
herbstclient keybind Mod4-b spawn bash -c \
   'winid=$(wmctrl -l | rofi -dmenu -i -p bring|cut -d" " -f1) \
    && herbstclient bring "$winid"'
```

**Comment by linwaytin** [comment]
Fantastic. 
Thank you.
