### ISSUE TITLE
Feature request: Lock workspace to specified monitor

### ISSUE THREAD

**Issue by PureTryOut** [herbstluftwm/herbstluftwm#61]
Using 2 screens, you can have all workspaces on whatever monitor you desire. I would like an option so lock a workspace to a specified monitor. Say workspace 8 to monitor 2.
If you press the key combination to get to that workspace, it would move your mouse and focus to the workspace on the screen it's locked to. This makes it for example easy to have a web-browser on a second monitor at all times (except when you manually move the window to a different container/workspace of course).

**Comment by ypnos** [comment]
You can achieve this feature easily by writing your own script that discerns the action based on workspace name. You can then bind to that instead.
You can do this either with an external script or hlwms internal scripting. The latter has some benefits in practice. I am not versed in that so I don't have a concrete example for you. It should only be a one-liner though.

**Comment by t-wissmann** [comment]
I've added an FAQ entry about this: http://herbstluftwm.org/faq.html#_q_how_can_i_have_some_of_the_tags_on_specific_monitors_only

Basically for each tag, you need to save the desired monitor name or index in the tag’s attributes. Before switching to another tag, check whether it has such an attribute, and if so, switch to that monitor first. The code for the autostart is as follows. It allows both static configuration of lockings and dynamically creation of lockings via the Mod-t and Mod-Shift-t keybindings:
```bash
# Replace the default section for tags in your autostart by the following:
# This is the default tag section of the autostart, with a single change:
# In the use_index keybinding, check the presence of the my_monitor attribute,
# before focusing the desired tag.
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        # first check if the tag is locked to some monitor.
        # if so, first focus the monitor
        hc keybind "$Mod-$key" \
            chain , silent substitute M tags."$i".my_monitor \
                        focus_monitor M \
                  , use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Add a keybinding for locking the current tag to the monitor it is displayed
# on. This is done by safing the current monitor index in the my_monitor
# attribute of the focused tag. If the monitor has a (nonempty) name, use the
# monitor name instead of its index.
herbstclient keybind $Mod-t chain \
    , new_attr string tags.focus.my_monitor \
    , substitute M monitors.focus.index set_attr tags.focus.my_monitor M \
    , try and \
        . compare monitors.focus.name != "" \
        . substitute M monitors.focus.name \
                set_attr tags.focus.my_monitor M

# Add a keybinding for removing the lock
herbstclient keybind $Mod-Shift-t \
    remove_attr tags.focus.my_monitor

# Statically define which tag should be send to which monitor
lock_tag_to_monitor() {
    herbstclient chain \
        , new_attr string tags.by-name."$1".my_monitor \
        , set_attr tags.by-name."$1".my_monitor "$2"
}
# Already lock some of the tags to a monitor, for example:
# lock the tag 8 to the monitor with index 1 (i.e. the second monitor)
lock_tag_to_monitor 8 1
```

**Comment by davidv171** [comment]
This does not synergize with:
`hc use_index +1` or `hc use_index -1`
Also issues with `hc use_previous` can occur. Basically every command to reach a workspace that is not the standard keybind will cause issues. I still believe true locking monitors to workspace is necessary.
