### ISSUE TITLE
[winterbreeze] $ herbstclient floating [tag]         >>> Exit from herbstluftwm

### ISSUE THREAD

**Issue by Hadi374** [herbstluftwm/herbstluftwm#610]
command 'herbstclient floating [tag number]' without "on | off | toggle" prompts to exit from window manager. I know this is not a big problem and usually does not happen. but I think solving of this problem is easy and maybe in file: "src/tag.cpp:81". 

I don't test this command on 'master' branch. maybe that branch will have this problem too.

**Comment by The-Compiler** [comment]
I can't reproduce.

**Comment by The-Compiler** [comment]
Ah, though there *is* something odd happening: Running e.g. `hc floating 2` will just log `src/tag.cpp: 412: setting tag:1->floating to off` (wrong tag, and always off rather than toggling). Happens on master as well.

**Comment by Hadi374** [comment]
this problem is only for winterbreeze branch. I can't reproduce on master too.

**Comment by t-wissmann** [comment]
Thanks for reporting! The exception handler was missing in winterbreeze. On master, an invalid description of the boolean led to the value *off*.

The floating command was in the old command format in winterbreeze anyway, so I've directly migrated it and fixed the issue along the way in #611.

**Comment by Hadi374** [comment]
Thanks for quickly fixing this issue.
#611 solved this issue.

**Comment by t-wissmann** [comment]
Thanks for checking! I've just merged it to the winterbreeze branch.
