### ISSUE TITLE
How to correctly set a rule

### ISSUE THREAD

**Issue by AckslD** [herbstluftwm/herbstluftwm#643]
Hi!

I'm very new to using herbstluftwm but I'm already hooked!

I'm trying to configure rules for my most common applications and can't seem to make this work. I have the following rule for `qutebrowser` which does work:
```
hc rule class=qutebrowser tag=2
```
When I open `qutebrowser` it opens in the second workspace.

However I tried to do the same for spotify without success. I tried the following different commands (and combinations thereof):
* `hc rule instance=spotify tag=3`
* `hc rule class='spotify' tag='3'`
* `hc rule title~'[Ss]potify*' tag=3`
but in all cases the spotify window opens in the focused workspace.

I would be very grateful for some input on how to do this correctly.

Thanks in advance!

**Comment by t-wissmann** [comment]
The problem is that spotify sets its class after it's window is shown (there's the same issue in i3wm https://github.com/i3/i3/issues/2060#issuecomment-155179472). Sadly, hlwm is lacking the feature that is used in the workaround for i3: namely applying the rules again after the window already showed up...

**Comment by AckslD** [comment]
I see, thanks for your reply @t-wissmann! Do you know any workaround for this?

**Comment by t-wissmann** [comment]
I've implemented a workaround in #657 and now, the rule
```
hc rule class='Spotify' tag='3'
```
sends spotify to tag 3 (`instance=spotify` also works, pick whatever you like — beware the casing).

**Comment by AckslD** [comment]
@t-wissmann Cool :) I tried to install from source but couldn't figure how to make herbstluftwm an option in the login manager so couldn't try this new feature for now. What did you mean with 'beware of casing?'

**Comment by t-wissmann** [comment]
> @t-wissmann Cool :) I tried to install from source but couldn't figure how to make herbstluftwm an option in the login manager so couldn't try this new feature for now.
As a very quick fix, you can replace the `herbstluftwm` in `/usr/bin/` with the one compiled from source. And after trying it, you can re-install the herbstluftwm package from your package manager to replace it back with the official from the software repository.

> What did you mean with 'beware of casing?'

the `class` requires an upper-case `Spotify` whereas the `instance` requires a lower-case `spotify`.

**Comment by The-Compiler** [comment]
This issue probably can be closed now, right? @t-wissmann if you use "resolves" instead of "solves" (or fixes/fix/closes/close) in a commit/PR message, GitHub does that automatically)

**Comment by t-wissmann** [comment]
I'd say so, yes. Thanks

**Comment by AckslD** [comment]
> > @t-wissmann Cool :) I tried to install from source but couldn't figure how to make herbstluftwm an option in the login manager so couldn't try this new feature for now.
> 
> As a very quick fix, you can replace the `herbstluftwm` in `/usr/bin/` with the one compiled from source. And after trying it, you can re-install the herbstluftwm package from your package manager to replace it back with the official from the software repository.
> 
Thanks for you reply @t-wissmann! Sorry, maybe I shouldn't ask this here but so you mean replacing the binary of the version installed from the software repository with the one from source such that when I choose it in the login manager it actually runs the one from source instead of the one from the software repository?

> > What did you mean with 'beware of casing?'
> 
> the `class` requires an upper-case `Spotify` whereas the `instance` requires a lower-case `spotify`.
Right, thanks!

**Comment by t-wissmann** [comment]
> > > @t-wissmann Cool :) I tried to install from source but couldn't figure how to make herbstluftwm an option in the login manager so couldn't try this new feature for now.
> > 
> > 
> > As a very quick fix, you can replace the `herbstluftwm` in `/usr/bin/` with the one compiled from source. And after trying it, you can re-install the herbstluftwm package from your package manager to replace it back with the official from the software repository.
> 
> Thanks for you reply @t-wissmann! Sorry, maybe I shouldn't ask this here but so you mean replacing the binary of the version installed from the software repository with the one from source such that when I choose it in the login manager it actually runs the one from source instead of the one from the software repository?

Exactly! And with the next update of the software package, the binary will automatically replaced again with the one from the package (and also when you force-reinstall the software package).

**Comment by t-wissmann** [comment]
And another note: if you are running arch linux, you can also install the [herbstluftwm-git](https://aur.archlinux.org/packages/herbstluftwm-git/) package from the aur.
