### ISSUE TITLE
Update introduction to settings in the documentation

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#652]
The settings have now the correct type written (in the manpage), but the introduction to them still says:
> There are two types of settings: Strings and integer values. An integer value is set, if its value is 1 or another value unequal to 0. An integer value is unset, if its value is 0.

**Comment by t-wissmann** [comment]
Thank you for the careful read! :-) I've fixed this in 72e60b1008d82f8b40059ec5b4b869105adbf0fa. If you notice further things in the doc

**Comment by tiosgz** [comment]
I didn't really read it from top to bottom—I just started experimenting with the newest version and did not know how this now works.

Two more things I noticed:
- nowhere said how to set boolean settings (first I wanted to try `yes|no` which is the only intuitive way I know of and doesn't work :-D)
- description of `toggle` is outdated
