### ISSUE TITLE
move_previous option does not exist

### ISSUE THREAD

**Issue by razzintown** [herbstluftwm/herbstluftwm#66]
There is a herbstclient command for `use_previous`, but not one for `move_previous`. I expected that option to exist since there are both a `use_index` and `move_index`.

Could we add the `use_previous` function?

**Comment by t-wissmann** [comment]
Theoretically we can implement `move_previous`, but I don't see a need (i.e. an application) for it. So if you **need** it, just say so and please describe why you need it. (Just saying "`use_index` has its very best friend `move_index`, please also give such a friendship experience to `use_previous`" is not enought ;-))

**Comment by razzintown** [comment]
Good point. I forgot to mention that I need `move_previous` because I often use `use_previous` without memorizing or knowing the tag index that I came from. I may not always have a panel to show me. My use case for `move_previous` goes hand-in-hand with my use of `use_previous`. Which is that I sometimes must move windows between two tags, and sometimes they are not sequential (+1, -1). The `use_previous` option would make my workflow easier.

**Comment by ypnos** [comment]
So if I get it correctly, you want to switch to the previous tag and bring your focused window with you.
You can do that easily with a one-liner script. For example fish:
```sh
set winid (herbstclient attr clients.focus.winid); and herbstclient use_previous; and herbstclient bring $winid
```

In bash it would probably look like this:
```sh
winid=$(herbstclient attr clients.focus.winid) && herbstclient use_previous && herbstclient bring $winid
```

Would this be a solution to your problem?

**Comment by t-wissmann** [comment]
Right, if you want to go to the previous tag and take the focused window with you, then you can do that with this herbstclient command
```
 herbstclient substitute ID clients.focus.winid chain , use_previous , bring ID 
```

**Comment by t-wissmann** [comment]
Right, if you want to go to the previous tag and take the focused window with you, then you can do that with this herbstclient command
```
 herbstclient substitute ID clients.focus.winid chain , use_previous , bring ID 
```

**Comment by razzintown** [comment]
No, I don't want to switch to my previous tag. I only want my focused window to move to my previous tag.
Is there a way to get the previous tag index from `herbstclient` to so that I may use the `use_index` command? Such as:
`herbstclient substitute INDEX tags.focus.previous.index move_index INDEX`

**Comment by t-wissmann** [comment]
Sorry, that's not possible. If you can live with the flickering for the time being, you can do
```
herbstclient substitute ID clients.focus.winid chain , lock , use_previous , bring ID , use_previous , unlock
```

**Comment by ypnos** [comment]
You can also take the more complicated route and have a script running alongside herbstluftwm. It can either store the previous tag or the previously focused client. I would do it with the tag if I were you.

Several examples exist on how to listen for hooks (in this case `tag_changed` and `move_previous`); you can then bind a key to `emit_hook more_previous` and in your script do the deed.

For inspiration, here is a perl script of mine that listens to hooks and performs stuff: https://github.com/ypnos/hlwm/blob/master/redecorate.pl

**Comment by razzintown** [comment]
Thank you for your help. I will use the chain command.
