### ISSUE TITLE
Testsuite: Exit on xlib error

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#661]
Make the testsuite detect errors generated by the xlib, such as the error that is fixed in PR #660.

**Comment by blarz** [comment]
Wasn't this added with 3d8f3919b2fb137a6fb9a6f69995bcae6a11bcd6?

**Comment by t-wissmann** [comment]
Oh right, I've added it accidentally (Because I was debugging CI issues for #957) and then I forgot about it because it didn't break the CI (ever?) since :)
