### ISSUE TITLE
Hide/minimize windows in layout 2 (max) which are behind the current window

### ISSUE THREAD

**Issue by astier** [herbstluftwm/herbstluftwm#673]
Hi. I like to use layout 2 (max)  for my frames. This means all windows in a frame are stacked on each other and only one window at a time is visible in a frame. Would it be possible to hide the windows which are stacked behind the currently visible window? It similar to minimizing windows in traditional desktop environments. Bspwm has such a feature called hide.

The reason why I would like to have such a feature is because of:

- **Shadows:** Those overlap unfortunately and become thicker the more windows are stacked on each other.
- **Transparency:** I like to have my terminal transparent. However, if a window is stacked behind my terminal I see this window through my transparent terminal. I would prefer to see my wallpaper.

**Comment by t-wissmann** [comment]
I'd like this as well. One only needs to think a bit what to do with pseudotile windows.

**Comment by astier** [comment]
It seems to me like the simplest implementation would be to treat a pw (pseudotile-window) just as any other window. This means if a pw is focused than hide the windows behind it like it would normally happen. If you don't want it you have to create a special case for pws. Maybe then you could add an option which users could set to choose the behavior. I personally would be happy with the simpler implementation. Add you would have to implement first anyway before you can implement the special case.

**Comment by t-wissmann** [comment]
It's now implemented in the git version (PR #757). I'm also handling pseudotile windows already. Does it solve your issue?

**Comment by t-wissmann** [comment]
(The new setting is called `hide_covered_windows`)
