### ISSUE TITLE
Where have the window class/instance attributes gone?

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#687]
I've just realised I cannot get window class/instance through `hc attr` though on the manpage it is listed and I couldn't find a commit/PR removing them since last release (searched only summary).

Is this intended?

**Comment by t-wissmann** [comment]
Oh, this is a mistake. It seems I accidentally dropped them while refactoring the attribute system. I will add this as soon as possible!

**Comment by t-wissmann** [comment]
They're back as soon as #688 is merged. Sorry about this, and thanks for reporting!

**Comment by tiosgz** [comment]
Thanks!
