### ISSUE TITLE
how to find index of a frame?

### ISSUE THREAD

**Issue by MarMun** [herbstluftwm/herbstluftwm#692]
I have a layout:

```
╾─┐ horizontal 65% selection=1
  ├─┐ horizontal 45% selection=0
  │ ├─┐ vertical 50% selection=1
  │ │ ├─╼ vertical: <- this is location 'left' top*
  │ │ └─╼ vertical: <- this is location 'left bottom'*
  │ └─╼ vertical: <- this is location 'center'*
  └─╼ vertical: <- this is location 'right'*
```

* I know that by moving a terminal into each location, run hc layout and look were the 'focus' marker is.

**Question:** How do I find out which frame / location has which (frame) index so I can use it in a rule [like here](https://herbstluftwm.org/faq.html#_q_what_about_a_layout_for_instant_messaging_applications_gajim_pidgin):

hc rule class=Pidgin windowrole=buddy_list tag=$imtag index=1 focus=off

What I figured out by trial and error is:

```
╾─┐ horizontal 65% selection=1
  ├─┐ horizontal 45% selection=0
  │ ├─┐ vertical 50% selection=1
  │ │ ├─╼ vertical: <- this is frame index ??
  │ │ └─╼ vertical: <- this is frame index ??
  │ └─╼ vertical: <- this is frame index 01
  └─╼ vertical: <- this is frame index 1
```
I fail to understand how frame index works / is allocated...

**Comment by MarMun** [comment]
Btw its awesome you even have a frame index I can use in a rule! (e.g. bspwm and awesome have not / at least to my knowledge).

**Comment by tiosgz** [comment]
You go through the tree, for each frame select either 0 (first child) or 1 (second child) until you have the frame you want. So for example your layout is:
```
╾─┐ horizontal
  ├─┐ horizontal   0
  │ ├─┐ vertical   00
  │ │ ├─╼ vertical 000
  │ │ └─╼ vertical 001
  │ └─╼ vertical   01
  └─╼ vertical:    1
```

**Comment by MarMun** [comment]
@tiosgz Thx a lot! 

I struggled with this for hours!!

What I also just noticed this:

```
╾─┐ horizontal 65% selection=0 <------
  ├─┐ horizontal 45% selection=0 <------
  │ ├─┐ vertical 50% selection=0 <------
  │ │ ├─╼ vertical:
  │ │ └─╼ vertical:
  │ └─╼ vertical:
  └─╼ vertical:
```
This is telling me the index I need to use ('000' in this case).
