### ISSUE TITLE
Can not get current frame layout using attributes

### ISSUE THREAD

**Issue by gayprogrammer** [herbstluftwm/herbstluftwm#71]
I would like to use an attribute like `tags.focus.curframe_layout` to find the current frame layout (tiling algorithm), but it does not exist.

My goal is to display the current frame's layout (tiling algorithm) in my panel. The easiest way would be if a hook was emitted when the layout changes. This is what I tried to do:
`herbstclient substitute LAYOUT tags.focus.curframe_layout emit_hook layout_changed LAYOUT`

Will it be possible to add something like `curframe_layout` or `tiling_algorithm` to the attributes?

**Comment by bklaase** [comment]
While probably not exactly what you are looking for, the layout of the current frame can best be obtained from running:
herbstclient layout

```
% herbstclient layout 
╾─┐ horizontal 50% selection=0
  ├─╼ vertical: 0x2a000d2 0x2a00235 [FOCUS]
  └─╼ vertical: 0x2a00004
```

The "[FOCUS]" gives you easy access to finding the right frame. Now your remaining problem is finding the best way to know when to ask for this info. What I would suggest is plugging it in a subset of hooks and events that together would constitute every possible event of being in a different layout:
**Hooks**
- focus_changed (also fires when switching to an empty frame (and therefore different tag or monitor))

**user actions / events**
- frame deletion (only required when the focus would not change to another frame/client)
- frame layout change

You would need to add your script to the shortcuts or automatic triggers that can cause the above events to happen. I *think* that these three would give you the complete set to have the behaviour that you require.

The alternative is of course easier to maintain, but less elegant: simply keep polling/parsing `herbstclient layout `.

**Comment by The-Compiler** [comment]
Some ~~months~~ years ago, I worked on [frame objects](http://git.the-compiler.org/herbstluftwm/log/?h=frame_objects) which would have that attribute - however it was reverted after merging due to a crash, and then we decided to wait until [winterbreeze](https://github.com/herbstluftwm/herbstluftwm/tree/winterbreeze) (the "proper" C++ rewrite) was merged and I'll pick that up then again.

**Comment by bklaase** [comment]
Is there news on this issue? :) 
I'm using the method I desribe above when I see a focus_changed, or framelayout_changed, which works fine. Just curious

**Comment by t-wissmann** [comment]
No, there aren't news, sorry. But my plan is to implement the frame objects!

**Comment by t-wissmann** [comment]
@bklaase , @gayprogrammer: you can now do the following in the git-version:
```
herbstclient attr tags.focus.tiling.focused_frame.algorithm
```

**Comment by bklaase** [comment]
Excellent! Thank you so much! 🙂

**Comment by blarz** [comment]
With #1111 you should now be able to watch attributes changing

**Comment by t-wissmann** [comment]
Concretely, you can now write
```
herbstclient watch tags.focus.tiling.focused_frame.algorithm
```
and this will cause `herbstclient --idle` to print something whenever the attribute changes ([see `watch`](https://herbstluftwm.org/herbstluftwm.html#watch)) and this will result in your panel being updated.

**Comment by t-wissmann** [comment]
I think everything requested here has been implemented, so I'm closing this issue. If there is anything left, please open another issue.
