### ISSUE TITLE
Keymask affects other clients

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#713]
If I set `keymask` to a client, it affects all other clients with unset keymask until another client with set keymask is focused.

Also, keymask works the opposite way of what's described in manpage, i.e., it *blocks* matching hotkeys (but that's a problem of manpage, the way it works makes more sense to me).

**Comment by t-wissmann** [comment]
Thanks for this very precise issue description! I've fixed the mistake in #714.

Regarding the documentation it seems that the documentation is actually right ([original patch](http://herbstluftwm.org/archive/msg00341.html)) but my implementation (for the winterbreeze rewrite) is the wrong way around. Hence, I have to eventually change the behaviour to make it match all previously released herbstluftwm stable versions.

I think the best way to have both is to add another attribute `keymask_inverse` such that a key press reaches the client only if
1. it matches `keymask` and
2. it does not match `keymask_inverse`

What do you think? Do you have a better name than `keymask_inverse`?

**Comment by tiosgz** [comment]
> I've fixed the mistake in #714.

Thanks!
> I think the best way to have both is to add another attribute `keymask_inverse` such that a key press reaches the client only if
> 
> 1. it matches `keymask` and
> 2. it does not match `keymask_inverse`
> 
> What do you think?

This would be good. But I think you meant *HLWM* instead of *client*.
> Do you have a better name than `keymask_inverse`?

`(hot)keys_disabled`?

**Comment by t-wissmann** [comment]
> Also, keymask works the opposite way of what's described in manpage, i.e., it _blocks_ matching hotkeys (but that's a problem of manpage, the way it works makes more sense to me).

For the record: by PR #715, what was called `keymask` in winterbreeze (git version of the past two weeks) is now called `keys_inactive` and has the opposite meaning of `keymask` (as described in the man page). For the moment `keymask` has no effect, but I'll reimplement the documented meaning of `keymask` soon.

Thanks again to @tiosgz for spotting this inconsistency!
