### ISSUE TITLE
Handle _NET_WM_STATE_BELOW (enhancement request)

### ISSUE THREAD

**Issue by sdothum** [herbstluftwm/herbstluftwm#72]
In max view, compton shadows appear to be written for each window, creating a darker shadow for the window than other layouts (when max view contains more than one window). 

_NET_WM_STATE_BELOW would allow a shadow-exclude rule in compton.

**Comment by astier** [comment]
Would love to see this fixed.

**Comment by t-wissmann** [comment]
In principle I agree, but I think `_NET_WM_STATE_BELOW` is not the right way to do this. But the approach of #673 would be a nice solution.

**Comment by t-wissmann** [comment]
With PR #757 we now have a `hide_covered_windows` setting, that (if activated) should solve the issue for you.
