### ISSUE TITLE
smart_window_surroundings not working correctly

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#721]
When `smart_window_surroundings` is enabled and `window_gap` is larger than 0, the gap appears around right and bottom border of the client (even if it's the only client in its frame).

**Comment by t-wissmann** [comment]
Thanks for reporting! Though I see the problem in the sourcecode (`Client::resize_tiling()` takes care of `window_gap` and does not know about the frame and whether `smart_window_surroungings` is the case), I need a bit of time to find a clean solution for this...

**Comment by t-wissmann** [comment]
As it turned out, the issue could be fixed nicely by PR #722.
Thanks :)

**Comment by tiosgz** [comment]
Thanks!
