### ISSUE TITLE
floating: invalid argument: only on/off/true/false/toggle are valid booleans

### ISSUE THREAD

**Issue by jer-gentoo** [herbstluftwm/herbstluftwm#734]
Versaion 0.8.0 appears to regress in the behaviour of the floating command:
```
$ herbstclient floating
floating: not enough arguments
$ herbstclient floating 6
invalid argument: only on/off/true/false/toggle are valid booleans
```
In the previous version this would default to toggle, and the manual still states that "[i]f no argument is given, floating mode is toggled."

**Comment by t-wissmann** [comment]
> Versaion 0.8.0 appears to regress in the behaviour of the floating command:
> 
> ```
> $ herbstclient floating
> floating: not enough arguments
> ```
> 
> In the previous version this would default to toggle, and the manual still states that "[i]f no argument is given, floating mode is toggled."

You're right, thanks for reporting this issue. I've addressed it in PR #738.

> ```
> $ herbstclient floating 6
> invalid argument: only on/off/true/false/toggle are valid booleans
> ```

I've tested this in the old version. There, it simply didn't do anything (the floating state of `6` stayed unchanged). So I think printing an error message is better than nothing. This is also consistent with the documentation
```
floating [[TAG] on|off|toggle|status]
```
where the `[`-`]`-pair states: if one argument passed, then it is one of `on`, `off`, `toggle`, or `status`.
