### ISSUE TITLE
Fix install dir for bash completion in CMakeLists.txt

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#736]
```
set(BASHCOMPLETIONDIR ${CMAKE_INSTALL_SYSCONF_PREFIX}/bash_completion.d
    CACHE PATH "Install path for bash completions file")
```
I think installing the bash completion to `/etc` is wrong. Already in the arch package for 0.7.2 it is installed to
```
/usr/share/bash-completion/completions/
```

**Comment by ThibautMarty** [comment]
I think /etc/bash_completion.d is (was?) the standard directory for bash completion files (it is cited in the man page), but Arch may override it to align with other shells.
The `CMAKE_INSTALL_SYSCONF_PREFIX` is only used for here bash completion and never seen this variable.
We may copy what other packages do. For instance, I found alacritty that uses CMake and produces bash completion files.

**Comment by blarz** [comment]
Seems like every shell now wants its completion files somewhere else..
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843573
(although that bug is quite old)

**Comment by t-wissmann** [comment]
> Seems like every shell now wants its completion files somewhere else..
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843573
> (although that bug is quite old)

The directory for the zsh completion was updated recently by PR #600. iirc, the contributor didn't use herbstluftwm, but was active for the zsh people, so I assume that new path (which is slightly different `site-functions` instead of `vendor...`) is correct.
