### ISSUE TITLE
labels on keybinds

### ISSUE THREAD

**Issue by uzsolt** [herbstluftwm/herbstluftwm#742]
I discovered the `keymask` which is a great feature (imho).
It would be more useful if can label the keybinds (as rules) too and can filter this labels and not only the hotkey.

**Comment by t-wissmann** [comment]
Hm I never thought about thids. Do you think this label should be unique (as for rules) or can multiple keys have the same label?

**Comment by uzsolt** [comment]
I have the following idea: with it can easily create keychains.
The first keybind will open (and focus) a specified window (client, maybe scratchpad-like) and only the "keychain-1" keybind_s_ will be active.
In the normal situation "keychain-.*" are inactive (or "non-keychain.*" are active).

So I think the label should be _not unique_ and maybe "label" isn't best terminology (the "tag" or "group" or similar would be better).

**Comment by uzsolt** [comment]
Ah, sorry, one more idea: a herbstluftwm-command which activite or de-activite (group of) keybinds.

**Comment by t-wissmann** [comment]
hm but then: wouldn't it be easer if herbstluftwm did directly support keychains?

**Comment by uzsolt** [comment]
It would be _the_ easiest :)

(Maybe I remember wrong but some years ago (before hlwm's github) on mailing list somebody suggested keychain-support too but you said maybe later (when you'll have time))

**Comment by t-wissmann** [comment]
you're right, I was reluctant to implement keychains directly. But I think it makes sense to implement it directly. I think it would be more complicated to implement labels with a consistent interface. So I suggest to dismiss this proposal and put key chains on the agenda instead (see issue #751).
