### ISSUE TITLE
What are hookable attributes?

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#749]
Many attributes in the object tree are marked hookable, but I don't see any hook firing when they change (or any other way of using them). Why these?

**Comment by t-wissmann** [comment]
It's a planned feature (and some code is already hidden in the code base) to activate hooks for those attributes. E.g. if your interested in changes of `clients.focus.floating`, then you can "listen" for it and will then will see hooks fireing whenever it changes.

It's not yet clear to me whether hooks for such attributes are activated globally (i.e. all `hc --idle` get updates) or whether this should be a setting per `hc --idle` process.

**Comment by tiosgz** [comment]
Ah, thanks!
