### ISSUE TITLE
Run or raise [Feature request]

### ISSUE THREAD

**Issue by neg-serg** [herbstluftwm/herbstluftwm#77]
Please, add example, or bring to distributive script which provide run-or-raise support.

If you do not know what is it look here:

1) You can search window by class / instance / role / name
2) If it is finded you will focus(select) it
3) If not new window is created

I've seen tags support for herbstluftwm also. It is about something like this:

1) Consider we have { Firefox, Chromium, Conkeror } with tag = w
2) Then we can implement tag-based circle jumps over windows:
     Firefox -> Chrome -> Conkeror -> Firefox -> ...

This  feature should be nice with stuff like games, or another similar use cases.

**Comment by t-wissmann** [comment]
Are you satisfied with this script?
```bash
#!/bin/bash -e
# this script requires:
#
#   - A running herbstluftwm instance
#   - herbstclient
#   - xdotool

prog="$0"
usage() {
    echo "Usage: $prog PROPERTY VALUE [CMD..]"
    echo ""
    echo "This tries to a window whose PROPERTY equals VALUE."
    echo "If such a window is found, it is focused using »herbstclient jumpto«."
    echo "If not, the given programe CMD is executed."
    echo ""
    echo "PROPERTY is one of:"
    echo "  class (the first entry of WM_CLASS)"
    echo "  classname (the second entry of WM_CLASS)"
    echo "  name (the window title)"
    echo ""
    echo "Example: $prog class Firefox firefox"
}

insufficient_arguments() {
    echo "Insufficiently many arugments." >&2
    usage >&2
    exit 1
}

property="$1" ; shift || insufficient_arguments
value="$1" ; shift || insufficient_arguments
if winid=$(xdotool search  --all --maxdepth 2 "--$property" "$value") ; then
    for i in $winid ; do
        herbstclient silent jumpto $(printf "0x%x\n" "$i") && break
    done
else
    if [ -n "$*" ] ; then
        # only 
        "$@" &
    fi
fi
```

**Comment by t-wissmann** [comment]
I think the question has been answered. If there is anything left, feel free to (re-)open this or another issue.

**Comment by wdouglass** [comment]
I found this script to be incredibly useful, can it be added to the repository, perhaps as `scripts/run-or-raise.sh`?

This was a feature i used heavily under stumpwm -- there are a lot of great reasons to move to herbstluftwm from stumpwm, and this script closes the gap even further!
