### ISSUE TITLE
Missing 'install' target (0.8.0)

### ISSUE THREAD

**Issue by Nairou** [herbstluftwm/herbstluftwm#778]
I'm attempting to update the herbstluftwm package for the Linux distro I use (Void), and am running into an issue during installation.

The 0.7.2 makefile has an 'install' target, but the 0.8.0 makefile is missing this.

```
make: *** No rule to make target 'install'.  Stop.
```

I also checked the PKGBUILD file for the Arch AUR package for 0.8.0, but that too uses "make install" on a makefile without an install target.

**Comment by t-wissmann** [comment]
0.8.0 now uses cmake, so the installation is:
```
mkdir -p build && cd build
cmake ..
make
make install
```
The makefile in the root directory of the repository is only a convenience wrapper around the first steps above. In a package one should use the cmake

**Comment by Nairou** [comment]
Thank you. That clarified enough for me to figure out what was missing.
