### ISSUE TITLE
No way to access monitor padding value

### ISSUE THREAD

**Issue by gayprogrammer** [herbstluftwm/herbstluftwm#78]
My use case is that I want dmenu to always match my panel.sh placement, whether it is at the top or bottom of the screen. 

The most obvious way for me to get this was `herbstclient get_attr monitors.focus.pad` but it does not exist. Is there any way to get the padding value for a monitor?

**Comment by The-Compiler** [comment]
You can use the `list_padding [monitor]` command to do so - I agree this should probably be an attribute on the monitor, but I'm guessing that'll happen anyways as part of the winterbreeze rewrite. Right, @t-wissmann @ypnos? :wink:

**Comment by ypnos-web** [comment]
Seems an obvious decision to make this an attribute, yes.

**Comment by ypnos** [comment]
Seems an obvious decision to make this an attribute, yes.

**Comment by t-wissmann** [comment]
Yes, it seems they're attributes now (I can't remember adding those, but they are even writable; it must have happend somewhen within the last 3½ years since this issue has been filed...)
