### ISSUE TITLE
One window in frame always shows border

### ISSUE THREAD

**Issue by bernerha** [herbstluftwm/herbstluftwm#803]
With version 0.8 the border around a single window in a single frame always get displayed.
The version before behaved different. The border only get showed if more than one window was visible in a frame.

Is this a bug or a fix?

Regards

**Comment by t-wissmann** [comment]
You're right, the setting `smart_window_surroundings` is ignored in 0.8.0. This is indeed a bug, thanks for the report!

**Comment by blarz** [comment]
Weird, shouldn't tests/test_layout.py::smart_window_surroundings test exactly that?

**Comment by t-wissmann** [comment]
> Weird, shouldn't tests/test_layout.py::smart_window_surroundings test exactly that?

Took me a while to see it: this test only checks that the `window_gap` is applied correctly but does not check the `border_width`.

**Comment by t-wissmann** [comment]
Fixed by #807.

**Comment by bernerha** [comment]
Nice, thank you. Do you plan to create a release at any time?

**Comment by t-wissmann** [comment]
Yes, there are two open pull requests with bugfixes which I will merge soon. And then, I think it's the perfect occasion for another release.
