### ISSUE TITLE
0.8.0 panel detection config option?

### ISSUE THREAD

**Issue by ZoeFiri** [herbstluftwm/herbstluftwm#815]
I use lemonbar and my bar is configured to show at the bottom of my screen which I have padded for it, although unfortunately the new 0.8.0 update's panel detection feature appears to not be aware of where the bar is located which creates a large pad at the top of my screen. This is increasingly problematic since I use lemonbar to create visual notifications which only last for a couple seconds, but will pad the top of my screen even after they're gone. Is there a way to simply disable this? I've included an image for reference.
![image](https://user-images.githubusercontent.com/27149384/79593919-c4ea4980-80a1-11ea-8ccc-1208ee86f258.png)

**Comment by ypnos** [comment]
So are these temporary panels that show notifications located at the top or at the bottom?
In other words, is the padding correct for these notifications?

Apart from that it looks like two/three issues:

- Automatic padding is always applied, even if padding was previously set manually
- No option to disable automatic padding
- Unregister seems not to work for your panel

As a "simple" workaround right now what you can do is use herbstclient to reset the padding in the script that shows your notification (after the panel appearance).

**Comment by t-wissmann** [comment]
With the lemonbar here, `lemonbar -b` correctly sets up the pad at the bottom.
Do you have your lemonbar script somewhere public such that I can try it? If not, how are you calling lemonbar? with `-b` or simply with the geometry?

I think it's reasonable to add a setting that allows disabling the panel detection, just to be on the save side.

Nice bar by the way :-) I didn't recognize that it's `lemonbar`!

**Comment by t-wissmann** [comment]
By the way, lemonbar also provides an option `-d` with which you can disable the panel detection.

For completeness, I also added a setting for controlling the detection in the PR #832.

**Comment by ZoeFiri** [comment]
@t-wissmann haha thanks, it's kinda a hacky combination of a lot of lemonbar instances, which may be why it doesn't allocate things right. I'm calling lemonbar with geometry for more finely tuned control.
@ypnos neither. the "notification" shows up briefly at the center of my screen and disappears shortly after. I'll try the hc pad after workaround, thanks.

**Comment by t-wissmann** [comment]
> @t-wissmann haha thanks, it's kinda a hacky combination of a lot of lemonbar instances, which may be why it doesn't allocate things right. I'm calling lemonbar with geometry for more finely tuned control.

You're welcome, thanks for the script! If you only pass the geometry via `-g` but don't add `-b`, then lemonbar still thinks it's at the top of the screen and allocates the space there, so I think adding `-b` to the lemonbar calls should fix the problem. And if it still exists, I think adding `-d` definitely will fix it.

**Comment by ZoeFiri** [comment]
Yeah -d will probably be fine, honestly I preferred the old system of manually padding the monitor to whatever specification so I think I'll stick with that.
