### ISSUE TITLE
Command 'bring' is broken

### ISSUE THREAD

**Issue by 45jqlakjrf87ayte7hy34ter4nguijauzl4eitk** [herbstluftwm/herbstluftwm#818]
Bring works in 7.2 but not 8.0 or current git

**Comment by blarz** [comment]
What exactly does not work? I can use
`herbstclient bring 0x3600009`
and it brings the window to the frame and focuses it here.
There are also quite some tests to verify that bring does what it should.

Maybe we missed a use case?

**Comment by 45jqlakjrf87ayte7hy34ter4nguijauzl4eitk** [comment]
Doing the same certainly does not work on my machine. Neither with my own builds nor Debian's unstable package.

**Comment by t-wissmann** [comment]
What happens if you run `bring` from the command line? is there an error message?

**Comment by 45jqlakjrf87ayte7hy34ter4nguijauzl4eitk** [comment]
`herbstclient bring`
> bring: not enough arguments

`herbstclient bring asdf`
> bring: Could not find client "asdf".

`herbstclient bring  0x0120000` is silent and does nothing.

The shipped wselect.sh script does nothing.

**Comment by The-Compiler** [comment]
FWIW both `bring` and `wselect.sh` work just fine for me on herbstluftwm 0.8.0 (85367b40 built on 2020-04-17)

**Comment by 45jqlakjrf87ayte7hy34ter4nguijauzl4eitk** [comment]
It does seem to work if the window being brought is not on the current tag.

**Comment by The-Compiler** [comment]
Huh, that's the whole point of `bring` though, no?

**Comment by 45jqlakjrf87ayte7hy34ter4nguijauzl4eitk** [comment]
I almost never use tags, personally. My windows are just maximized buffers that get called to whichever frame I currently want to work in.

**Comment by blarz** [comment]
> Huh, that's the whole point of `bring` though, no?

Documentation says
> Moves the specified window to the current frame and focuses it.

This does not seem to be true. If I create a new frame and "bring" a client from the new frame to the old frame, it does not work. As @45jqlakjrf87ayte7hy34ter4nguijauzl4eitk already stated, only if the client is on a different tag, the client is "brought" to the current frame.

Either this is expected behavior, in that case, the documentation should say so.
Or it is actually a bug that should be fixed, i.e. it should be possible to bring a client from one frame to another on the same tag.

**Comment by blarz** [comment]
`layout.cpp::frame_current_bring` uses `global_tags->moveClient(client, tag, {}, true);` which in turn simply returns if `if (tag_source == target`. So that's that.

Let's see what @t-wissmann has to say.

**Comment by t-wissmann** [comment]
Sorry for breaking your workflo!
I wasn't aware anymore that `bring` also moves the client to the focused frame. So I'd say it's a bug that has to be fixed (but only in the `frame_current_bring` not in `moveClient`).

**Comment by blarz** [comment]
Thank you for your report @45jqlakjrf87ayte7hy34ter4nguijauzl4eitk!
This is now fixed in the current git version.
