### ISSUE TITLE
Used indices/tags in panel with multiple monitors

### ISSUE THREAD

**Issue by AckslD** [herbstluftwm/herbstluftwm#819]
The default panel shows nicely the indices which are not empty by making the number white instead of gray. However if the index is focused in another monitor it looks the same as if it's an empty unfocused index. For example in the picture below, index 1 has a window and is focused in the other monitor, index 3 of focused in the current monitor and index 2 has a window but not focused in any monitor:
![Screenshot from 2020-04-18 13-48-21](https://user-images.githubusercontent.com/23341710/79636918-8e80fd00-817b-11ea-831a-3a7dd757e536.png)

Is it possible to have the panel show that an index is focused in another monitor? Maybe filled, lighter green or gray

**Comment by tiosgz** [comment]
You can have this if you add another case with different colours for `%` (focused) and `-` (unfocused) in the `case` starting at line 96.

**Comment by AckslD** [comment]
Perfect! I added `-`, thanks @tiosgz
