### ISSUE TITLE
Recommendations for showing battery, volume etc

### ISSUE THREAD

**Issue by AckslD** [herbstluftwm/herbstluftwm#820]
I tried to add battery and volume status to the panel myself. It does work and shows what I want but I'm experiencing some hangs/freezes from time to time which I think is do to what I added and that it probably gets queried to often. My computer hangs for a second or two sometimes but when I remove what I added to panel.sh it seems to not happen anymore, at least so far.

What I did is to add the following to functions
```sh
# Get volume
GetVolume () {
    volume_on=$(amixer sget Master | grep -oE '\[on\]')
    if [ "$volume_on" == "" ]; then
        volume_level="^fg(#909090)off"
    else
        volume_level=$(amixer -D pulse get Master | grep -oE 'Front Left:.*' | grep -oE '[0-9]{1,3}%')
    fi
    volume="^bg()^fg()Volume: $volume_level"
    echo $volume
}

# Get battery
GetBattery () {
    percent=$(acpi | grep -oE '[0-9]{1,3}%')
    if [ "${percent::-1}" -lt "15" ]; then
        battery_color="^fg(#b10e03)"
    else
        battery_color="^fg()"
    fi
    discharging=$(acpi | grep -oE 'Discharging')
    if [ "$discharging" == "" ]; then
        battery_color="^fg(#8cb11e)"
    fi
    battery="^bg()^fg()Battery: $battery_color$percent"
    echo $battery
}
```
the following to lines
```sh
echo -e "volume\t$(GetVolume)"
echo -e "battery\t$(GetBattery)"
```
in the event loop generator next to the command getting the time.
Furthermore I also added the following two cases to the event handler:
```sh
            volume)      
                volume="${cmd[1]}"                   
                ;;
            battery)
                battery="${cmd[1]}"
                ;;          
```

which shows the following in the panel
![Screenshot from 2020-04-18 14-37-59](https://user-images.githubusercontent.com/23341710/79637748-3dc0d280-8182-11ea-8c62-ca0f8c9f69be.png)
(the battery turns green when power is plugged in and red below 15 %)
But as mentioned it seems to freeze my computer from time to time. Any advice on how to do this better?

**Comment by The-Compiler** [comment]
I'd recommend switching to [barpyrus](https://github.com/t-wissmann/barpyrus) instead, FWIW.

**Comment by AckslD** [comment]
@The-Compiler ah cool, thanks I'll check that out

**Comment by t-wissmann** [comment]
I'm also using barpyrus, and on some setups I have an (additional) xfce4-panel or lxpanel

**Comment by vlada-dudr** [comment]
For battery I do this:
```
. /sys/class/power_supply/$batt_name/uevent
batt_perc="$(( POWER_SUPPLY_ENERGY_NOW * 100 / POWER_SUPPLY_ENERGY_FULL))"
```

**Comment by AckslD** [comment]
I'm using barpyrus now so this can be closed
