### ISSUE TITLE
command to move window to prev/next monitor

### ISSUE THREAD

**Issue by nyanpasu** [herbstluftwm/herbstluftwm#83]
We have things like `move_index INDEX` to move to tags relatively, it would be nice if we also had a command to move focused windows to different monitors

**Comment by t-wissmann** [comment]
There is
```
shift_to_monitor MONITOR
```
where `MONITOR` can be a name, an absolute or a relative monitor index, see the [MONITORS](http://herbstluftwm.org/herbstluftwm.html#MONITORS) section in the man page. It even allows `-r` and `-l` for addressing the monitor on the right or left.

**Comment by nyanpasu** [comment]
Aah, that was what I was looking for. Thanks.
