### ISSUE TITLE
fullscreen hook

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#845]
According to the old code (and the man page), the `fullscreen` hook is fired whenever the fullscreen state of a client changes. There are two options:
* Implement it again, by attaching to the `changed()` signal of the fullscreen attribute of every client
* Keep it dropped because I'm not aware of any scenario where this is useful.

**Comment by blarz** [comment]
Easiest way would be to just remove it from the documentation and see if anybody cares?

**Comment by keithhub** [comment]
I like to automatically disable screen blanking when a full screen window is visible (and enable it again when there are no visible full screen windows). Without this hook I'm not sure how to accomplish that.
