### ISSUE TITLE
keepassxc autotype window not showing up

### ISSUE THREAD

**Issue by sputnik95** [herbstluftwm/herbstluftwm#849]
Hi! Thank you for developing the new version, loving it so far. Especially the ability to put single windows on a floating layer, that's a feature I've long waited for on hlwm!  

I've noticed a problem with keepassxc not showing it's global autotype window on a new version. 
To reproduce the problem one needs to:  
1. Save credentials into keepassxc database
2. Add matching window title pattern for said credentials
3. Visit the log-in page with window title pattern defined in step 2
4. Invoke autotype window with a keybinding  

Expected result: autotype window shows up:
![autotype_window](https://i.imgur.com/O8t1UEz.png)

Version of keepassxc this bug can be reproduced on: 2.3.4
Version of herbstluftwm: 0.8.1
Autotype window properties reported by xprop:
<details>
  <summary>Collapsed</summary>
<pre>
  WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE
_NET_WM_DESKTOP(CARDINAL) = 1
_NET_WM_USER_TIME(CARDINAL) = 249531123
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE
WM_TRANSIENT_FOR(WINDOW): window id # 0x1000008
_NET_WM_ICON_NAME(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "Auto-Type - KeePassXC"
_NET_WM_NAME(UTF8_STRING) = "Auto-Type - KeePassXC"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x26, 0x1e, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x1000008
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 25382
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16777315
WM_CLASS(STRING) = "keepassxc", "keepassxc"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST, _NET_WM_CONTEXT_HELP
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 436, 262
		user specified size: 492 by 242
		program specified minimum size: 180 by 143
		window gravity: NorthWest
</pre>
 _NET_WM_ICON ommited for brewity
</details>

Please let me know if you need more input information.

**Comment by t-wissmann** [comment]
> Hi! Thank you for developing the new version, loving it so far. Especially the ability to put single windows on a floating layer, that's a feature I've long waited for on hlwm!

Great to hear that!

> 4. Invoke autotype window with a keybinding

How can I do this? Do I have to configure a keybindings in keepassxc that is bould globally then? Or is this a certain command I have to run?

**Comment by sputnik95** [comment]
> > 1. Invoke autotype window with a keybinding
> 
> How can I do this? Do I have to configure a keybindings in keepassxc that is bould globally then? Or is this a certain command I have to run?

Yes, this keybinding is set in keepassxc's settings in 'Tools -> Settings -> General -> Auto-Type' form. 
I have mine set to ctrl+alt+p:
![auto-type settings](https://i.imgur.com/mNRS4rq.png)

Example of credentials with a window title pattern added:
![example1](https://i.imgur.com/Bv3wAfA.png)
![example2](https://i.imgur.com/Qh08lsn.png)
It should work on [this](https://wiki.archlinux.org/index.php?title=Special:UserLogin&returnto=Main+page) page.

Interesting thing is that if database is locked, password prompt window does show up after hitting ctrl+alt+p, but autotype selection window still doesn't.

**Comment by t-wissmann** [comment]
I can reproduce it: When hitting Ctrl+Alt+P, I am prompted for the password of the keepassxc store, but the next window does not show up. This issue does not seem to arise in herbstluftwm 0.7.2.

In hlwm 0.7.2, the main loop receives a ClientMessage, whereas in the current hlwm, no event comes in.

A first guess: Maybe this has something to do with the EWMH-WM-Window, maybe the client message is sent there and we don't listen for it...

**Comment by t-wissmann** [comment]
My first guess was wrong, but I've found the issue:
This issue was present in hlwm before and has been fixed in a50457335091cd990d0146e5008ca3b3db1cc574, however, I didn't sincerely adapt this to the new codebase and accidentally changed the type again to XA_CARDINAL.

**Comment by t-wissmann** [comment]
Fixed by c3fcc11 (#851).

**Comment by t-wissmann** [comment]
Thank you for the precise report of this issue :-)

**Comment by sputnik95** [comment]
This is great to hear! Thank you very much for looking into this!
