### ISSUE TITLE
close_and_remove closes wrong window for single window floating clients

### ISSUE THREAD

**Issue by cnotis82** [herbstluftwm/herbstluftwm#853]
Steps to reproduce:

- 2 windows in tiling mode

- Make one of them floating

- Execute "close_and_remove" on floating window closes the window in tiling, the floating window cannot be closed.

**Comment by t-wissmann** [comment]
You can still close the floating window with the `close` command. But in general you are right: `close_and_remove` and `close_or_remove` should behave like `close` when a floating window is focused.
