### ISSUE TITLE
Debug window title rule

### ISSUE THREAD

**Issue by AckslD** [herbstluftwm/herbstluftwm#905]
I'm trying to set a rule based on the title of a gnome-terminal and am wondering what's the best way to debug this. Can I in some way check what the title actually is, since it's not being applied.

I have the following key-command:
```sh
hc keybind $Mod-o spawn gnome-terminal -e 'zsh -c "cd && fzf | xargs -r xdg-open"' --title=fzfopen
```
to quickly open a file.

(Btw, I know that some people use `st` or something for things like this because it's faster but I don't see any delay with `gnome-terminal` so thought I would just go for that since I already have it.)

And I would like this window to pseudotile:
```sh
hc rule title=fzfopen pseudotile=on
```
which is not applied. However, the barpyrus panel from @t-wissmann does show the title correctly as `fzfopen`.

As a follow-up question, I would ideally want my "normal" gnome-terminal to always open in tag 1, however I would like the above command to open wherever I am. Is there a way to achieve this?

Thanks in advance!

**Comment by t-wissmann** [comment]
Several attempts:
1. Does the window turn into pseudotile when running the following command after the window opened?
```
herbstclient apply_rules --all
```
(you need  herbstluftwm >= 0.8.0 for this)

2. Maybe the title is only set when the window is already shown, but that is just a guess. You could try setting another window property, e.g. the window role. According to the [gnome-terminal man page](http://manpages.ubuntu.com/manpages/focal/en/man1/gnome-terminal.1.html), the syntax is `--role=fzfopen` and the rule syntax then is:
```
hc rule windowrole=fzfopen pseudotile=on
```

3. Maybe a general thing: Do you know [rofi](https://github.com/davatorium/rofi)? fzf is essentially the in-terminal adaption of rofi

4. If you have herbstluftwm >= 0.8.0, maybe `floating=on` suites you better than `pseudotile` (but this does not solve your actual question of course)

**Comment by AckslD** [comment]
Hey @t-wissmann! Thanks for you reply!

Indeed, setting the `role` instead works.

Regarding floating, ah I see! I was still on 0.7.2 so didn't realise that this was possible.

I heard about rofi but haven't looked into it. You think it's better for this purpose?

**Comment by t-wissmann** [comment]
> I heard about rofi but haven't looked into it. You think it's better for this purpose?

Oh, I totally forgot to answer you, sorry! Yes, I think rofi is much better for this purpose! I even had written this using rofi for my own purposes some years ago:

https://github.com/t-wissmann/dotfiles/blob/master/menu/rofi-file-open.sh

**Comment by AckslD** [comment]
@t-wissmann No problem, I did started using rofi after that :)

**Comment by t-wissmann** [comment]
If I see it correctly, all questions have been answered. If I missed one, please feel free to re-open this ticket!
