### ISSUE TITLE
Mapping plus

### ISSUE THREAD

**Issue by Chinggis6** [herbstluftwm/herbstluftwm#92]
Hello,

I'm switching from [i3](https://github.com/i3/i3).
I could map plus as "plus" in i3 to switch to the 12th desktop (tag) (<kbd>Shift</kbd>+<kbd>+</kbd>).

Although I could map - as "minus" to the 11th, but I couldn't map the plus sign as "plus" in herbstluftwm.

Moreover, I would also like to know the character names for "[" and "]" block parantheses to use in `herbstlufvm` config as substitute for the default "<" and ">" arrows to cycle through the tags.

Thanks in advance.

**Comment by hexid** [comment]
You can map `[` as `bracketleft` and `]` as `bracketright`.

For `+`, you will want `equal` as that is the non-shift character on the keyboard.

You can find other names in `/usr/share/X11/xkb/symbols/us`

**Comment by Chinggis6** [comment]
Thank you, it solved the issue.

**Comment by The-Compiler** [comment]
Let's close it then :wink:
