### ISSUE TITLE
Window swallowing

### ISSUE THREAD

**Issue by BeTmAsTeR** [herbstluftwm/herbstluftwm#925]
What about  adding "window swallowing" to hlwm like this dwm patch?
https://dwm.suckless.org/patches/swallow/

Description:
"This patch helps users spawning a lot of graphical programs from their command line by avoiding cluttering the screen with many unusable terminals. Being deep down in a directory hierarchy just does not make the use of dmenu feasible."

it would be very useful

**Comment by BeTmAsTeR** [comment]
usage example: https://youtu.be/92uo5OBOKfY?t=160

**Comment by erooke** [comment]
Depending on your workflow you can fake this feature using frame layouts. If you set your frame layout to max any newly spawned windows will cover the whole frame. So if your terminal is the only thing in the frame and you spawn a program from it you will cover the terminal. 

Differs from frame swallowing in a couple of ways, but if your workflow is like mine where you tend to only have one window per frame its a workable stopgap.

**Comment by t-wissmann** [comment]
I think this is a very useful feature, but  I'm a bit reluctant to hide windows entirely. One solution would be to implement window minimization and then the "parent" window would be automatically minimized & unminimized to create this 'swallowing' effect.

Also I'm not sure what should happen if the parent window creates another child window (e.g. running `xclock & mpv` from a terminal). Should the parent window stay hidden until all of the child windows disappear?

**Comment by tiosgz** [comment]
> I'm a bit reluctant to hide windows entirely

You already do this with `hide_covered_windows`. If you see a problem in that the parent is inaccessible until you close the child, you can add a command to show it (which could be useful anyway).

**Comment by t-wissmann** [comment]
> > I'm a bit reluctant to hide windows entirely
> 
> You already do this with `hide_covered_windows`. If you see a problem in that the parent is inaccessible until you close the child, you can add a command to show it (which could be useful anyway).

Yeah, with 'hiding entirely' I meant making them entirely inaccessible for the user (which is not the case for `hide_covered_windows`). Such a command to show the parent window would be the "unminimize".

Additionally, I think it makes sense to implement the minimization anyway and it's roughly the same work as directly hacking the window swallowing into hlwm.

**Comment by BeTmAsTeR** [comment]
maybe just add the minimization feature and let users create support scripts for windows swallowing and similar features

**Comment by The-Compiler** [comment]
As for minimization: Couldn't that already be implemented (maybe in a hackish way) by having a tag with a custom `invisible` attribute or whatever, and then configuring your panel to not show that tag?

**Comment by BeTmAsTeR** [comment]
I already implemented this in my workflow by using [xdo](https://github.com/baskerville/xdo) "hide" action, works really well but a native functionality would be better in my opinion

**Comment by t-wissmann** [comment]
@BeTmAsTeR: the git version now supports window minimization natively, maybe you can use this already to accomplish the window swallowing by minimizing the terminal. (Maybe a keybinding like
```
hc keybind $Mod-Shift-m set_attr clients.focus.minimized toggle
```
is already enough to do it manually)

**Comment by BeTmAsTeR** [comment]
this is awesome, THANK YOU ALL

**Comment by t-wissmann** [comment]
Does this cover your use case already? (By the way: now you can also un-minimize clients in a fifo or stack order with keybindings). If it solves the issue for you, we can close this issue.

**Comment by noctuid** [comment]
tdrop supports [a similar functionality](https://github.com/noctuid/tdrop#auto-hiding) for any wm. You can automatically hide a window when opening a picture or video, for example, and then automatically show the window again when closing the media file. It also works for floating windows (and can restore their geometry on show). Tdrop may be useful for someone who wants this automatically.

There are some disadvantages of the hide/minimize method though:
- Requires some extra setup (shell aliases for media players; extra configuration in file openers)
- Things can look a little glitchy as one window is hidden and the other appears, and the layout could be changed with certain confgiurations; the layout is retained in dwm with real swallowing

As for the glitchiness, maybe there is some way to lock redraw and then only unlock once the new window is created?
