### ISSUE TITLE
Switch to GitHub actions?

### ISSUE THREAD

**Issue by The-Compiler** [herbstluftwm/herbstluftwm#930]
I switched [pytest-xvfb](https://github.com/The-Compiler/pytest-xvfb) to GitHub Actions today - should we do the same for hlwm?

Why:

- [Nice syntax](https://github.com/The-Compiler/pytest-xvfb/blob/master/.github/workflows/main.yml) and lots of possibilities
- [Good documentation](https://help.github.com/en/actions)
- [Beautiful output](https://github.com/The-Compiler/pytest-xvfb/runs/754819447)
- Nice integration with GitHub

Why not:

- No official C++ support so far, but [Docker support](https://help.github.com/en/actions/creating-actions/creating-a-docker-container-action) - just not sure if we can make it work with how we use Docker in `.travis.yml` currently.

**Comment by t-wissmann** [comment]
In principle, I don't care what we use; instead of optimizing the workflow, I'd rather like to optimize hlwm itself. Usually, I'm only changing the CI setup if there is something that annoys me while working on hlwm. If you or someone else really wants to switch to Github Actions, it's fine for me because I don't care to much as long as it does not cause additional work for me.

**Comment by dnnr** [comment]
Thanks for your input, @t-wissmann. I think that's totally fair.

@The-Compiler Unless you're keen on doing it yourself, I'd be happy to pick this up, but I probably won't get to it anytime soon.

**Comment by The-Compiler** [comment]
FWIW I am annoyed by Travis' slowness (both the workers and the website) - but mostly for qutebrowser, since I don't work on hlwm much nowadays. I might be able to pick this up, but it might also take a while. I'll certainly migrate qutebrowser first and see how that goes!

**Comment by The-Compiler** [comment]
Another nice feature (IMHO): [Problem matchers](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md) can be used to make compiler errors (or linting output) show as part of the GitHub website:

![image](https://user-images.githubusercontent.com/625793/85578553-71185580-b63a-11ea-85a7-f5b404f46bb7.png)

There's one [for GCC](https://github.com/ammaraskar/gcc-problem-matcher) - not sure if it'll work with clang-* as well, but it's easy enough to define our own regexes if needed.

**Comment by blarz** [comment]
@t-wissmann did the switch and it is looking good so far

**Comment by t-wissmann** [comment]
I'd say this can be closed because we fortunately did the migration :-) ... and the interface is indeed much better compared to travis!
