### ISSUE TITLE
Multi virtual monitors positions dialog half outside

### ISSUE THREAD

**Issue by wilriker** [herbstluftwm/herbstluftwm#932]
ArchLinux, HLWM 0.8.3

I am not certain if this can even be logically detected but here is my setup:
I have a 4K monitor split into two HLWM logical monitors 1920x2160 each. Whenever a dialog appears it will render half outside the right edge of the current HLWM monitor. The reason is simple: the dialog requests physical screen size to calculate the center but once it will be placed by HLWM this means it's offset by and limited to the logical monitor position and size.

There is only one standard rule concerning dialogs I have
```
label=1 windowtype~_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)  pseudotile=on
```

Being a programmer myself I can see the problem of detecting the difference between "this dialog wants to be placed in the middle but falsely uses physical screen size" and "this dialog intentionally wants to be rendered half outside of the monitor". But is there anything I can do about it? Any rule I can apply? I don't mind if the unprobably event happens where the dialog _wants_ to be outside of the screen - I will pull it into the screen nevertheless.

**Comment by tiosgz** [comment]
Maybe you want also `floating=false` to actually apply the pseudotile? Otherwise I don’t know of any better way.

**Comment by wilriker** [comment]
Thanks, that definitely improved the situation.

Maybe as a future enhancement: would it be possible to get control over `WM_SIZE_HINTS`, especially the `user specified location`? This way one could overwrite it for floating dialogs since I do prefer it if they just appear above the application(s) instead of adding a new tile.

**Comment by wilriker** [comment]
I just looked at the source code:
`Client::resize_floating()` already makes sure that the floating window is at least 24px inside the monitor. Would it be possible to have a setting that instead makes sure that it is completely visible on the screen when first rendering the dialog but keep the 24px "grabable" minimum after that? I am not familiar enough with the source code (or X server in the first place) to know if the code has an understanding of initial rendering vs. re-rendering due to movement.

**Comment by tiosgz** [comment]
I think a floating window should be simply put into the center of the monitor or (if it has transient-for or what property) in the centre of its parent window. (Probably make this toggle-able?)

***

The 24px policy caused me some headaches recently when I was trying to move xclock in the padding area. Fortunately I was just playing and I don’t need it there.

**Comment by wilriker** [comment]
> I think a floating window should be simply put into the center of the monitor or (if it has transient-for or what property) in the centre of its parent window. (Probably make this toggle-able?)

I'd be very happy with that solution!

**Comment by wilriker** [comment]
@tiosgz Can you tell me where the code is that handles initial placement? I'd like to compile my own version until this has been introduced in HLWM officially.

**Comment by tiosgz** [comment]
> Can you tell me where the code is that handles initial placement?

I’m not sure as I haven’t written even a single line of all that code, but it seems it has something to do with `Client::fuzzy_fix_initial_position()` (`src/client.cpp`). But it’s better to ask one of the 5 masters here.
> I'd like to compile my own version until this has been introduced in HLWM officially.

I think they’ll welcome this change, at least if you make it toggleable.

**Comment by wilriker** [comment]
OK, so then who to summon via GitHub-mention to get some attention on this? ;-)

**Comment by t-wissmann** [comment]
Sorry for ignoring this thread for some time...

> Being a programmer myself I can see the problem of detecting the difference between "this dialog wants to be placed in the middle but falsely uses physical screen size" and "this dialog intentionally wants to be rendered half outside of the monitor". But is there anything I can do about it? Any rule I can apply? I don't mind if the unprobably event happens where the dialog _wants_ to be outside of the screen - I will pull it into the screen nevertheless.

There isn't anything built in right now to handle this. I think a reasonable way to fix it is to add another rule consequence called `within_monitor` (or something similar/better) which (if enabled) adjusts the floating position of a new window such that the window is entirely visible.

I'm not sure whether I'd hard-code it in `fuzzy_fix_initial_position()`... (probably not).

**Comment by wilriker** [comment]
I'd go with `centered` as a rule consequence. You can move it anywhere after that and center is where dialogs want to go most of the time anyway. I will accept whatever it is called as long as my dialogs stop appearing half-way outside of some monitor borders.

I was looking into `fuzzy_fix_initial_position()` and at the point where this is called the monitor is not yet determined and I have no idea what else it would affect if this is simply moved down after the monitor is known. I am just poking around in the code trying to get a simple intermediate solution. ;-)

**Comment by wilriker** [comment]
I had a look again and actually the monitor instance _is_ determined before `fuzzy_fix_initial_position()` is called so I just hacked it locally to pass the `Monitor* m` into the function and just hard-coded the initial position to be monitor center. Ugly but works for me until the official solution is available. :-)

**Comment by tiosgz** [comment]
> There isn't anything built in right now to handle this. I think a reasonable way to fix it is to add another rule consequence called `within_monitor` (or something similar/better) which (if enabled) adjusts the floating position of a new window such that the window is entirely visible.

Later this could be even something more crazy like `x=` and `y=` and units (`px` and `%`, or whole number=px and decimal number=%).
> I'm not sure whether I'd hard-code it in `fuzzy_fix_initial_position()`... (probably not).

Where does the initial positioning happen then? Or is it now just left where it is and only checked whether it’s in the monitor?

**Comment by wilriker** [comment]
> Where does the initial positioning happen then? Or is it now just left where it is and only checked whether it’s in the monitor?

It does happen inside `fuzzy_fix_initial_position()` and as you guessed it only makes sure that it is at least partially inside the monitor.

**Comment by blarz** [comment]
Does #957 improve the situation?

**Comment by wilriker** [comment]
@blarz #957 seems to solve my request. Thanks!
