### ISSUE TITLE
some programs take a long time to open

### ISSUE THREAD

**Issue by Pyrena** [herbstluftwm/herbstluftwm#939]
Hi,

I have this weird issue where a subset of programs takes a long time until they show up
on the screen.
Worst offenders are evolution, evince and gnome-calendar, taking upwards of 20 seconds.

When switching to i3 all of these show up instantly. Could this be an issue specific to herbstluftwm? I'm happy to provide any information required.

Best regards,

Daniel

**Comment by t-wissmann** [comment]
What's the output of these programs when you start them (e.g. evolution) in the terminal? (Especially what was their last output before the long wait?). Maybe it takes time for some gnome daemon to boot up, but it's just a guess.

After you have started evolution, does evince show up quicker? If not, does starting up evolution still take long?

**Comment by Pyrena** [comment]
Thank you for your reply, this has helped me to debug the issue!

In case someone else has the same problem, the issue is the same as the one described here: https://bbs.archlinux.org/viewtopic.php?id=230036

The root of the problem seems to be that I was somehow starting herbstluftwm wrongly. I'm using Solus as my distribution and therefore had to compile from source, and I'm also using lightdm to start herbstluftwm.
The thread suggested starting the windowmanager with dbus-launch. This seems to be somewhat of a hack and I don't know which implications this has, but changing my herbstlustwm.desktop to

`[Desktop Entry]
Encoding=UTF-8
Name=herbstluftwm
Comment=Manual tiling window manager
Exec=dbus-launch --exit-with-session /path/to/herbstluftwm/binary
Type=Application
`

resolved the issue for me. This is probably a non-issue for many users though, because herbstluftwm is available through most package managers.

Anyway, thank you for your help, I really enjoy using herbstluftwm so far!

**Comment by t-wissmann** [comment]
Thanks for providing the solution! Great to hear that you're enjoying hlwm :-)
