### ISSUE TITLE
tags.*.floating_focused shouldn’t be writeable

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#947]
…because setting it is ignored (just messes up the attribute).

Or, what was probably the original idea, respect setting it.

**Comment by Akinevz** [comment]
if you switch focus to a different tag (monitor) and then return, a floating window will be selected when `.floating_focused` is set. I achieve intended behaviour by locking, `cycle monitor; cycle monitor`, unlocking

**Comment by t-wissmann** [comment]
> Or, what was probably the original idea, respect setting it.

Yes, that's the actual solution.
