### ISSUE TITLE
Allow per-side border width and color configuration

### ISSUE THREAD

**Issue by krims0n32** [herbstluftwm/herbstluftwm#950]
I am coming from AwesomeWM and was wondering if it is possible to set window border properties on one side only (e.g. left) and if not if you could add this as a feature.

**Comment by krims0n32** [comment]
Here's an example of what it looks like (yellow border on the left = focused, black border on the left = unfocused)

![scrot_2020-07-07-104804](https://user-images.githubusercontent.com/661853/86752050-6351cf80-c03f-11ea-98cc-4e4882f3f0a1.png)

**Comment by t-wissmann** [comment]
```
herbstclient attr theme.border_width 0
herbstclient attr theme.padding_left 5
```

![border-only-on-the-left](https://user-images.githubusercontent.com/9048813/86753097-1de1d200-c040-11ea-8823-d6f0863b1550.png)

**Comment by krims0n32** [comment]
Perfect, thanks!
