### ISSUE TITLE
Drop-down terminals like tilda

### ISSUE THREAD

**Issue by linwaytin** [herbstluftwm/herbstluftwm#959]
The feature of single-window floating allows me to use drop-down terminals like `tilda`.
I use `hc rule instance='tilda' floating=on` to make the window floating and so it does not need to occupy the whole frame.
The problem is that I notice the window would show up first and immediately "shrink" to the correct size.
The process of "shrinking" is ~0.1s.
I guess this is due to the rule `floating=on` is applied after the window is created.

I'm curious if there is a simple way to make the window created as a floating window,
so that the window can show up smoothly.

**Comment by davidv171** [comment]
I might be misunderstanding your issue, but what is:
https://github.com/herbstluftwm/herbstluftwm/blob/master/scripts/q3terminal.sh
Missing? The solution with virtual monitors is way more flexible than something like tilda, as it is just a frame you can put anything in, as a dropdown.

**Comment by linwaytin** [comment]
I didn't notice this script before, and this is indeed similar to the way I take for now.
Thanks for pointing this out.

I still think the "shrinking" could be a problem, but that should be an separate issue.

**Comment by t-wissmann** [comment]
Thanks @davidv171 for pointing towards q3terminal.sh, and sorry I didn't do this before. I once tried to reproduce the issue with tilda, didn't succeed, and then forgot about this issue..
