### ISSUE TITLE
can't focus textfields in unmanaged dialogs

### ISSUE THREAD

**Issue by mrdrogdrog** [herbstluftwm/herbstluftwm#96]
OS: Arch Linux x64
hwm version: 0.7.0

I tried to create floating dialogs with 
`hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG)' manage=off`
but that results in dialogs I can't focus. Or I can't type into. There is no other rule for dialogs.

Reproduce:
- use this rule
- use a program that spawns a dialog with a textfield. like `zenity --password`
- You can press the buttons, but can't focus the passwordfield.

**Comment by The-Compiler** [comment]
That seems like the expected behavior to me - an unmanaged dialog is unmanaged, i.e. the window manager also won't take care of giving it focus.
