### ISSUE TITLE
Using bash functions / scripts inside builtin and/or/chain commands

### ISSUE THREAD

**Issue by Akinevz** [herbstluftwm/herbstluftwm#961]
Hi,

I'm trying to implement functionality where I run `hc cycle` if the current layout is `max` and `set_layout max` (without cycle) otherwise.
Can someone point me towards the correct syntax for running a bash function inside the `or` directive in the autostart file?

I currently have 
```bash
function is_max() {
    hc layout | grep 'FOCUS' | grep max && hc cycle
}
hc keybind $Mod-d or . is_max . set_layout max
```

I tried changing `is_max` to `spawn is_max` but neither seems to work. Is there a way to view logs for hwm / autostart?

**Comment by t-wissmann** [comment]
It is simply not possible to call bash functions from herbstluftwm. The best way is to call `bash` again from herbstluftwm:
```bash
herbstclient keybind Mod4-d spawn bash -c \
  '[[ $(herbstclient dump "" "@") =~ max ]] \
       && herbstclient cycle \
       || herbstclient set_layout max'
```
(Note that the `\` here are of two different levels: the first `\` is handled when the autostart is execued, whereas the other two `\` are passed to herbstluftwm and evaluated by the `bash` that is invoked when you press <kbd>$Mod+d</kbd>)

**Comment by Akinevz** [comment]
Ah! Thank you so much.

I've figured to just put those calls to hclient into a separate script in a local bin folder and just spawn the script. Spawning bash is a fantastic thought; if I understand correctly, I could generate these bash calls using a function? The backslashes seem intuitive and consistent.

I think that it would be good to add this to the main documentation. While researching scriptability I'd stumbled upon the 2012 mailing list posts about implementing the `or` / `and` / `chain` operators, which might lead a new user down the wrong path. Do I understand correctly that those are currently useful mostly just for `attr`ibute checking and such? I think it would be good to explicitly document which of the internal herbstluft commands return error codes, and in which cases

**Comment by t-wissmann** [comment]
> I've figured to just put those calls to hclient into a separate script in a local bin folder and just spawn the script. Spawning bash is a fantastic thought; if I understand correctly, I could generate these bash calls using a function? The backslashes seem intuitive and consistent.

The script in some folder is a clean solution! Of course, you can generate bash code in your autostart as you like. You should only be very careful while generating text that is eventually executed while having access to all your data.

> I think that it would be good to add this to the main documentation. While researching scriptability I'd stumbled upon the 2012 mailing list posts about implementing the `or` / `and` / `chain` operators, which might lead a new user down the wrong path. Do I understand correctly that those are currently useful mostly just for `attr`ibute checking and such?

Yes, the scripting abilities from `or` / `and` / `chain` are quite restricted and they best work with the data that's available in the object tree (i.e. `attr`).

> I think it would be good to explicitly document which of the internal herbstluft commands return error codes, and in which cases

Per default, every command exits with 0 on success and with something greater than 0 on some kind of error. You're right, that this isn't mentioned in the doc. However, the exit code is documented for the commands where the exit code 'matters'.

**Comment by t-wissmann** [comment]
By the way, there is now an attribute for the layout algorithm:
```
herbstclient attr tags.focus.tiling.focused_frame.algorithm
```
So one can now accomplish your key binding natively:
```bash
herbstclient keybind Mod4-d or : and '?' \
    compare tags.focus.tiling.focused_frame.algorithm '=' max \
    '?' try cycle : set_layout max
```

**Comment by Akinevz** [comment]
I've been waiting for this feature for ages, thank you so much for
implementing it!

I've originally meant to use hlwm to implement some complex tiling uis for
a touch interface (pseudo-widgets). It's a bit early to ask, but would you
object if I tried to monetise such a package in the future?

**Comment by t-wissmann** [comment]
> I've been waiting for this feature for ages, thank you so much for implementing it! I've originally meant to use hlwm to implement some complex tiling uis for a touch interface (pseudo-widgets). It's a bit early to ask, but would you object if I tried to monetise such a package in the future?

I think it's fine; good luck with it! (hlwm's license is very liberal; essentially you only need to cite the copyright correctly)

**Comment by t-wissmann** [comment]
I think all questions in this thread have been solved. If not, feel free to re-open.
