### ISSUE TITLE
emit framelayout_changed event when removing frames

### ISSUE THREAD

**Issue by bklaase** [herbstluftwm/herbstluftwm#968]
I update my panel based on changes in framelayout. I noticed that when calling for example `herbstclient remove`, or other actions that remove a frame, the event `framelayout_changed` is not emitted. It is, when creating frames. Is this intentional?

**Comment by t-wissmann** [comment]
I never noticed any `framelayout_changed` events, and the word `framelayout` does not even appear in the sourcecode. Do you have local changes?

In principle you are right, that some kind of events on layout changes are reasonable..

**Comment by bklaase** [comment]
wow, that was sloppy of me. I found the event so official sounding that I assumed it was build in.. :)

I only recently returned to hlwm with the great WinterBreeze merge, and had forgotten I emit these hooks myself. Sorry!
