### ISSUE TITLE
Crash with merge_tag command

### ISSUE THREAD

**Issue by ltobler** [herbstluftwm/herbstluftwm#97]
When calling `herbstclient merge_tag TAG TARGET`, herbstluftwm crashes when TARGET doesn't exist. Example with the default `autostart` file: `herbstclient merge_tag 9 foo`.

The crash only happens when TAG is not focused. In that case i get the expected error message:

```
merge_tag: Tag "foo" not found
merge_tag: Cannot merge the currently viewed tag
```

(PS: Is there an easy way to enable debug symbols and set optimization to O0 in the build system? I seem to be unable to figure it out ...)

**Comment by t-wissmann** [comment]
Thank you for reporting this issue!

Debug flags are enabled per default (you can find them in config.mk), and now optimizations are enabled per default. To be absolutely sure, you can compile with
```
make CXXFLAGS='-g -O0'
```
