### ISSUE TITLE
Support for keyboard layout independent keybinding?

### ISSUE THREAD

**Issue by CosmosAtlas** [herbstluftwm/herbstluftwm#972]
Is there a built-in way to manage herbstluftwm keybindings so that it's keyboard layout independent?

For example, in the Dvorak layout where the `s` key normally is the `o` key. So by pressing the `s` key on my qwerty keyboard, it would input `o` key as the keysym. However, since I often switch the keyboard layout when using the computer, when I in different layouts, with keysym only, the actual keybindings also change. 

Solutions to this problem I know:
- Reading keycodes instead of keysyms. -- Since keycode actually map to a physical key regardless of keyboard layout (i3, dwm (with patch))
- Fix the layout at start and ignore following keylayout switches (IIRC, sxhkd does this)

My temp solution for herbstluftwm:
Since all actions can be done using herbstclient, I can use sxhkd for keybindings which will avoid this problem. 

Anyway, I'm wondering if any functionality to achieve this is built-in herbstluftwm or is using sxhkd is the way to go for now.

**Comment by t-wissmann** [comment]
Yes,  binding to key codes would be a very reasonable feature!

**Comment by CosmosAtlas** [comment]
With the newly introduced `herbsclient`, I believe it offers the functionality that I originally hoped for. : )

For documentation purpose, if anyone want to use a *QWERTY* binding consistently, and maybe use another for typing (e.g., *DVORAK*).

With the power of *sxhkd*, you could do the following in the startup script.

```bash
# This will be the layout the keybindings work in
setxkbmap -layout us
# sxhkd by default ignores requests for changing mapping
setsid sxhkd &
# Add some delay to avoid race condition
sleep 0.5
# Setup the actual keybord you want to use
setxkbmap -layout us -variant dvp -option 'caps:ctrl_modifier'
```

I would like to restate my appreciated for the features added! Thanks @t-wissmann !

**Comment by bew** [comment]
Why close? Was this implemented?

**Comment by CosmosAtlas** [comment]
@bew I'm revisiting the issues I've opened. `sxhkd` is functioning well for me to manage herbsluftwm, and I don't really see myself regoing to the default even if the feature has been added.
