### ISSUE TITLE
Way of resetting tags / or: (bug?); workspaces retained from previous EWHM session 

### ISSUE THREAD

**Issue by bklaase** [herbstluftwm/herbstluftwm#973]
Weird behavior: when another user on my system has run an XFCE4 session, I get their workspace names as tags! I set mine  up using:

```bash
tag_names=( {1..9} )
tag_keys=( {1..9} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
	hc add "${tag_names[$i]}"
	hc floating "${tag_names[$i]}" off
	key="${tag_keys[$i]}"
	if ! [ -z "$key" ] ; then
		hc keybind "$Mod-$key" use_index "$i"   # go there without window
		hc keybind "$Mod-Shift-$key" move_index "$i" # send window there without following
		hc keybind "$Mod-Control-$key" chain , move_index "$i" , use_index "$i" # send window there and follow
	fi
done
```

Obviously this won't remove pre-existing workspaces (Workspace 1, Workspace 2, ...etc)
System uses lxdm. Restarting Xorg resolves this issue. But why do these workspaces "leak" into my session? Never seen this before with other WM's. Perhaps because you have the option to set workspaces declaratively (for example `bspc --reset-desktops 1 2 3 4 5 6 7 8 9 `). Being able to reset tags to a specific set on startup would help, but I am assuming this is not intended behavior?

**Comment by t-wissmann** [comment]
If information leaks, then guilty part is usually at the sending side, not the receiving side. My impression is, that on your setup your X-server (more specifically the root window) is not reset sufficiently when the other user logs out.
Recently, I implemented the hlwm feature that it imports the tags from a previous WM, which is quite handy if you switch between WMs or if you restart hlwm. You can supress the tag import by passing `--no-tag-import` to hlwm.

**Comment by bklaase** [comment]
excellent, that resolves the issue!
On your hypothesis, I'll check with a different  dm. I don't know enough about X's inner workings, but that sounds very plausible: wallpapers set with `feh` also (initially) bleed into other users sessions :/

Thanks for your quick response and great WM!

**Comment by t-wissmann** [comment]
Thanks for the feedback and for using hlwm :)
