### ISSUE TITLE
How to intercept through 'herbstclient -i' the event of a client that opens or closes?

### ISSUE THREAD

**Issue by paoloschi** [herbstluftwm/herbstluftwm#977]
I'm running herbstluftwm 0.8.3 officially packaged by VoidLinux

(I've only been using _herbstluftwm_ for a few days now so I don't yet know it in depth...)
When a client opens or closes, I notice that `herbstclient -i` notifies the event as if there had only been a `focus_changed`.
I'm automating my configuration through Bash scripting and in one of these scripts I've placed an event watcher loop done by 'herbstclient -i' and from there I would also like to be able to detect the closing and opening of the clients: can it already be done or would need a pre-defined, dedicated hook which is currently not implemented?

P.S.
before opening the issue I looked if it had already been asked but I didn't find any matches; I apologize if I just missed it...

**Comment by t-wissmann** [comment]
> (I've only been using herbstluftwm for a few days now so I don't yet know it in depth...)
Welcome aboard! :)

Reacting to the output of `herbstclient -i` is a bit tricky. On some cases, it is enough to use `herbstclient -w $event` where `$event` needs to be replaced by the name of the event you are waiting for.

If you need to react to more than one event, you can take a look at the `panel.sh` script. There the output of `herbstclient -i` is essentially piped into a `while read line ; do ... ; done` loop. For example, the following script monitors the urgency state of windows:

```bash
#!/usr/bin/env bash

herbstclient -i urgent | while IFS=$'\t' read -ra hook ; do
    echo "The urgency state of window ${hook[2]} changed to >${hook[1]}<!"
done
```
Note that in most cases, such loops can have nasty bugs and it's sometimes hard to keep track of them (they are not killed if the autostart is executed!).

**Comment by paoloschi** [comment]
> Welcome aboard! :)

Thank you! and I have a feeling I'll be here a long time because this project is proving to be a great experience: kudos to you :-)
I only regret not having installed it before!

With Bash I'm more familiar than with the English language and so with all evidence I did not express myself in such a way as to make myself understood: I've already developed my own script that includes a loop with `herbstclient -i … | while read …` and it's already working really well for my expectations (…)
Sorry I wasn't clear enough, let's see if I can better illustrate my request:
In the situation of wanting to intercept the two conditions __client_has_opened__ and/or __client_has_closed__, I found that there __are not__ two predefined hooks for such events, or at least so it seemed to me...
I ask how could I do it so that my _while_ loop can intercept the two above mentioned conditions or to know if for this feature, two new dedicated hooks should possibly be implemented in _herbstluftwm_?
In the second case, this issue would turns into a _feature request_, I suppose...

**Comment by tiosgz** [comment]
I remember having a rule spawning a `new_client` hook, but I don’t know of any way to get notified of a client being closed.

**Comment by t-wissmann** [comment]
Ah, I see! You can create a `rule client_has_opened` hook yourself by adding the rule
```
herbstclient rule hook=client_has_opened
```
as mentioned by @tiosgz. The other one is more tricky. The easiest is probably to connect to X yourself and to try to get notified via ewmh. (There's a [ewmh](https://ewmh.readthedocs.io/en/latest/) python module, so maybe your entire script can be written as a python script using the ewmh module)

**Comment by tiosgz** [comment]
> The easiest is probably to connect to X yourself and to try to get notified via ewmh.

…and to keep it all finally handled by the script, `emit_hook` :-)

**Comment by paoloschi** [comment]
> `herbstclient rule hook=client_has_opened`

aha, that's how it can be simply done! ..I said I'm a novice; I've been consulting the manual for days but with certain mechanisms I still have to get used to...
thanks both for giving me these valuable hints; I close right now and go back to studying and experimenting ... :-)
