### ISSUE TITLE
Focus last window [feature request]

### ISSUE THREAD

**Issue by vyp** [herbstluftwm/herbstluftwm#98]
I may have missed it, but is there a command to focus the previously focused window? (ala alt+Tab from microsoft windows)

I know for example there's `use-previous` for focusing the last tag, but having one for windows would be nice. I find it really convenient to use especially if I'm switching between two windows a lot, it's really easy to just press the same keybinding rather than having to press a different one each time to switch back.

**Comment by vyp** [comment]
(I have this workaround in `autostart` atm, but obviously it's stupid and would like a better way.)

``` bash
pkill -x herbstclient || true

current_win="$HOME/.config/herbstluftwm/current-win"
last_win="$HOME/.config/herbstluftwm/last-win"

herbstclient -i focus_changed | \
while read hook winid title; do
  [[ -f $current_win ]] && cat $current_win > $last_win
  echo $winid > $current_win
done &
```

And then just bind to `herbstclient jumpto $(cat ~/.config/herbstluftwm/last-win)`.

**Comment by ypnos** [comment]
I wouldn't call this a workaround neither stupid. Here are some tips on how you can improve your script:

* Watch for several hooks at once, e.g. `herbstclient -i '(focus_changed|trigger_lastwin|reload)`
  1. When `focus_changed`, save the last and current winid in variables `$lastwin`, `$curwin` instead of files
  2. When `trigger_lastwin`, execute `herbstclient jumpto $lastwin`
  3. When `reload`, die
* In your autostart, bind to `emit_hook trigger_lastwin`

I think that's a bit more slick. Here is Perl code sample that uses the same tricks (for a different purpose): https://github.com/ypnos/hlwm/blob/master/activities.pl

**Comment by t-wissmann** [comment]
I suggest the following. It is basically what ypnos wrote, but it uses hlwm attributes instead of variables:
```bash
#!/usr/bin/env bash

init_focuslastwindow=(
  chain
    # quit existing instances of loop below
    , emit_hook quit_focuslastwindow
    # if the key is pressed
    , keybind Alt-Tab
        # read the content of the my_lastwin attribute
        substitute LASTWIN my_lastwin
            # and jump there
            jumpto LASTWIN
    # create necessary attributes, but do not fail if they already exist
    , silent try new_attr string my_lastwin
    , silent try new_attr string my_curwin
    # fill them with the current window id
    , and ,, silent attr clients.focus
          ,, substitute WIN clients.focus.winid set_attr my_curwin WIN
          ,, substitute WIN clients.focus.winid set_attr my_lastwin WIN
)

# run the initialization
herbstclient "${init_focuslastwindow[@]}"

herbstclient -i '(focus_changed|reload|quit_focuslastwindow)' | \
    while read h winid t ; do
        case "$h" in
            focus_changed)
                # never feed an 'unfocused' state into the queue
                # if a window is focused, shift the content of my_curwin into
                # my_lastwin. Note that we use $winid here and not the content
                # of clients.focus.winid in order to avoid race conditions.
                [[ "$winid" != "0x0" ]] && \
                herbstclient and \
                    , substitute WIN my_curwin set_attr my_lastwin WIN \
                    , set_attr my_curwin "$winid"
                ;;
            *)  # on any other hook, quit this loop. Note that the idling
                # herbstclient still lives until the next time a hook arrives
                # and then quits because it can not write to stdout anymore
                break ;;
        esac
    done

```

**Comment by vyp** [comment]
Wow these solutions are neat! Thank you both.

@ypnos I felt it was a workaround since it saved the variables in files, but now my mind just exploded after seeing how useful and powerful hlwm hooks can be, so thanks. And thank you for all the detailed comments @t-wissmann! :smiley:
