### ISSUE TITLE
How to map Printscreen key

### ISSUE THREAD

**Issue by adamgajzlerowicz** [herbstluftwm/herbstluftwm#981]
Not sure what is the key for it is

`hc keybind XF86AudioMute spawn amixer set Master toggle` is for mute. What is the printscreen key please?

Thanks

**Comment by t-wissmann** [comment]
It is `Print`, if I'm not mistaken.

**Comment by jsav0** [comment]
> It is `Print`, if I'm not mistaken.

Confirmed it is `Print` for me. You can check a keysym by running `xev -events keyboard` and checking the output after pressing a key.

**Comment by adamgajzlerowicz** [comment]
I think you are right. It is `Print`, but for some reason it presents a bit of weird behavior.

I added a mapping like this:
`hc keybind Print spawn scrot '/tmp/%F_%T_$wx$h.png' -s -e 'xclip -selection clipboard -target image/png -i $f'`

Given that `scrot` and `xclipt` are installed the following `scrot '/tmp/%F_%T_$wx$h.png' -s -e 'xclip -selection clipboard -target image/png -i $f'` allows me to select part of screen and copy it to clipboard for pasting. But in herbstluftwm, when mapped to Print, the cursor changes to "select area mode" and changes back. 

Thus to make the area screenshot I need to open the terminal and run the script each time. Can you please advise how to do this better? Perhaps you have a better snipped on your own?

Than you so much!

**Comment by t-wissmann** [comment]
I think the issue is that the scrot program attempts to grab the keyboard&mouse, but it is still used by hlwm because the key is not released yet. This is an issue of hlwm, because hlwm does not allow it  yet to bind something to key releases. The best workaround I am aware of is to add a small delay before `scrot` is called:
```
herbstclient keybind Mod1-Mod4-e spawn bash -c "sleep 0.2 ; scrot '/tmp/%F_%T_\$wx\$h.png' -s -e 'xclip -selection clipboard -target image/png -i \$f'"
```
(because of the `bash` process around it, we need to escape the `$` characters)

**Comment by jsav0** [comment]
> I think you are right. It is `Print`, but for some reason it presents a bit of weird behavior.
> 
> I added a mapping like this:
> `hc keybind Print spawn scrot '/tmp/%F_%T_$wx$h.png' -s -e 'xclip -selection clipboard -target image/png -i $f'`
> 
> Given that `scrot` and `xclipt` are installed the following `scrot '/tmp/%F_%T_$wx$h.png' -s -e 'xclip -selection clipboard -target image/png -i $f'` allows me to select part of screen and copy it to clipboard for pasting. But in herbstluftwm, when mapped to Print, the cursor changes to "select area mode" and changes back.
> 
> Thus to make the area screenshot I need to open the terminal and run the script each time. Can you please advise how to do this better? Perhaps you have a better snipped on your own?
> 
> Than you so much!

As a workaround excluding herbstluftwm config, you can add an additional application to manage your keybinds: `sxhkd`. I only put critical things like spawning a terminal/dmenu into my hlwm config. I use sxhkd for all other custom keybinds.

**Comment by adamgajzlerowicz** [comment]
@t-wissmann Thank you so much - now it is working perfectly!
