### ISSUE TITLE
[newbie question] resizing frames with mouse

### ISSUE THREAD

**Issue by paoloschi** [herbstluftwm/herbstluftwm#986]
As far as I can see, the way to get frame resizing using the mouse is to point and then drag the decoration of a client while the edge of the frames is not in itself draggable.
If this assumption is incorrect, I'm about to ask a meaningless question... 

I really like not having decorations when I only have one single client in a frame, so in my preferences I have  `smart_window_surroundings`  to  `on`.
But if none of the frames in the current tag contains more than one client, then this is a situation where I can't resize the frames with the mouse and I have to add a client in the same frame where a other one is already present so that the theme switches from _minimal_ to _normal_ (which makes the window decorations appear) and only then I can resize the frames by dragging whit mouse.

If all this is correct, would it take me then that when the frames are more than one the `smart_window_surroundings` attr is no longer set even if there is only one window for each frame? 
My question is: can I get this through a particular configuration or should I switch on|off `smart_window_surroundings` from bash scripting based on `tags.focus.frame_count` ? (as I said in a previous post, I'm already monitoring events in a permanent way with a  `herbstclient -i | while read...`  loop... )
thank you for your patience...

**Comment by t-wissmann** [comment]
You can resize the tiled clients with `Mod-RightClick` even if the client does not have a window decoration. (You're right that the frame border itself can't be dragged)

**Comment by paoloschi** [comment]
thanks for the hint
after years of Openbox, where with just mouse-clicks I could get everything, now I got lazy :-)
yet I had come up by myself with the need of a combined keyboard-mouse action to move the hlwm float windows; I realized that any key pressed on the decoration always leads to get just a resize otherwise...

**Comment by t-wissmann** [comment]
By the way, you can also use the standard keybindings for focusing/moving/resizing (per default Mod-/Mod-Shift/Mod-Control plus h/j/k/l/arrows) also for floating windows! (So no mouse required at all)

**Comment by AckslD** [comment]
@t-wissmann I never got the resizing to work with the standard keybindings. If I manually try the command, i.e. `herbstclient resize up +0.1`  I just get `resize: No neighbour found ` even if there are neighbouring windows. Any idea what I might be doing wrong?

**Comment by t-wissmann** [comment]
In tiling mode, the command `herbstclient resize up +0.1` requires that there is a window "north of" the focused window, and in floating mode, the command should always work, even if there are no other windows on the tag (then it resizes to the monitor border). Can you send a screenshot of your desktop such that I can see the window layout?

**Comment by tiosgz** [comment]
> there is a window "north of" the focused window

It requires that there is a frame, doesn’t it?

**Comment by AckslD** [comment]
@t-wissmann For example like this

![gscreenshot_2021-02-01-120651](https://user-images.githubusercontent.com/23341710/106450824-ffcd3a80-6485-11eb-8ca4-df169bcefe73.png)

**Comment by t-wissmann** [comment]
Right, as @tiosgz wrote, it requires a neighbouring frame. All 4 windows are contained in the same frame and you can't resize windows within a frame, but only frames. After running `herbstclient split explode`, you have two frames and then you can resize them.

**Comment by AckslD** [comment]
> It requires that there is a frame, doesn’t it?

Ah I see! I never really go the difference between frames and windows :) I guess I only been using a single frame per index. Splitting the windows into frames makes resizing indeed work.

Why is there a difference between windows and frames actually? In what situations would I want to split into windows in a single frame vs multiple frames?

**Comment by t-wissmann** [comment]
The frame layout provides the flexibility and the 'multiple windows within a frame' is the automation. I have one window per frame nearly all the time (and `split explode` is bound to Mod-v).

**Comment by AckslD** [comment]
I see, thanks for the information :) Is there some way to automatically put new windows in new frames? Or is that not desirable in some situations?

**Comment by t-wissmann** [comment]
No there is no way to automate it, simply because I never had the urge to do this.

**Comment by tiosgz** [comment]
> Is there some way to automatically put new windows in new frames?

Are you sure that you want it? That way if you opened three windows w/ the original frame in horizontal layout, instead of each of the windows taking 1/3 of the space, one would use 1/2 & the other two would use 1/4 each.

**Comment by AckslD** [comment]
@t-wissmann @tiosgz After trying out this new knowledge, I know understand the point :) It's funny, I've been using hlwm for quite a while and really enjoyed it and now it suddenly got even better 🎉 Thanks for that :)
