### ISSUE TITLE
Balance frames? [feature request]

### ISSUE THREAD

**Issue by vyp** [herbstluftwm/herbstluftwm#99]
Is there a way to reset the frame split fractions? (as in say to 0.5 for default, or to a given fraction)

**Comment by t-wissmann** [comment]
No, there is none. It may change in future versions, but something like this is of quite a low priority.

You can simply adjust the split fraction using the existing (relative) keybinds.

**Comment by t-wissmann** [comment]
In the current git version, you can write `0.5` to the `fraction` attribute of frame objects. For example, you could do the following:
```bash
for idx in .{,{0.,1.}{,{0.,1.}{,{0.,1.}}}} ; do
   hc attr tags.focus.tiling.root${idx}fraction 0.5
done
```
(This is a brute-force solution, because it tries all frame indices up to depth 3 and tries to set the fraction to 0.5)

**Comment by t-wissmann** [comment]
As soon as #1394 is merged, you can recursively set the fraction to 0.5 for all frames on a tag:
```
$ hc foreach F tags.focus.tiling.root --recursive sprintf ATTR '%c.fraction' F try silent set_attr ATTR 0.5
```
This also tries to set the fraction attribute for leaf frames, which of course have no fraction attribute. Hence, I supress the error messages via `try silent`.

If there is anything else, feel free to (re-)open this or another issue.
