### ISSUE TITLE
undesirable interaction between compositor and windowborder drawing

### ISSUE THREAD

**Issue by bklaase** [herbstluftwm/herbstluftwm#992]
When using VTE based terminals (termite, xfce4-terminal, etc) I get the behavior, that when a compositor is enabled, the borders become transparent. Urxvt (not being VTE based) is fine.

I found this (old) discussion on the matter in the termite issuetracker:
https://github.com/thestinger/termite/issues/200

Is this the same problem? Most wm's (bspwm, xfce4, openbox) don't exibit the issue, but some do (windowchef, xmonad, hlwm).

**Comment by t-wissmann** [comment]
I once had this issue but I'm not experiencing it anymore
![term-border-transparent](https://user-images.githubusercontent.com/9048813/90269503-0543b380-de59-11ea-8f70-41b0e87dfc69.png)
I'm using picom 8-2 (picom 8, archlinux package version 2), and as I've just noticed, I don't have any special configuration, so I assume the default picom config from the arch package is used.

**Comment by t-wissmann** [comment]
Ah, picom is still respecting `~/.config/compton.conf`, and this is mine: https://github.com/t-wissmann/dotfiles/blob/master/config/compton.conf

**Comment by bklaase** [comment]
Thank you!
I will compare and let other know here what setting causes, or fixes the behavior!

**Comment by bklaase** [comment]
Alas, same picom, same distro and even with your config:
![image](https://user-images.githubusercontent.com/8513117/90277547-1b0ba580-de66-11ea-89fb-30a95aadb68e.png)
![image](https://user-images.githubusercontent.com/8513117/90277640-42627280-de66-11ea-81b8-93104294b726.png)

Perhaps a driver thing. (intel gpu)... perhaps I'll test with nvidia and radeon cards later.

To be honest, my largest gripe was with borders getting ugly on max layout. When reading the man I found 
`hide_covered_windows` and those issues went away. It's even better now then having terminal content shine through, so I am happy :)

I'll close this, thanks for thinking along!

**Comment by t-wissmann** [comment]
Definitely can confirm that I had this too. Maybe it's really a driver thing. By the way, hlwm is already doing what's proposed in https://github.com/chjj/compton/issues/240#issuecomment-62245919 -- namely to use a windows color-scheme for color conversion.

**Comment by Barbarossa93** [comment]
Unfortunately after going through your `compton.conf` @t-wissmann  nothing seemed to work. I used to use a tool called `chwb2` from wmutils that had this exact same problem that eventually got fixed. [Here's](https://github.com/wmutils/opt/issues/48#issuecomment-667541248) about where in the issue were the logistics started to be discussed. Maybe the logic here can be applied to HLWM?

**Comment by Barbarossa93** [comment]
It also looks like there was some discussion over in [picom](https://github.com/yshui/picom/issues/285) about this issue. I guess picom expects a premultiplied value?

>The window border have a color whose alpha value is 0, causing the border to be rendered improperly, because picom expects a premultiplied color

Not sure how you're doing it based on the old compton issue

**Comment by t-wissmann** [comment]
I can reproduce it on my intel graphics laptop but I didn't  manage to fix it. As soon as I understand what dwm is doing in their [alpha patch](https://dwm.suckless.org/patches/alpha/dwm-alpha-6.1.diff) chances hopefully get better that this can be fixed for hlwm too

**Comment by Barbarossa93** [comment]
I just realized, should I go ahead and make a new issue since this is still a problem?
