### ISSUE TITLE
Rule to always bring

### ISSUE THREAD

**Issue by AckslD** [herbstluftwm/herbstluftwm#995]
Is there some way to specify a rule that always brings a window to the current tag? I would like to have this for the onboard keyboard I use in tablet mode.

**Comment by t-wissmann** [comment]
Bringing a window to the current tag is the default behaviour.
```
hc rule class=TheClassOfYourKeyboard tag=''
```

**Comment by AckslD** [comment]
Thanks @t-wissmann! Maybe a rule is what I am looking for. Since the rule is only applied when the window is opened as far as I understand. What I would like is that the keyboard/window is brought automatically to whatever tag I am on, not only when the window is created. Is there some other way to achieve this, or should I call `apply_rules` in some way whenever I switch tags?

**Comment by t-wissmann** [comment]
Ah, I understand. The feature you are asking for is often called 'sticky windows' and this feature has been requested recently in https://github.com/herbstluftwm/herbstluftwm/issues/976 but it is not yet implemented. The best workaround at the moment is to call `bring` with the respective window id eacht time after switching tags. 
Alternatively, maybe you can unmanage the window of your (onscreen?) keyboard. (Add a rule matching the window and set `manage=off` there). Then the window is also always visible. Maybe, you need to  `raise` the window manually such that it is above the other windows.

**Comment by AckslD** [comment]
Cool, thanks for the info :) I'll try out what you suggested and keep an eye out for the 'sticky window' feature.

**Comment by AckslD** [comment]
@t-wissmann I didn't manage to get it to work with `manage=off` but I think I'll just wait for the sticky windows feature and think we can close this
