### ISSUE TITLE
tag_renamed hook does not show old name

### ISSUE THREAD

**Issue by The-Compiler** [herbstluftwm/herbstluftwm#999]
The `tag_renamed` hook only has the new name as argument, not the old one. Thus, it's only really useful as as a notification to call `tag_status` again, but it'd be nice if it carried that kind of information.

Conveniently, it's also currently undocumented in the manpage, so I suppose we could just change it? From a quick GitHub search, nobody really seems to use its argument:

- [`activities.pl` by @ypnos](https://github.com/ypnos/hlwm/blob/61b6fccd6259257229fd891bbf67b949d1b8ce21/activities.pl#L64-L73) (which mentions the same issue)
- [Someone's `panel.sh`](https://github.com/razzfox/dotfiles/blob/5bf5649fa80281f0e1190ec2270eca15dc28c084/config/herbstluftwm/panel.sh) (the default uses `tag*` instead)
- [ggbar](https://github.com/lutobler/ggbar/blob/c51f2c828763a39c8d3f6b007475f551fbb5c330/src/main.rs#L290)

**Comment by blarz** [comment]
Thanks for the report! Should be fixed with #1016

**Comment by The-Compiler** [comment]
@blarz Thanks for the fix! :+1:
